posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Subcontractor</fullName>
        <active>true</active>
        <description>Those who do work on behalf of PosiGen (Installers, EE Upgraders, etc)</description>
        <label>Subcontractor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Support Vendors (Accounting, Professional Services, etc)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Group__c.object
<CustomObject>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxGroup_Name__c</fullName>
        <label>BoxGroup Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Profile_Id__c</fullName>
        <label>SF Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Group</label>
    <nameField>
        <label>Box Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Profile__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_SubFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix SubFolder</label>
        <referenceTo>BoxAccessMatrix_SubFolder__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Profiles</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lookup_Field_Name__c</fullName>
        <label>Lookup Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Profile</label>
    <nameField>
        <label>BoxAccessMatrix Profiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Stage__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix Profile</label>
        <referenceTo>BoxAccessMatrix_Profile__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Stages</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box_Permission__c</fullName>
        <label>Box Permission</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previewer Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer Uploader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Stage</label>
    <nameField>
        <label>BoxAccessMatrix Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_SubFolder__c.object
<CustomObject>
    <fields>
        <fullName>SubFolder_Name__c</fullName>
        <label>SubFolder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix SubFolder</label>
    <nameField>
        <label>BoxAccessMatrix SubFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix SubFolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>PVI_Rails_Installed_Date__c</fullName>
        <description>Not used by the User.  For the Apex trigger.</description>
        <label>PVI Rails Installed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pipeline_Stage__c</fullName>
        <formula>IF( AND(Permanent_Removal__c, NOT(ISNULL(R_P_Removal_Date__c))), &quot;Removed &amp; Terminated&quot;,
IF( Num_of_LD_Leases__c &gt; 0
	, &quot;Boarded&quot;,
    IF(TEXT( StageName ) = &quot;Closed Won&quot;,
		IF( OR( Lease_Boarding_Status__c = &quot;Upload to LD (based on CAO File)&quot;,Lease_Boarding_Status__c = &quot;Boarded&quot;, Has_Been_Boarded__c )
			, &quot;Boarded&quot;
			, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c)) &amp;&amp; NOT(ISNULL(EU_Completed_Date__c))
				, &quot;Need to Board&quot;
				, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Solar Panels&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Uptown Solar Lease&quot;)) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c))
					, &quot;Need to Board&quot;
					, IF( AND( NOT(ISNULL(PVI_Net_Meter_Install_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
						, &quot;Need to Board&quot;
						, IF(  AND(  NOT(ISNULL(PVI_Placed_In_Service_Date__c)), ISNULL(EU_Completed_Date__c), Has_EE_as_a_Solar_Product__c )
							, &quot;Pending EU&quot;
							, IF( AND( NOT(ISNULL(PVI_Placed_In_Service_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
								, &quot;Pending Net Meter&quot;
								, IF ( AND(ISNULL(PVI_Placed_In_Service_Date__c ), NOT(ISNULL(PVI_Rails_and_Panels_Left_WH_Date__c)))
									, &quot;PV System Left Warehouse&quot; 
									, TEXT( StageName )
								)
							)
						)
					)
				)
			)
        )
        ,TEXT( StageName )
	)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>EE_Completed_Date__c</fullName>
        <label>EE Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PVI_Rails_Installed_Date__c</fullName>
        <label>PVI Rails Installed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PVI_Rails_and_Panels_Left_Warehouse_Date__c</fullName>
        <label>PVI Rails and Panels Left Warehouse Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Release</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subcontractor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subcontractor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Subcontractor, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Child_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Trigger_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Attachment_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attachment Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BoxAccessMatrixStage_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BoxAccessMatrixStage Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FeedItem_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FeedItem Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LD_Lease_trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>LD Lease trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LogsTrigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LogsTrigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opportunity Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>PM Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Task_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>for TaskTriggerNew</description>
        <label>Task Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Setting</label>
</CustomObject>

posiGen_FullsendBox/src/classes/TestProjectTriggerHandler.cls
@isTest
public class TestProjectTriggerHandler {
    Static testmethod void method2(){
      UtilityController.recursive = true;
            List<Sub_folder__c> subList = new List<Sub_folder__c>();
            RecordType rt2 = [Select id from RecordType where name='EE Upgrade'];
            RecordType rt = [Select id from RecordType where name='Subcontractor'];
            UtilityController.recursive =true;
            
            
            Account acc =new Account();
            acc.name = 'irfan khan';
            acc.RecordTypeId = rt.Id;
            insert acc;
            system.assert(acc.id!=null);
            
            
            
            Trigger_Setting__c ts = new Trigger_Setting__c(Project_Trigger__c =true);
            insert ts; 
            
            Opportunity opp = new Opportunity();
            opp.name = 'Test opp';
            opp.accountId = acc.id;
            opp.CloseDate = date.today();
            opp.stageName = 'Release to Installer';
            OpportunityTriggerHandler.firstRun =false; 
            insert opp;
            
            Opportunity oppr =[Select id, Pipeline_stage__c from opportunity where id=:opp.id];
            
            Sub_folder__c sf = new Sub_folder__c();
            sf.name = 'EE';
            sf.cf_opportunity__c = oppr.id;
            sf.cf_box_folder_id__c = '11446498';
            insert sf;
            
            subList.add(sf);
            List<String> fldsubList = new List<String>();
            fldsubList.add(sf.cf_box_folder_id__c);
           
            Profile prf= [select id,Name From Profile Where Name='EE partner user'];
            
            BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
            bams.SubFolder_Name__c='EE';
            bams.Name='EE';
            insert bams;
            
            BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
            bamp.BoxAccessMatrix_SubFolder__c=bams.id;
            bamp.Profile_Id__c=prf.id;
            bamp.Profile_Name__c='EE partner user';
            bamp.Lookup_Field_Name__c='Subcontractor__c';
            insert bamp;
            
            BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
            BAM.Box_Permission__c='Viewer';
            BAM.BoxAccessMatrix_Profile__c=bamp.id;
            BAM.Stage__c=oppr.Pipeline_stage__c;
            BAM.check__c=true;
            insert BAM;
            
            Box_Group__c bg = new Box_Group__c();
            bg.BoxGroup_Id__c='34087847';
            bg.BoxGroup_Name__c='test box grop';
            bg.SF_Profile_Id__c=prf.id;
            insert bg;
            
            
            
            List<String> cnLst = new List<String>(); 
            Contact con = new Contact(FirstName='Test1',LastName='State1',email='newCon@abc.com',AccountId=acc.id);
            insert con;
            
            cnlst.add(con.email);
            Set<String> cnSet = new Set<String>(cnLst);
            
            Project__c pj = new Project__c();
            pj.RecordTypeId=rt2.id;
            pj.Name = 'old prj';
            pj.Opportunity__c = opp.id;
            pj.Subcontractor__c = acc.id;
            insert pj;
            
            
            Account acc2 =new Account();
            acc2.name = 'Anki khan';
            acc2.RecordTypeId = rt.id;
            insert acc2;
            
            Set<String> cnSet2 = new Set<String>();
            Contact con2 = new Contact(FirstName='Test1',LastName='State1',email='crewCon@abc.com',AccountId=acc2.id);
            insert con2;
            cnSet.add(con2.email);
            
            
            pj.Subcontractor__c =acc2.id;
            UtilityController.recursive =true;
            OpportunityTriggerHandler.firstRun =false; 
            pj.EE_Completed_Date__c = system.today();
            pj.PVI_Rails_and_Panels_Left_Warehouse_Date__c = system.today();
            pj.PVI_Rails_Installed_Date__c = system.today();
            update pj;
            
            ProjectTriggerHandler pt = new ProjectTriggerHandler();
            pt.bulkBefore();
            pt.bulkAfter();
            pt.beforeInsert();
            pt.beforeUpdate();
            pt.beforeDelete();
            pt.afterDelete();
            pt.afterUnDelete();
            
            
    }
    
    Static testmethod void method22(){
      UtilityController.recursive = true;
        List<Sub_folder__c> subList = new List<Sub_folder__c>();
        RecordType rt2 = [Select id from RecordType where name='PV Install'];
        RecordType rt = [Select id from RecordType where name='Subcontractor'];
        UtilityController.recursive =true;
        
        
        Account acc =new Account();
        acc.name = 'irfan khan';
        acc.RecordTypeId = rt.Id;
        insert acc;
        
        
        Trigger_Setting__c ts = new Trigger_Setting__c(Attachment_Trigger__c=true,BoxAccessMatrixStage_Trigger__c=true,FeedItem_Trigger__c=true,LD_Lease_trigger__c=true,LogsTrigger__c=true,Opportunity_Trigger__c=true,PM_Trigger__c=true,Project_Trigger__c=true,Task_Trigger__c=true,User_Trigger__c=true);
        insert ts; 
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Release to Installer';
        OpportunityTriggerHandler.firstRun =false; 
        insert opp;
        
        Opportunity oppr =[Select id, Pipeline_stage__c from opportunity where id=:opp.id];
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Sales';
        sf.cf_opportunity__c = oppr.id;
        sf.cf_box_folder_id__c = '11446498';
        insert sf;
        
        subList.add(sf);
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
       
        Profile prf= [select id,Name From Profile Where Name='EE partner user'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Sales';
        bams.Name='Sales';
        insert bams;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='EE partner user';
        bamp.Lookup_Field_Name__c='Subcontractor__c';
        insert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=oppr.Pipeline_stage__c;
        BAM.check__c=true;
        insert BAM;
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        insert bg;
        
        
        
        List<String> cnLst = new List<String>(); 
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='newCon@abc.com',AccountId=acc.id);
        insert con;
        
        cnlst.add(con.email);
        Set<String> cnSet = new Set<String>(cnLst);
        
        Project__c pj = new Project__c();
        pj.RecordTypeId=rt2.id;
        pj.Name = 'old prj';
        pj.Opportunity__c = opp.id;
        pj.Subcontractor__c = acc.id;
       
        insert pj;
        
        Account acc2 =new Account();
        acc2.name = 'Anki khan';
        acc2.RecordTypeId = rt.id;
        insert acc2;
        
        Project__c pj2 = new Project__c();
        pj2.RecordTypeId=rt2.id;
        pj2.Name = 'old prj aa';
        pj2.Opportunity__c = opp.id;
        pj2.Subcontractor__c = acc2.id;
        
        Set<String> cnSet2 = new Set<String>();
        Contact con2 = new Contact(FirstName='Test1',LastName='State1',email='crewCon@abc.com',AccountId=acc2.id);
        insert con2;
        cnSet.add(con2.email);
        
        
        pj.Subcontractor__c =acc2.id;
        UtilityController.recursive =true;
        OpportunityTriggerHandler.firstRun =false; 
        update pj;
       
       
       
        ProjectTriggerHandler pt = new ProjectTriggerHandler();
        pt.bulkBefore();
        pt.bulkAfter();
        pt.beforeInsert();
        pt.beforeUpdate();
        pt.beforeDelete();
        pt.afterDelete();
        pt.afterUnDelete();
        
    }
  
    
    Static testmethod void method23(){
      
        List<Sub_folder__c> subList = new List<Sub_folder__c>();
        RecordType rt2 = [Select id from RecordType where name='PV Install'];
        RecordType rt = [Select id from RecordType where name='Subcontractor'];
        UtilityController.recursive =true;
        
        
        Account acc =new Account();
        acc.name = 'irfan khan';
        acc.RecordTypeId = rt.Id;
        insert acc;
        
        
        
        
        Trigger_Setting__c ts = new Trigger_Setting__c(Project_Trigger__c =true);
        insert ts; 
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Release to Installer';
        OpportunityTriggerHandler.firstRun =false; 
        insert opp;
        
        Opportunity oppr =[Select id, Pipeline_stage__c from opportunity where id=:opp.id];
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Funding-Vendor';
        sf.cf_opportunity__c = oppr.id;
        sf.cf_box_folder_id__c = '11446498';
        insert sf;
        
        subList.add(sf);
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
       
        Profile prf= [select id,Name From Profile Where Name='EE partner user'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Funding-Vendor';
        bams.Name='Funding-Vendor';
        insert bams;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='EE partner user';
        bamp.Lookup_Field_Name__c='Subcontractor__c';
        insert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=oppr.Pipeline_stage__c;
        BAM.check__c=true;
        insert BAM;
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        insert bg;
        
        
        
        List<String> cnLst = new List<String>(); 
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='newCon@abc.com',AccountId=acc.id);
        insert con;
        
        cnlst.add(con.email);
        Set<String> cnSet = new Set<String>(cnLst);
        
        Project__c pj = new Project__c();
        pj.RecordTypeId=rt2.id;
        pj.Name = 'old prj';
        pj.Opportunity__c = opp.id;
        pj.Subcontractor__c = acc.id;
        insert pj;
        
        Account acc2 =new Account();
        acc2.name = 'Anki khan';
        acc2.RecordTypeId = rt.id;
        insert acc2;
        
        Set<String> cnSet2 = new Set<String>();
        Contact con2 = new Contact(FirstName='Test1',LastName='State1',email='crewCon@abc.com',AccountId=acc2.id);
        insert con2;
        cnSet.add(con2.email);
        
        
        //pj.Subcontractor__c =acc2.id;
        //update pj;
      
      
        ProjectTriggerHandler pt = new ProjectTriggerHandler();
        pt.bulkBefore();
        pt.bulkAfter();
        pt.beforeInsert();
        pt.beforeUpdate();
        pt.beforeDelete();
        pt.afterDelete();
        pt.afterUnDelete();
        
    }
   
    Static testmethod void method24(){
        
        UtilityController.recursive = true;
        List<Sub_folder__c> subList = new List<Sub_folder__c>();
        RecordType rt2 = [Select id from RecordType where name='PV Install'];
        RecordType rt = [Select id from RecordType where name='Subcontractor'];
        UtilityController.recursive =true;
        
        
        Account acc =new Account();
        acc.name = 'irfan khan';
        acc.RecordTypeId = rt.Id;
        insert acc;
        
        
        Trigger_Setting__c ts = new Trigger_Setting__c(Project_Trigger__c =true);
        insert ts; 
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Release to Installer';
        OpportunityTriggerHandler.firstRun =false; 
        insert opp;
        
        Opportunity oppr =[Select id, Pipeline_stage__c from opportunity where id=:opp.id];
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Application';
        sf.cf_opportunity__c = oppr.id;
        sf.cf_box_folder_id__c = '11446498';
        insert sf;
        
        subList.add(sf);
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
       
        Profile prf= [select id,Name From Profile Where Name='EE partner user'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Application';
        bams.Name='Application';
        insert bams;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='EE partner user';
        bamp.Lookup_Field_Name__c='Subcontractor__c';
        insert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=oppr.Pipeline_stage__c;
        BAM.check__c=true;
        insert BAM;
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        insert bg;
        
        
        
        List<String> cnLst = new List<String>(); 
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='newCon@abc.com',AccountId=acc.id);
        insert con;
        
        cnlst.add(con.email);
        Set<String> cnSet = new Set<String>(cnLst);
        
        Project__c pj = new Project__c();
        pj.RecordTypeId=rt2.id;
        pj.Name = 'old prj';
        pj.Opportunity__c = opp.id;
        pj.Subcontractor__c = acc.id;
       
        insert pj;
        
        Account acc2 =new Account();
        acc2.name = 'Anki khan';
        acc2.RecordTypeId = rt.id;
        insert acc2;
        
        Set<String> cnSet2 = new Set<String>();
        Contact con2 = new Contact(FirstName='Test1',LastName='State1',email='crewCon@abc.com',AccountId=acc2.id);
        insert con2;
        cnSet.add(con2.email);
        
        
        pj.Subcontractor__c =acc2.id;
        UtilityController.recursive =true;
        
        OpportunityTriggerHandler.firstRun =false; 
        update pj;
        
        
        ProjectTriggerHandler pt = new ProjectTriggerHandler();
        pt.bulkBefore();
        pt.bulkAfter();
        pt.beforeInsert();
        pt.beforeUpdate();
        pt.beforeDelete();
        pt.afterDelete();
        pt.afterUnDelete();
        
        ts.Project_Trigger__c =false;
        update ts; 
        
        UtilityController.recursive =true;
        OpportunityTriggerHandler.firstRun =false; 
        RecordType rt3 = [Select id from RecordType where name='EE Assessment'];
        pj.RecordTypeId=rt3.id;
        pj.EE_Completed_Date__c  = system.today();
        update pj;

    } 
    
    Static testmethod void method25(){
        
        UtilityController.recursive = true;
        RecordType rt2 = [Select id from RecordType where name='EE Upgrade'];
        RecordType rt = [Select id from RecordType where name='Subcontractor'];
        UtilityController.recursive =true;

        Account acc =new Account();
        acc.name = 'irfan khan';
        acc.RecordTypeId = rt.Id;
        insert acc;
        
        
        Trigger_Setting__c ts = new Trigger_Setting__c(Project_Trigger__c =false);
        insert ts; 
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Release to Installer';
        OpportunityTriggerHandler.firstRun =false; 
        insert opp;
        
       
    
        Project__c pj = new Project__c();
        pj.RecordTypeId=rt2.id;
        pj.Name = 'old prj';
        pj.Opportunity__c = opp.id;
        pj.Subcontractor__c = acc.id;
       
        insert pj;
        
        UtilityController.recursive =true;
        OpportunityTriggerHandler.firstRun =false; 

        pj.EE_Completed_Date__c = system.today();
        update pj;
        
      

    } 
    
    
    Static testmethod void method26(){
        
        UtilityController.recursive = true;
        RecordType rt2 = [Select id from RecordType where name='PV Feasibility'];
        RecordType rt = [Select id from RecordType where name='Subcontractor'];
        UtilityController.recursive =true;

        Account acc =new Account();
        acc.name = 'irfan khan';
        acc.RecordTypeId = rt.Id;
        insert acc;
        
        
        Trigger_Setting__c ts = new Trigger_Setting__c(Project_Trigger__c =false);
        insert ts; 
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Release to Installer';
        OpportunityTriggerHandler.firstRun =false; 
        insert opp;
        
       
    
        Project__c pj = new Project__c();
        pj.RecordTypeId=rt2.id;
        pj.Name = 'old prj';
        pj.Opportunity__c = opp.id;
        pj.Subcontractor__c = acc.id;
        insert pj;

    } 
    
    Static testmethod void method27(){
        
        UtilityController.recursive = true;
        RecordType rt2 = [Select id from RecordType where name='PV Removal'];
        RecordType rt = [Select id from RecordType where name='Subcontractor'];
        UtilityController.recursive =true;

        Account acc =new Account();
        acc.name = 'irfan khan';
        acc.RecordTypeId = rt.Id;
        insert acc;
        
        
        Trigger_Setting__c ts = new Trigger_Setting__c(Project_Trigger__c =false);
        insert ts; 
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Release to Installer';
        OpportunityTriggerHandler.firstRun =false; 
        insert opp;
        
       
    
        Project__c pj = new Project__c();
        pj.RecordTypeId=rt2.id;
        pj.Name = 'old prj';
        pj.Opportunity__c = opp.id;
        pj.Subcontractor__c = acc.id;
       
        insert pj;

    } 
    
   
}