posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Days_Delinquent__c</fullName>
        <label>LD Lease Days Delinquent</label>
        <summarizedField>LD_Lease__c.Days_Delinquent__c</summarizedField>
        <summaryForeignKey>LD_Lease__c.Account__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NVMContactWorld__NVM_Phone__c</fullName>
        <description>NewVoiceMedia click to dial Phone</description>
        <formula>IF( 
        LEN(  Phone  )&gt;0 , 
        HYPERLINK( &quot;/apex/NVMContactWorld__NVM_AgentUI_ClickToDialInitiator?number=&quot; &amp; 
                   SUBSTITUTE(Phone, &quot;+&quot;, &quot;%2B&quot;) &amp; 
                   &quot;&amp;oid=&quot; &amp; Id &amp; 
                   &quot;&amp;name=&quot; &amp;  Name &amp;
                   &quot;&amp;type=Account&quot;, 
                   Phone, &quot;nvm-clicktodial&quot;) 
                   &amp; &quot; &quot; &amp; IMAGE( &quot;../servlet/servlet.FileDownload?file=015A0000000FU0f&quot;, &quot;Dial&quot;), &quot;&quot;)</formula>
        <inlineHelpText>Click to dial Phone</inlineHelpText>
        <label>NVM Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numeric_ID__c</fullName>
        <externalId>true</externalId>
        <label>Numeric ID</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>NVMContactWorld__NVM_Phone__c</fullName>
        <description>NewVoiceMedia click to dial Phone</description>
        <formula>IF( 
        LEN(  Phone  )&gt;0 , 
        HYPERLINK( &quot;/apex/NVMContactWorld__NVM_AgentUI_ClickToDialInitiator?number=&quot; &amp; 
                   SUBSTITUTE(Phone, &quot;+&quot;, &quot;%2B&quot;) &amp; 
                   &quot;&amp;oid=&quot; &amp; Id &amp; 
                   &quot;&amp;name=&quot; &amp; FirstName &amp; &quot;%20&quot; &amp;  LastName &amp; 
                   &quot;&amp;type=Contact&quot;, 
                   Phone, &quot;nvm-clicktodial&quot;) 
                   &amp; &quot; &quot; &amp; IMAGE( &quot;../servlet/servlet.FileDownload?file=015A0000000FU0f&quot;, &quot;Dial&quot;), &quot;&quot;)</formula>
        <inlineHelpText>Click to dial Phone</inlineHelpText>
        <label>NVM Phone</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/LD_Lease__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account the record is related to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LD Leases</relationshipLabel>
        <relationshipName>LD_Leases</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Am_I_Concierge__c</fullName>
        <formula>Account__r.Owner.FullID__c   =  $User.FullID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Am I Concierge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Days_Delinquent__c</fullName>
        <description># of days the oldest past due invoice is delinquent</description>
        <inlineHelpText># of days the oldest past due invoice is delinquent</inlineHelpText>
        <label>Days_Delinquent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The Opportunity this LD Lease is related to.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>LD Leases</relationshipLabel>
        <relationshipName>LD_Leases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Past_Due__c</fullName>
        <description>Payment Amount Invoiced with a prior payment date, not yet paid. (Includes Base Rent, Fees, &amp; Taxes)</description>
        <inlineHelpText>Payment Amount Invoiced with a prior payment date, not yet paid. (Includes Base Rent, Fees, &amp; Taxes)</inlineHelpText>
        <label>Total_Past_Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LD Lease</label>
    <nameField>
        <label>LD Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LD Leases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Numeric_ID__c</fullName>
        <externalId>true</externalId>
        <label>Numeric ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>equals</operation>
                <value>Project Manager</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_User_Project_Manager_For</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solar_Product__c</fullName>
        <label>Solar Product</label>
        <picklist>
            <picklistValues>
                <fullName>Solar Hot Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Efficiency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solar Panels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uptown Solar Lease</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>System_Size_in_KW__c</fullName>
        <description>From PV Project</description>
        <label>System Size in KW</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>NVMContactWorld__NVM_Phone__c</fullName>
        <description>NewVoiceMedia click to dial Phone</description>
        <formula>IF( 
        LEN( Phone )&gt;0 , 
        HYPERLINK( &quot;/apex/NVMContactWorld__NVM_AgentUI_ClickToDialInitiator?number=&quot; &amp; 
                   SUBSTITUTE(Phone, &quot;+&quot;, &quot;%2B&quot;) &amp; 
                   &quot;&amp;oid=&quot; &amp; Id &amp; 
                   &quot;&amp;name=&quot; &amp; FirstName &amp; &quot;%20&quot; &amp;  LastName &amp; 
                   &quot;&amp;type=User&quot;, 
                   Phone, &quot;nvm-clicktodial&quot;) 
                   &amp; &quot; &quot; &amp; IMAGE( &quot;../servlet/servlet.FileDownload?file=015A0000000FU0f&quot;, &quot;Dial&quot;), &quot;&quot;)</formula>
        <inlineHelpText>Click to dial Phone</inlineHelpText>
        <label>NVM Phone</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/AccountDetailsController1.cls
//Controller Class for AccountDetails

Public without sharing class AccountDetailsController1{

    public AccountDetailsController1(ApexPages.StandardController controller) {

    }
       
    //Class Instances (get,set)
    
    Public String accountId {get;set;}  
    Public Account accRecord {get;set;} 
    Public List<SelectOption> listProjMan {get;set;} 
    Public String selMan {get;set;}
    Public List<SelectOption> listAccMan {get;set;} 
    Public String selAcc {get;set;}
    Public List<Account > allAccounts {get;set;}  
    Set<String> lstPMSet = new Set<String>();  
    
    private integer counter=0;  //keeps track of the offset
    private integer list_size=11; //sets the page size or number of rows
    Public integer total_size;  
    
         
    //constructor
    Public AccountDetailsController1()
    {         
        List<opportunity> lstPM = new List<opportunity >();   
        lstPM = [select Project_manager__r.name from opportunity where Project_manager__r.name != null limit 1000]; 
        
        List<Account> accountRecords = [Select id, Name,BillingCountry,phone, BillingStreet, AccountNumber,BillingCity, BillingAddress, BillingState, BillingPostalCode, PersonMobilePhone, PersonEmail, PersonHomePhone From Account order by name limit 1];
        accountId = accountRecords[0].Id;  
        getAccountDetails();       
                       
        lstPMSet.add('-None-');                       
        for(Opportunity op : lstPM) {  
            lstPMSet.add(op.Project_manager__r.name);            
        }
       
        listProjMan = new List<SelectOption>();
        for(String op : lstPMSet) {
            listProjMan.add(new SelectOption(op,op));
        }
        selMan = '-None-';
        listAccMan = new List<SelectOption>(); 
        selAcc = '-None-';            
        
        listAccMan.add(new SelectOPtion('-None-','-None-'));
        listAccMan.add(new SelectOption('I am Account Manager, 11-30','I am Account Manager, 11-30'));
        listAccMan.add(new SelectOption('I am Account Manager, 31-60','I am Account Manager, 31-60'));
        listAccMan.add(new SelectOption('I am Account Manager, 61-90','I am Account Manager, 61-90'));
        listAccMan.add(new SelectOption('I am Account Manager, 91-180','I am Account Manager, 91-180'));
        listAccMan.add(new SelectOption('I am Account Manager, 180+','I am Account Manager, 180+'));
        
        total_size = [Select count() From Account]; 

    }
    
    
    Public List<Account> getAccounts() {
      try {
         List<Account> accountRecords = [Select id, Name,BillingCountry, phone,BillingStreet, AccountNumber,BillingCity, BillingAddress, BillingState, BillingPostalCode, PersonMobilePhone, PersonEmail, PersonHomePhone From Account order by name limit :list_size offset :counter];
           
         return accountRecords;
         
      } catch (QueryException e) {
         ApexPages.addMessages(e);   
         return null;
      }
   }
   
   Public PageReference first() { //user clicked beginning
      counter = 0;
      return null;
   }

   Public PageReference Previous() { //user clicked previous button
      counter -= list_size;
      return null;
   }

   Public PageReference Next() { //user clicked next button
      counter += list_size;
      return null;
   }

   Public PageReference last() { //user clicked end
      counter = total_size - math.mod(total_size, list_size);
      counter = counter - 1;
      return null;
   }

   Public Boolean getDisablePrevious() { 
      //this will disable the previous and beginning buttons
      if (counter>0) return false; else return true;
   }

   Public Boolean getDisableNext() { //this will disable the next and end buttons
      if (counter + list_size < total_size) return false; else return true;
   }  
   
   Public Integer getTotal_size() {
      return total_size;
   }

      
    /*
    Fetch specific account details when clicked on Account name
    */  
    Public void getAccountDetails()                         
    {                 
        accRecord = [Select id, NVMContactWorld__NVM_Phone__c, phone, Name,  BillingCountry, BillingStreet, AccountNumber,BillingCity, BillingAddress, BillingState, BillingPostalCode, PersonMobilePhone, PersonEmail, PersonHomePhone,  (Select id, Name from Contacts), (Select id, CaseNumber, CaseAgeDays__c, Status From cases), (Select id, Name,  Days_Delinquent__c, Total_Past_Due__c From LD_Leases__r), (Select id, Name, System_Size_in_KW__c, Solar_Product__c, Numeric_ID__c from opportunities) From Account Where Id =: accountId];  
    }  
    Public void resetAccs() {
        accRecord = null;
    }
    
    /*
    Filter accounts when different filters are selected
    */
    
    Public void filterAccs()
    {   
       
        List<LD_Lease__c> lease = new List<LD_Lease__c>();
        Set<ID> leaseId = new Set<Id>();
        Set<ID> leaseAccsSet = new Set<Id>();
        accRecord = null;
        try {
            
            //If Both filters are not selected
            
            if(selMan == '-None-' && selAcc == '-None-') {
                allAccounts = [Select id, Name,BillingCountry, BillingStreet, AccountNumber,BillingCity, BillingAddress, BillingState, BillingPostalCode, PersonMobilePhone, PersonEmail, PersonHomePhone,  (Select id, Name from Contacts), (Select id, CaseNumber, CaseAgeDays__c, Status From cases), (Select id, Name,  Days_Delinquent__c, Total_Past_Due__c From LD_Leases__r), (Select id, Name, System_Size_in_KW__c, Solar_Product__c, Numeric_ID__c from opportunities) From Account order by name];
            }
            
            //when Project manager is filtered but account manager is not selected
            
            else if(selMan != '-None-' && selAcc == '-None-'){
                allAccounts = [Select id, Name, BillingCountry, BillingStreet, AccountNumber, BillingCity, BillingAddress, BillingState, BillingPostalCode, PersonMobilePhone, PersonEmail, PersonHomePhone,  (Select id, Name from Contacts), (Select id, CaseNumber, CaseAgeDays__c, Status From cases), (Select id, Name,  Days_Delinquent__c, Total_Past_Due__c From LD_Leases__r), (Select id, Name, project_manager__c, System_Size_in_KW__c, Solar_Product__c, Numeric_ID__c from opportunities) From Account where id in (select AccountId from opportunity where project_manager__r.name =: selMan) order by name];
            }
            
            //when Project manager is not filtered but account manager is selected
            
            else if(selMan == '-None-' && selAcc != '-None-'){
                
                if(selAcc.contains('11-30')) {
                    lease = [Select id,name,Account__c,Am_I_Concierge__c,Days_Delinquent__c From LD_Lease__c where Am_I_Concierge__c = true AND Days_Delinquent__c >= 10 AND Days_Delinquent__c <= 30 order by name];
                }
                else if(selAcc.contains('31-60')) {
                    lease = [Select id,name,Account__c,Am_I_Concierge__c,Days_Delinquent__c From LD_Lease__c where Am_I_Concierge__c = true AND Days_Delinquent__c >= 31 AND Days_Delinquent__c <= 60 order by name];
                }
                else if(selAcc.contains('61-90')) {
                    lease = [Select id,name,Account__c,Am_I_Concierge__c,Days_Delinquent__c From LD_Lease__c where Am_I_Concierge__c = true AND Days_Delinquent__c >= 61 AND Days_Delinquent__c <= 90 order by name];
                }
                else if(selAcc.contains('91-180')) {
                    lease = [Select id,name,Account__c,Am_I_Concierge__c,Days_Delinquent__c From LD_Lease__c where Am_I_Concierge__c = true AND Days_Delinquent__c >= 91 AND Days_Delinquent__c <= 180 order by name];
                }
                else {
                    lease = [Select id,name,Account__c,Am_I_Concierge__c,Days_Delinquent__c From LD_Lease__c where Am_I_Concierge__c = true AND Days_Delinquent__c > 180 order by name];
                }
                
                for(LD_Lease__c LDObj: lease) {
                    leaseId.add(LDObj.id);
                }
                
                lease = [select id, name, Account__c from LD_Lease__c where id in : leaseId];
                
                for(LD_Lease__c LD : lease) {
                    leaseAccsSet.add(LD.Account__c);
                }
                
                allAccounts = [Select id, Name, BillingCountry, BillingStreet, AccountNumber, BillingCity, BillingAddress, BillingState, BillingPostalCode, PersonMobilePhone, PersonEmail, PersonHomePhone,  (Select id, Name from Contacts), (Select id, CaseNumber, CaseAgeDays__c, Status From cases), (Select id, Name,  Days_Delinquent__c, Total_Past_Due__c From LD_Leases__r), (Select id, Name, project_manager__c, System_Size_in_KW__c, Solar_Product__c, Numeric_ID__c from opportunities) From Account where id IN : leaseAccsSet order by name];           
            }
            
            //Both filters are selected
            
            else {
            
                if(selAcc.contains('11-30')) {
                    lease = [Select id,name,Account__c,Am_I_Concierge__c,Days_Delinquent__c From LD_Lease__c where Am_I_Concierge__c = true AND Days_Delinquent__c >= 10 AND Days_Delinquent__c <= 30 order by name];
                }
                else if(selAcc.contains('31-60')) {
                    lease = [Select id,name,Account__c,Am_I_Concierge__c,Days_Delinquent__c From LD_Lease__c where Am_I_Concierge__c = true AND Days_Delinquent__c >= 31 AND Days_Delinquent__c <= 60 order by name];
                }
                else if(selAcc.contains('61-90')) {
                    lease = [Select id,name,Account__c,Am_I_Concierge__c,Days_Delinquent__c From LD_Lease__c where Am_I_Concierge__c = true AND Days_Delinquent__c >= 61 AND Days_Delinquent__c <= 90 order by name];
                }
                else if(selAcc.contains('91-180')) {
                    lease = [Select id,name,Account__c,Am_I_Concierge__c,Days_Delinquent__c From LD_Lease__c where Am_I_Concierge__c = true AND Days_Delinquent__c >= 91 AND Days_Delinquent__c <= 180 order by name];
                }
                else {
                    lease = [Select id,name,Account__c,Am_I_Concierge__c,Days_Delinquent__c From LD_Lease__c where Am_I_Concierge__c = true AND Days_Delinquent__c > 180 order by name];
                }
                for(LD_Lease__c LDObj: lease) {
                    leaseID.add(LDObj.id);
                }
                
                lease = [select id, name, Account__c from LD_Lease__c where id in : leaseId];
                
                for(LD_Lease__c LD : lease) {
                    leaseAccsSet.add(LD.Account__c);
                }
                
                allAccounts = [Select id, Name, BillingCountry, BillingStreet, AccountNumber, BillingCity, BillingAddress, BillingState, BillingPostalCode, PersonMobilePhone, PersonEmail, PersonHomePhone,  (Select id, Name from Contacts), (Select id, CaseNumber, CaseAgeDays__c, Status From cases), (Select id, Name,  Days_Delinquent__c, Total_Past_Due__c From LD_Leases__r), (Select id, Name, project_manager__c, System_Size_in_KW__c, Solar_Product__c, Numeric_ID__c from opportunities) From Account where id IN (select AccountId from opportunity where project_manager__r.name =: selMan) AND id IN : leaseAccsSet order by name];
            }
        }      
        catch(Exception ex) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Something\'s Wrong. Contact Administrator.'));
        }  
    }
}