posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Support Vendors (Accounting, Professional Services, etc)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Id__c</fullName>
        <label>Boxclient Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Secret__c</fullName>
        <label>Boxclient Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxrefresh_token__c</fullName>
        <label>Boxrefresh token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CloseDate__c</fullName>
        <label>CloseDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StageName__c</fullName>
        <label>StageName</label>
        <picklist>
            <picklistValues>
                <fullName>Schedule Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reschedule Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Input Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docusign Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docusign Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduct Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Submitted to DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Rejected by DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Contract Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Layout and Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Rejected by DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Rejected by UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Submitted to DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Submitted to UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Sunrun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Layout Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release to Installer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Not Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Layout Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Cancelled After Install Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed/Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Meta_Data_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Meta Data Assignments</relationshipLabel>
        <relationshipName>Meta_Data_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>File_Id__c</fullName>
        <label>File Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_name__c</fullName>
        <label>File name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meta_Data_Assignment_Column__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meta Data Assignment Column</label>
        <referenceTo>Meta_Data_Assignment_Column__c</referenceTo>
        <relationshipLabel>Meta Data Assignments</relationshipLabel>
        <relationshipName>Meta_Data_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Uploaded_at__c</fullName>
        <label>Uploaded at</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Uploaded_by__c</fullName>
        <label>Uploaded by</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Meta Data Assignment</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meta Data Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Meta_Data_Assignment_Column__c.object
<CustomObject>
    <fields>
        <fullName>Column_Name__c</fullName>
        <label>Column Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Meta Data Assignment Column</label>
    <nameField>
        <displayFormat>COL-{0000}</displayFormat>
        <label>Column number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meta Data Assignment Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Sub_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestMetaDetaAssignmentController.cls
@isTest
public class TestMetaDetaAssignmentController{
    
        static testMethod void unittest() {

                Account acc =new Account();
                acc.name = 'irfan khan';
                insert acc;
                System.assert(acc.id!=null); 
                           
                Deal__c opp = new Deal__c();  
                //opp.name = 'Test opp';
                opp.Account__c = acc.id;
                opp.CloseDate__c = date.today();
                opp.stageName__c = 'Closed won';
                insert opp;
                System.assert(opp.id!=null);            
                
            
            Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Deal__c=opp.id,Name='Funding-Vendor');
            insert sc;
            system.assert(sc.id!=null);
            
            Meta_Data_Assignment_Column__c metaDataColumn = new Meta_Data_Assignment_Column__c(Column_Name__c = 'column1');
            insert metaDataColumn;
            Meta_Data_Assignment_Column__c metaDataColumn1 = new Meta_Data_Assignment_Column__c(Column_Name__c = 'column2');
            insert metaDataColumn1;
            Meta_Data_Assignment_Column__c metaDataColumn2 = new Meta_Data_Assignment_Column__c(Column_Name__c = 'column3');
            insert metaDataColumn2;
            
            Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
            insert testBox;
            System.assert(testBox.id!=null);   
            ApexPages.StandardController controller;
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new TestFolderInfoMock());
            apexpages.currentpage().getparameters().put('id',opp.id);
            MetaDetaAssignmentController metaData = new MetaDetaAssignmentController(controller);

            Test.stopTest();
           }
           
            static testMethod void unittest2() {

                
                Account acc =new Account();
                acc.name = 'irfan khan';
                insert acc;
                System.assert(acc.id!=null); 
                           
                Deal__c opp = new Deal__c();
                //opp.name = 'Test opp';
                opp.Account__c = acc.id;
                opp.CloseDate__c = date.today();
                opp.stageName__c = 'Closed won';
                insert opp;
                System.assert(opp.id!=null);            
                
               
            
            Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Deal__c=opp.id,Name='Funding-Vendor');
            insert sc;
            system.assert(sc.id!=null);
            
            Meta_Data_Assignment_Column__c metaDataColumn = new Meta_Data_Assignment_Column__c(Column_Name__c = 'column1');
            insert metaDataColumn;
            Meta_Data_Assignment_Column__c metaDataColumn1 = new Meta_Data_Assignment_Column__c(Column_Name__c = 'column2');
            insert metaDataColumn1;
            Meta_Data_Assignment_Column__c metaDataColumn2 = new Meta_Data_Assignment_Column__c(Column_Name__c = 'column3');
            insert metaDataColumn2;
                        
            Meta_Data_Assignment__c mdAssign = new Meta_Data_Assignment__c(Check__c=true, File_Id__c ='423432', File_name__c='wuudwd', Meta_Data_Assignment_Column__c=metaDataColumn.id, Deal__c=opp.id, Uploaded_at__c='9/9/15', Uploaded_by__c='irfan khan');
            insert mdAssign;
            Meta_Data_Assignment__c mdAssign1 = new Meta_Data_Assignment__c(Check__c=false, File_Id__c ='42322432', File_name__c='wuudwd', Meta_Data_Assignment_Column__c=metaDataColumn1.id, Deal__c=opp.id, Uploaded_at__c='9/9/15', Uploaded_by__c='irfan khan');
            insert mdAssign1;
            Meta_Data_Assignment__c mdAssign2 = new Meta_Data_Assignment__c(Check__c=true, File_Id__c ='4234332', File_name__c='wuudwd', Meta_Data_Assignment_Column__c=metaDataColumn2.id, Deal__c=opp.id, Uploaded_at__c='9/9/15', Uploaded_by__c='irfan khan');
            insert mdAssign2;
            
            Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
            insert testBox;
            System.assert(testBox.id!=null);   
            ApexPages.StandardController controller;
            //.startTest();
            //Test.setMock(HttpCalloutMock.class, new TestFolderInfoMock());
            apexpages.currentpage().getparameters().put('id',opp.id);
            MetaDetaAssignmentController metaData = new MetaDetaAssignmentController(controller);
            metaData.save();
           //Test.stopTest();
           }
           
                      static testMethod void unittest1() {

                
                Account acc =new Account();
                acc.name = 'irfan khan';
                insert acc;
                System.assert(acc.id!=null); 
                           
                Deal__c opp = new Deal__c();
                //opp.name = 'Test opp';
                opp.Account__c = acc.id;
                opp.CloseDate__c = date.today();
                opp.stageName__c = 'Closed won';
                insert opp;
                System.assert(opp.id!=null);            
                   					
               
            
            Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Deal__c=opp.id,Name='Funding-Vendor');
            insert sc;
            system.assert(sc.id!=null);
            
            Meta_Data_Assignment_Column__c metaDataColumn = new Meta_Data_Assignment_Column__c(Column_Name__c = 'column1');
            insert metaDataColumn;
            Meta_Data_Assignment_Column__c metaDataColumn1 = new Meta_Data_Assignment_Column__c(Column_Name__c = 'column2');
            insert metaDataColumn1;
            Meta_Data_Assignment_Column__c metaDataColumn2 = new Meta_Data_Assignment_Column__c(Column_Name__c = 'column3');
            insert metaDataColumn2;
                        
            Meta_Data_Assignment__c mdAssign = new Meta_Data_Assignment__c(Check__c=true, File_Id__c ='423432', File_name__c='wuudwd', Meta_Data_Assignment_Column__c=metaDataColumn.id, Deal__c=opp.id, Uploaded_at__c='9/9/15', Uploaded_by__c='irfan khan');
            insert mdAssign;
            Meta_Data_Assignment__c mdAssign1 = new Meta_Data_Assignment__c(Check__c=false, File_Id__c ='42322432', File_name__c='wuudwd', Meta_Data_Assignment_Column__c=metaDataColumn1.id, Deal__c=opp.id, Uploaded_at__c='9/9/15', Uploaded_by__c='irfan khan');
            insert mdAssign1;
            Meta_Data_Assignment__c mdAssign2 = new Meta_Data_Assignment__c(Check__c=true, File_Id__c ='4234332', File_name__c='wuudwd', Meta_Data_Assignment_Column__c=metaDataColumn2.id, Deal__c=opp.id, Uploaded_at__c='9/9/15', Uploaded_by__c='irfan khan');
            insert mdAssign2;
            
            Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
            insert testBox;
            System.assert(testBox.id!=null);   
            ApexPages.StandardController controller;
            //.startTest();
            //Test.setMock(HttpCalloutMock.class, new TestFolderInfoMock());
            apexpages.currentpage().getparameters().put('id',opp.id);
            MetaDetaAssignmentController metaData = new MetaDetaAssignmentController(controller);
            metaData.saveColumn();
           //Test.stopTest();
           }
           
            
}