posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Contacting Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Not Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Existing Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Can&apos;t Reach Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Support Vendors (Accounting, Professional Services, etc)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <controllingField>State__c</controllingField>
            <picklistValues>
                <fullName>01CT- PVAssessment Schematics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment Breaker Box photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment Pathfinder Trace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment Powerclerk Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment PV Assessment site photo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment Roof photo’s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment Site Survey form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- Permitting Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Attachment C NYSERDA Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Close out Images</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Conditional Utility Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Field Verification Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Final Utility Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Inspection Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Permits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Posigen QC Checklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Site Safety Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment 3 Line Electric Drawing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Agent Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Attachment B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Pathfinder Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Pre-site Assessment Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Site Photos (NYSERDA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Site Visit/Clipboard Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Utility Interconnect Auth Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03CTNY- Engineering Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03CTNY- PV Assessment Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03CTNY- PV Install Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03CTNY- Design/Engineering Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breaker Box Picture</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <displayFormat>ATT-{000000}</displayFormat>
        <label>Attachment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Id__c</fullName>
        <label>Boxclient Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Secret__c</fullName>
        <label>Boxclient Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxrefresh_token__c</fullName>
        <label>Boxrefresh token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Box_Errors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete - Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Child_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestAttachmentUploaderScheduler.cls
@isTest
public class TestAttachmentUploaderScheduler {
     static testMethod void myTest() {
 
                    Account acc =new Account();
                    acc.name = 'irfan khan';
                    insert acc;
                    System.assert(acc.id!=null); 
                               
                    Opportunity opp = new Opportunity();
                    opp.name = 'Test opp';
                    opp.accountId = acc.id;
                    opp.CloseDate = date.today();
                    opp.stageName = 'Closed won';
                    insert opp;
                    System.assert(opp.id!=null);            
                    
                    Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='sales');
                    insert sc1;
                    system.assert(sc1.id!=null);           
                    
                    dsfs__DocuSign_Status__c  dds = new dsfs__DocuSign_Status__c(dsfs__Company__c=acc.id,dsfs__Opportunity__c=opp.id,dsfs__Subject__c='Application');
                    insert dds;
                    system.assert(dds.id!=null);
                
                    Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Application');
                    insert sc;
                    system.assert(sc.id!=null);
                   
                    Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
                    insert testBox;
                    System.assert(testBox.id!=null);
                   
                   
                    Blob b = Blob.valueOf('Test Data =================');  
                    Attachment attachment = new Attachment();  
                    attachment.ParentId = dds.id;  
                    attachment.Name = 'Test Attachment for Parent';  
                    attachment.Body = b;  
                    upsert attachment;
                    system.assert(attachment.id!=null);
                    
                    box_error__c bxerr = new box_error__c();
                    bxerr.Opportunity__c = opp.id; 
                    bxerr.name = 'Exception '; 
                    bxerr.Message__c = 'Attachment id-'+attachment.id; 
                    bxerr.Body__c = 'Heap Limit Exception';
                    bxerr.Type__c = 'Docusign Doc';
                    bxerr.Status__c = 'Error';
                    insert bxerr;
                    System.assert(bxerr.id!=null);


         AttachmentUploaderScheduler aus= new AttachmentUploaderScheduler();       
         Test.startTest(); 
         Test.setMock(HttpCalloutMock.class, new TestFileUploadMock()); 
         AttachmentUploaderScheduler.runUploadAttachment();   
         AttachmentUploaderScheduler.dummyCode();
         Test.stopTest();
         
             
     }
    static testMethod void myTest1() {
 
                    Account acc =new Account();
                    acc.name = 'irfan khan';
                    insert acc;
                    System.assert(acc.id!=null); 
                               
                    Opportunity opp = new Opportunity();
                    opp.name = 'Test opp';
                    opp.accountId = acc.id;
                    opp.CloseDate = date.today();
                    opp.stageName = 'Closed won';
                    insert opp;
                    System.assert(opp.id!=null);            
                    
                    Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='sales');
                    insert sc1;
                    system.assert(sc1.id!=null);           
                    
                    dsfs__DocuSign_Status__c  dds = new dsfs__DocuSign_Status__c(dsfs__Company__c=acc.id,dsfs__Opportunity__c=opp.id,dsfs__Subject__c='Application');
                    insert dds;
                    system.assert(dds.id!=null);
                
                    Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Application');
                    insert sc;
                    system.assert(sc.id!=null);
                   
                    Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
                    insert testBox;
                    System.assert(testBox.id!=null);
                   
                   
                    Blob b = Blob.valueOf('Test Data =======');  
                    Attachment attachment = new Attachment();  
                    attachment.ParentId = dds.id;  
                    attachment.Name = 'Test Attachment for Parent';  
                    attachment.Body = b;  
                    upsert attachment;
                    system.assert(attachment.id!=null);
                    
                    box_error__c bxerr = new box_error__c();
                    bxerr.Opportunity__c = opp.id; 
                    bxerr.name = 'Exception '; 
                    bxerr.Message__c = 'Attachment id-'+attachment.id; 
                    bxerr.Body__c = 'Heap Limit Exception=';
                    bxerr.Type__c = 'Docusign Doc';
                    bxerr.Status__c = 'Error';
                    insert bxerr;
                    System.assert(bxerr.id!=null);


         AttachmentUploaderScheduler aus= new AttachmentUploaderScheduler();
         Test.startTest();         
         Test.setMock(HttpCalloutMock.class, new TestFileUploadMock1()); 
         AttachmentUploaderScheduler.runUploadAttachment();                      
         Test.stopTest();
         
             
     }
     static testMethod void myTest2() {
 
                    Account acc =new Account();
                    acc.name = 'irfan khan';
                    insert acc;
                    System.assert(acc.id!=null); 
                               
                    Opportunity opp = new Opportunity();
                    opp.name = 'Test opp';
                    opp.accountId = acc.id;
                    opp.CloseDate = date.today();
                    opp.stageName = 'Closed won';
                    insert opp;
                    System.assert(opp.id!=null);            
                    
                    Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='sales');
                    insert sc1;
                    system.assert(sc1.id!=null);           
                
                    Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Application');
                    insert sc;
                    system.assert(sc.id!=null);
                   
                    Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
                    insert testBox;
                    System.assert(testBox.id!=null);
                   
                   
                    Blob b = Blob.valueOf('Test Data =');  
                    Attachment attachment = new Attachment();  
                    attachment.ParentId = opp.id;  
                    attachment.Name = 'Test Attachment for Parent';  
                    attachment.Body = b;  
                    upsert attachment;
                    system.assert(attachment.id!=null);
                    
                    box_error__c bxerr = new box_error__c();
                    bxerr.Opportunity__c = opp.id; 
                    bxerr.name = 'Exception '; 
                    bxerr.Message__c = 'Attachment id-'+attachment.id; 
                    bxerr.Body__c = 'Heap Limit Exception';
                    bxerr.Type__c = 'Docusign Doc';
                    bxerr.Status__c = 'Error';
                    insert bxerr;
                    System.assert(bxerr.id!=null);


         AttachmentUploaderSchedulerStandard  auss = new AttachmentUploaderSchedulerStandard();
         Test.startTest();
         Test.setMock(HttpCalloutMock.class, new TestFileUploadMock());
         String sch1 = '0 1 13 * * ?';
         system.schedule('Test check 1', sch1, auss);                         
         Test.stopTest();        
             
     }
     
       static testMethod void myTest11() {
 
                    Account acc =new Account();
                    acc.name = 'irfan khan';
                    insert acc;
                    System.assert(acc.id!=null); 
                               
                    Opportunity opp = new Opportunity();
                    opp.name = 'Test opp';
                    opp.accountId = acc.id;
                    opp.CloseDate = date.today();
                    opp.stageName = 'Closed won';
                    insert opp;
                    System.assert(opp.id!=null);            
                    
                    Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='sales');
                    insert sc1;
                    system.assert(sc1.id!=null);           
                
                    Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Application');
                    insert sc;
                    system.assert(sc.id!=null);
                   
                    Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
                    insert testBox;
                    System.assert(testBox.id!=null);
                   
                   
                    Blob b = Blob.valueOf('================Test Data');  
                    Attachment attachment = new Attachment();  
                    attachment.ParentId = opp.id;  
                    attachment.Name = 'Test Attachment for Parent';  
                    attachment.Body = b;  
                    upsert attachment;
                    system.assert(attachment.id!=null);
                    
                    box_error__c bxerr = new box_error__c();
                    bxerr.Opportunity__c = opp.id; 
                    bxerr.name = 'Exception '; 
                    bxerr.Message__c = 'Attachment id-'+attachment.id; 
                    bxerr.Body__c = 'Heap Limit Exception';
                    bxerr.Type__c = 'Docusign Doc';
                    bxerr.Status__c = 'Error';
                    insert bxerr;
                    System.assert(bxerr.id!=null);


         AttachmentUploaderSchedulerStandard  auss = new AttachmentUploaderSchedulerStandard();
         Test.startTest();
         Test.setMock(HttpCalloutMock.class, new TestFileUploadMock());
         String sch1 = '0 1 13 * * ?';
         system.schedule('Test check 1', sch1, auss);                         
         Test.stopTest();
         
             
     }
     
    static testMethod void myTest3() {
 
                    Account acc =new Account();
                    acc.name = 'irfan khan';
                    insert acc;
                    System.assert(acc.id!=null); 
                               
                    Opportunity opp = new Opportunity();
                    opp.name = 'Test opp';
                    opp.accountId = acc.id;
                    opp.CloseDate = date.today();
                    opp.stageName = 'Closed won';
                    insert opp;
                    System.assert(opp.id!=null);            
                    
                    Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='sales');
                    insert sc1;
                    system.assert(sc1.id!=null);           

                    Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Application');
                    insert sc;
                    system.assert(sc.id!=null);
                   
                    Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
                    insert testBox;
                    System.assert(testBox.id!=null);
                   
                   
                    Blob b = Blob.valueOf('Test Data =======');  
                    Attachment attachment = new Attachment();  
                    attachment.ParentId = opp.id;  
                    attachment.Name = 'Test Attachment for Parent';  
                    attachment.Body = b;  
                    upsert attachment;
                    system.assert(attachment.id!=null);
                    
                    box_error__c bxerr = new box_error__c();
                    bxerr.Opportunity__c = opp.id; 
                    bxerr.name = 'Exception '; 
                    bxerr.Message__c = 'Attachment id-'+attachment.id; 
                    bxerr.Body__c = 'Heap Limit Exception=';
                    bxerr.Type__c = 'Docusign Doc';
                    bxerr.Status__c = 'Error';
                    insert bxerr;
                    System.assert(bxerr.id!=null);


         AttachmentUploaderSchedulerStandard  auss = new AttachmentUploaderSchedulerStandard();
         Test.startTest();
         Test.setMock(HttpCalloutMock.class, new TestFileUploadMock1());
         String sch = '0 0 23 * * ?';
         system.schedule('Test check 1', sch, auss);              
         Test.stopTest();
         
             
     }
     static testMethod void myTest4() {
 
                    Account acc =new Account();
                    acc.name = 'irfan khan';
                    insert acc;
                    System.assert(acc.id!=null); 
                               
                    Opportunity opp = new Opportunity();
                    opp.name = 'Test opp';
                    opp.accountId = acc.id;
                    opp.CloseDate = date.today();
                    opp.stageName = 'Closed won';
                    insert opp;
                    System.assert(opp.id!=null);            
                    
                    Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='sales');
                    insert sc1;
                    system.assert(sc1.id!=null);           

                    Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Application');
                    insert sc;
                    system.assert(sc.id!=null);
                   
                    Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
                    insert testBox;
                    System.assert(testBox.id!=null);
                   
                   
                    Blob b = Blob.valueOf('===========Test Data =============');  
                    Attachment attachment = new Attachment();  
                    attachment.ParentId = opp.id;  
                    attachment.Name = 'Test Attachment for Parent';  
                    attachment.Body = b;  
                    upsert attachment;
                    system.assert(attachment.id!=null);
                    
                    box_error__c bxerr = new box_error__c();
                    bxerr.Opportunity__c = opp.id; 
                    bxerr.name = 'Exception '; 
                    bxerr.Message__c = 'Attachment id-'+attachment.id; 
                    bxerr.Body__c = 'Heap Limit Exception=';
                    bxerr.Type__c = 'Docusign Doc';
                    bxerr.Status__c = 'Error';
                    insert bxerr;
                    System.assert(bxerr.id!=null);


         AttachmentUploaderSchedulerStandard  auss = new AttachmentUploaderSchedulerStandard();
         AttachmentUploaderSchedulerStandard.dummyCode();
         Test.startTest();
         Test.setMock(HttpCalloutMock.class, new BoxApiControllerRecover_mock_error());
         String sch = '0 0 23 * * ?';
         system.schedule('Test check 1', sch, auss);              
         Test.stopTest();               
     }
     
     
 static testMethod void myTest5() {
 
                    Account acc =new Account();
                    acc.name = 'irfan khan';
                    insert acc;
                    System.assert(acc.id!=null); 
                               
                    Opportunity opp = new Opportunity();
                    opp.name = 'Test opp';
                    opp.accountId = acc.id;
                    opp.CloseDate = date.today();
                    opp.stageName = 'Closed won';
                    insert opp;
                    System.assert(opp.id!=null);            
                    
                    Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Funding-Vendor');
                    insert sc1;
                    system.assert(sc1.id!=null);           
                
                    Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Funding-Vendor');
                    insert sc;
                    system.assert(sc.id!=null);
                   
                    Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
                    insert testBox;
                    System.assert(testBox.id!=null);
                   
                    Project__c project = new Project__c(Opportunity__c=opp.id);
                    insert project;
                    system.assert(project.id!=null);
                    
                    Attachment__c ca= new Attachment__c();
                    ca.Project__c=project.id;
                    insert ca;
                    System.assert(ca.id!=null);

                    Blob b = Blob.valueOf('=============Test Data =======');  
                    Attachment attachment = new Attachment();  
                    attachment.ParentId = ca.id;  
                    attachment.Name = 'Test Attachment for Parent';  
                    attachment.Body = b;  
                    upsert attachment;
                    system.assert(attachment.id!=null);
                    
                    box_error__c bxerr = new box_error__c();
                    bxerr.Opportunity__c = opp.id; 
                    bxerr.name = 'Heap Size Exceed '; 
                    bxerr.Message__c = 'Attachment id-'+attachment.id; 
                    bxerr.Body__c = 'Heap Limit Exception';
                    bxerr.Type__c = 'Custom Doc';
                    bxerr.Status__c = 'Error';
                    insert bxerr;
                    System.assert(bxerr.id!=null);                    
                   

         AttachmentUploaderSchedulerCustom ausc = new AttachmentUploaderSchedulerCustom();
         AttachmentUploaderSchedulerCustom.dummyCode();
         Test.startTest();
         Test.setMock(HttpCalloutMock.class, new TestFileUploadMock());
         AttachmentUploaderSchedulerCustom.runUploadCustom();                          
         Test.stopTest();
         
             
     }  
     
    static testMethod void myTest6() {
 
                    Account acc =new Account();
                    acc.name = 'irfan khan';
                    insert acc;
                    System.assert(acc.id!=null); 
                               
                    Opportunity opp = new Opportunity();
                    opp.name = 'Test opp';
                    opp.accountId = acc.id;
                    opp.CloseDate = date.today();
                    opp.stageName = 'Closed won';
                    insert opp;
                    System.assert(opp.id!=null);            
                    
                    Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Funding-Vendor');
                    insert sc1;
                    system.assert(sc1.id!=null);           

                    Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Funding-Vendor');
                    insert sc;
                    system.assert(sc.id!=null);
                   
                    Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
                    insert testBox;
                    System.assert(testBox.id!=null);
                   
                    Project__c project = new Project__c(Opportunity__c=opp.id);
                    insert project;
                    system.assert(project.id!=null);
                    
                    Attachment__c ca= new Attachment__c();
                    ca.Project__c=project.id;
                    insert ca;
                    System.assert(ca.id!=null);

                    Blob b = Blob.valueOf('===========Test Data =====');  
                    Attachment attachment = new Attachment();  
                    attachment.ParentId = ca.id;  
                    attachment.Name = 'Test Attachment for Parent';  
                    attachment.Body = b;  
                    upsert attachment;
                    system.assert(attachment.id!=null);
                    
                    box_error__c bxerr = new box_error__c();
                    bxerr.Opportunity__c = opp.id; 
                    bxerr.name = 'Heap Size Exceed '; 
                    bxerr.Message__c = 'Attachment id-'+attachment.id; 
                    bxerr.Body__c = 'Heap Limit Exception=';
                    bxerr.Type__c = 'Custom Doc';
                    bxerr.Status__c = 'Error';
                    insert bxerr;
                    System.assert(bxerr.id!=null);


         AttachmentUploaderSchedulerCustom ausc = new AttachmentUploaderSchedulerCustom();
         Test.startTest();
         Test.setMock(HttpCalloutMock.class, new TestFileUploadMock());
         AttachmentUploaderSchedulerCustom.runUploadCustom();                      
         Test.stopTest();         
             
     }
     
       static testMethod void myTest7() {
 
                    Account acc =new Account();
                    acc.name = 'irfan khan';
                    insert acc;
                    System.assert(acc.id!=null); 
                               
                    Opportunity opp = new Opportunity();
                    opp.name = 'Test opp';
                    opp.accountId = acc.id;
                    opp.CloseDate = date.today();
                    opp.stageName = 'Closed won';
                    insert opp;
                    System.assert(opp.id!=null);            
                    
                    Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Funding-Vendor');
                    insert sc1;
                    system.assert(sc1.id!=null);           

                    Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Funding-Vendor');
                    insert sc;
                    system.assert(sc.id!=null);
                   
                    Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
                    insert testBox;
                    System.assert(testBox.id!=null);
                   
                    Project__c project = new Project__c(Opportunity__c=opp.id);
                    insert project;
                    system.assert(project.id!=null);
                    
                    Attachment__c ca= new Attachment__c();
                    ca.Project__c=project.id;
                    insert ca;
                    System.assert(ca.id!=null);

                    Blob b = Blob.valueOf('===========Test Data');  
                    Attachment attachment = new Attachment();  
                    attachment.ParentId = ca.id;  
                    attachment.Name = 'Test Attachment for Parent';  
                    attachment.Body = b;  
                    upsert attachment;
                    system.assert(attachment.id!=null);
                    
                    box_error__c bxerr = new box_error__c();
                    bxerr.Opportunity__c = opp.id; 
                    bxerr.name = 'Heap Size Exceed '; 
                    bxerr.Message__c = 'Attachment id-'+attachment.id; 
                    bxerr.Body__c = 'Heap Limit Exception=';
                    bxerr.Type__c = 'Custom Doc';
                    bxerr.Status__c = 'Error';
                    insert bxerr;
                    System.assert(bxerr.id!=null);


         AttachmentUploaderSchedulerCustom ausc = new AttachmentUploaderSchedulerCustom();
         Test.startTest();
         Test.setMock(HttpCalloutMock.class, new TestFileUploadMock());
         AttachmentUploaderSchedulerCustom.runUploadCustom();                      
         Test.stopTest();         
             
     }
          
     static testMethod void myTest8() {
 
                    Account acc =new Account();
                    acc.name = 'irfan khan';
                    insert acc;
                    System.assert(acc.id!=null); 
                               
                    Opportunity opp = new Opportunity();
                    opp.name = 'Test opp';
                    opp.accountId = acc.id;
                    opp.CloseDate = date.today();
                    opp.stageName = 'Closed won';
                    insert opp;
                    System.assert(opp.id!=null);            
                    
                    Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Funding-Vendor');
                    insert sc1;
                    system.assert(sc1.id!=null);           

                    Sub_Folder__c sc= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='Funding-Vendor');
                    insert sc;
                    system.assert(sc.id!=null);
                   
                    Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
                    insert testBox;
                    System.assert(testBox.id!=null);
                   
                    Project__c project = new Project__c(Opportunity__c=opp.id);
                    insert project;
                    system.assert(project.id!=null);
                    
                    Attachment__c ca= new Attachment__c();
                    ca.Project__c=project.id;
                    insert ca;
                    System.assert(ca.id!=null);

                    Blob b = Blob.valueOf('Test Data  =============');  
                    Attachment attachment = new Attachment();  
                    attachment.ParentId = ca.id;  
                    attachment.Name = 'Test Attachment for Parent';  
                    attachment.Body = b;  
                    upsert attachment;
                    system.assert(attachment.id!=null);
                    
                    box_error__c bxerr = new box_error__c();
                    bxerr.Opportunity__c = opp.id; 
                    bxerr.name = 'Heap Size Exceed '; 
                    bxerr.Message__c = 'Attachment id-'+attachment.id; 
                    bxerr.Body__c = 'Heap Limit Exception==';
                    bxerr.Type__c = 'Custom Doc';
                    bxerr.Status__c = 'Error';
                    insert bxerr;
                    System.assert(bxerr.id!=null);


         AttachmentUploaderSchedulerCustom ausc = new AttachmentUploaderSchedulerCustom();
         Test.startTest();
         Test.setMock(HttpCalloutMock.class, new BoxApiControllerRecover_mock_error());
         AttachmentUploaderSchedulerCustom.runUploadCustom();               
         Test.stopTest();
         
             
     }
}