posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Numeric_ID__c</fullName>
        <externalId>true</externalId>
        <label>Numeric ID</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/LD_Lease__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account the record is related to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LD Leases</relationshipLabel>
        <relationshipName>LD_Leases</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ach_Debit__c</fullName>
        <description>Whether customer is on ACH or not (True or False)</description>
        <inlineHelpText>Whether customer is on ACH or not (True or False)</inlineHelpText>
        <label>Ach_Debit</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_No__c</fullName>
        <description>Contract Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Contract Number</inlineHelpText>
        <label>Contract No</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Customer_No__c</fullName>
        <description>Customer Number</description>
        <inlineHelpText>Customer Number</inlineHelpText>
        <label>Customer No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Day__c</fullName>
        <description>Day on which a payment is due each month.</description>
        <inlineHelpText>Day on which a payment is due each month.</inlineHelpText>
        <label>Due_Day</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_Pay_Due_Dte__c</fullName>
        <description>Date of Next Payment due</description>
        <inlineHelpText>Date of Next Payment due</inlineHelpText>
        <label>Next_Pay_Due_Dte</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The Opportunity this LD Lease is related to.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>LD Leases</relationshipLabel>
        <relationshipName>LD_Leases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Late_Fees__c</fullName>
        <description>Any Late Fees applied to the Contract (Does not include historical late fees assessed prior to conversion)</description>
        <inlineHelpText>Any Late Fees applied to the Contract (Does not include historical late fees assessed prior to conversion)</inlineHelpText>
        <label>Total_Late_Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Paid_Lr__c</fullName>
        <description>Total lease rental payments received, LTD (does not include sales tax or EE)</description>
        <inlineHelpText>Total lease rental payments received, LTD (does not include sales tax or EE)</inlineHelpText>
        <label>Total_Paid_Lr</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LD Lease</label>
    <nameField>
        <label>LD Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LD Leases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Numeric_ID__c</fullName>
        <externalId>true</externalId>
        <label>Numeric ID</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Trigger_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>LD_Lease_trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>LD Lease trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Setting</label>
</CustomObject>

posiGen_FullsendBox/src/classes/TestLDLeaseTrigger.cls
@isTest
public with sharing class TestLDLeaseTrigger{
  public static testMethod void myUnitTest1(){
  
      Account acc =new Account();
      acc.name = 'irfan khan';
      insert acc;
      
      Opportunity opp = new Opportunity();
      opp.name = 'Test opp';
      opp.accountId = acc.id;
      opp.CloseDate = date.today();
      opp.stageName = 'Closed Won';
      insert opp;
      
      System.assertEquals(null, opp.Numeric_id__c);
      
      Trigger_Setting__c ts = new Trigger_Setting__c(LD_Lease_trigger__c=true);
      insert ts; 

      List<LD_Lease__c> ldLeaseList = new List<LD_Lease__c>();
      ldLeaseList.add(new LD_Lease__c(Contract_No__c='12346744',Name='aaaa',opportunity__c=opp.id,account__c=acc.id,Customer_No__c='22'+opp.Numeric_id__c,Next_Pay_Due_Dte__c=System.today(),Total_Late_Fees__c=500.00,Due_Day__c=5,Ach_Debit__c='452134545',Total_Paid_Lr__c=1000.00));
      ldLeaseList.add(new LD_Lease__c(Contract_No__c='12346733',Name='bbbb',opportunity__c=opp.id,account__c=acc.id,Customer_No__c='44'+opp.Numeric_id__c,Next_Pay_Due_Dte__c=System.today(),Total_Late_Fees__c=400.00,Due_Day__c=4,Ach_Debit__c='4aa2134545',Total_Paid_Lr__c=500.00));
      ldLeaseList.add(new LD_Lease__c(Contract_No__c='12346722',Name='cccc',opportunity__c=opp.id,account__c=acc.id,Customer_No__c='55'+opp.Numeric_id__c,Next_Pay_Due_Dte__c=System.today(),Total_Late_Fees__c=600.00,Due_Day__c=3,Ach_Debit__c='452341545',Total_Paid_Lr__c=7000.00));
      ldLeaseList.add(new LD_Lease__c(Contract_No__c='12346711',Name='dddd',opportunity__c=opp.id,account__c=acc.id,Customer_No__c='66'+opp.Numeric_id__c,Next_Pay_Due_Dte__c=System.today(),Total_Late_Fees__c=700.00,Due_Day__c=1,Ach_Debit__c='4523sss545',Total_Paid_Lr__c=8000.00));
      
      upsert ldLeaseList;
  }
}