posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>State</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts In This State</relationshipLabel>
        <relationshipName>Accounts_In_This_State</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Utility</fullName>
        <active>true</active>
        <description>Utility Company</description>
        <label>Utility</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Installation_Step__c.object
<CustomObject>
    <fields>
        <fullName>Business_Stage__c</fullName>
        <label>Business Stage</label>
        <referenceTo>Business_Stage__c</referenceTo>
        <relationshipLabel>Business Installation Steps</relationshipLabel>
        <relationshipName>Business_Installation_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Display_In_Tracker__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Display In Tracker</label>
        <type>Checkbox</type>
    </fields>
    <label>Business Installation Step</label>
    <nameField>
        <label>Business Installation Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Installation Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Market__c.object
<CustomObject>
    <label>Business Market</label>
    <nameField>
        <label>Business Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Business_Market__c</fullName>
        <label>Business Market</label>
        <referenceTo>Business_Market__c</referenceTo>
        <relationshipLabel>Business Stages</relationshipLabel>
        <relationshipName>Business_Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Display_In_Tracker__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Display In Tracker</label>
        <type>Checkbox</type>
    </fields>
    <label>Business Stage</label>
    <nameField>
        <label>Business Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Status__c.object
<CustomObject>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Business Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>equals</operation>
                <value>Project Manager</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_User_Project_Manager_For</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Property__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities At This Property</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Steps__c.object
<CustomObject>
    <fields>
        <fullName>Aging__c</fullName>
        <label>Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Installation_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Installation Step</label>
        <referenceTo>Business_Installation_Step__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Status</label>
        <referenceTo>Business_Status__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Process_Aging_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Process Aging Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>In_Process_Aging__c</fullName>
        <label>In Process Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_Process_End_Date__c</fullName>
        <label>In Process End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Process_Start_Date__c</fullName>
        <label>In Process Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NA_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Review_Aging_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PM Review Aging Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Review_Aging__c</fullName>
        <label>PM Review Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PM_Review_End_Date__c</fullName>
        <label>PM Review End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PM_Review_Start_Date__c</fullName>
        <label>PM Review Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PM_Tool_V2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PM Tool V2</label>
        <referenceTo>PM_Tool_V2__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>PM Step</label>
    <nameField>
        <displayFormat>Step-{000000}</displayFormat>
        <label>PM Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Tool_V2__c.object
<CustomObject>
    <fields>
        <fullName>Completion_Average__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Completion Average</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <label>Lease Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PM Tools V2</relationshipLabel>
        <relationshipName>PM_Tools_V2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <formula>Opportunity__r.Project_Manager__r.FirstName+&apos; &apos;+Opportunity__r.Project_Manager__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Opportunity__r.Property_State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <label>PM Tool V2</label>
    <nameField>
        <label>PM Tool V2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Tools V2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestPMToolV2Controller.cls
@isTest
public with sharing class TestPMToolV2Controller {
    public static testMethod void unitTest1() {
        List<Business_Installation_Step__c> bisFilterList = new List<Business_Installation_Step__c>();
        
        Business_Status__c bStatus1 = new  Business_Status__c(name='Not Applicable',score__c=-1);
        insert bStatus1;
        Business_Status__c bStatus2 = new  Business_Status__c(name='Not Started',score__c=0);
        insert bStatus2;
        Business_Status__c bStatus3 = new  Business_Status__c(name='PM Review',score__c=1);
        insert bStatus3;
        Business_Status__c bStatus4 = new  Business_Status__c(name='In Process',score__c=2);
        insert bStatus4;
        Business_Status__c bStatus5 = new  Business_Status__c(name='Complete',score__c=3);
        insert bStatus5;
        Business_Status__c bStatus6 = new  Business_Status__c(name='Confirmed Completed',score__c=4);
        insert bStatus6;
        
        Business_Market__c bm = new Business_Market__c(name='CT');
        insert bm;
        
        String recordTypeId1  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account pAcc= new Account(
        RecordTypeID=recordTypeId1 ,
        FirstName='Test FName',
        LastName='Test LName',
        PersonMailingStreet='test@yahoo.com',
        PersonMailingPostalCode='12345',
        PersonMailingCity='SFO',
        PersonEmail='test@yahoo.com',
        PersonHomePhone='1234567',
        PersonMobilePhone='12345678' 
        );
        insert pAcc;
        
        Property__c prop = new Property__c();
        prop.State__c = 'CT';
        prop.Account__c = pAcc.id;
        prop.Address_Line_1__c = 'Address1 Test';
        insert prop;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
   
        User u = new User(); 
        u.Username =  'Hello'+ '@testPMToolV2' + '.org'; 
        u.ProfileId = p.Id; 
        u.LastName = 'test'; 
        u.Alias = 'test1'; 
        u.Email =  'name'+ '@test' + '.org'; 
        u.TimeZoneSidKey = 'America/Los_Angeles'; 
        u.localesidkey='en_US'; 
        u.emailencodingkey='UTF-8';
        u.languagelocalekey='en_US'; 
        insert u;
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test1';
        opp.Project_Manager__c = u.id;
        opp.Property__c = prop.id;
        opp.StageName = 'Layout Approval';
        opp.CloseDate = system.today();
        opp.Accountid = pAcc.id;
        insert opp;
        
        PM_Tool_V2__c pm = new PM_Tool_V2__c();
        pm.Opportunity__c = opp.id;
        pm.Project_Status__c = 'Active';
        pm.Completion_Average__c = 0.0;
        pm.Lease_Type__c = '';
        insert pm;
        
        Business_Stage__c bs = new Business_Stage__c(Name='Feasibility', Business_Market__c = bm.id, Display_In_Tracker__c=true);
        insert bs;
        
        for(Integer i = 0; i < 5; i++) {
            Business_Installation_Step__c bis = new Business_Installation_Step__c();
            bis.name = 'Test '+i;
            bis.Business_Stage__c = bs.id;
            bisFilterList.add(bis);         
        }
        insert bisFilterList;
        
        PM_Steps__c pms = new PM_Steps__c();
        pms.Aging__c = 1;
        pms.Business_Installation_Step__c = new Business_Installation_Step__c(name='test1',Business_Stage__c=bs.id).id;
        pms.End_Date__c = null; 
        pms.In_Process_Aging__c = 2; 
        pms.In_Process_Aging_Exception__c = false; 
        pms.In_Process_End_Date__c = null; 
        pms.In_Process_Start_Date__c = null; 
        pms.NA_Override__c = false; 
        pms.PM_Review_Aging__c = 3; 
        pms.PM_Review_Aging_Exception__c = true; 
        pms.PM_Review_End_Date__c = null; 
        pms.PM_Review_Start_Date__c = null;
        pms.PM_Tool_V2__c = pm.id; 
        pms.Start_Date__c = null;
        insert pms;
        List<PM_Steps__c> pmStepsList = new List<PM_Steps__c>();
        pmStepsList.add(pms);
        
        PMToolV2Controller pmtool = new PMToolV2Controller();
        pmtool.filterConditions = ' <span id="dtext_0">(Intro Call = Not Started)</span><span id="dtext_1"> and (Final Utility Approval/PTO/NM = In Process)</span> ';
        pmtool.filterText = '{\"data\":[{\"id\":0,\"step\":\"Intro Call\",\"status\":\"Not Started\"},{\"id\":1,\"step\":\"Quality Control\",\"status\":\"Completed\"}]}';
        pmtool.selectedMarket = bm.id;
        pmtool.loaddata();
        pmtool.getBusinessMarkets();
        pmtool.populateProjectManagersList('CT');
        pmtool.populateFilterList(bisFilterList);
        pmtool.getEvalConditions();
        
        ApexPages.currentPage().getParameters().put('customerId', pm.id);
        pmtool.viewCustomerDetail();
        
        pmtool.loaddata();
    }
    
    public static testMethod void unitTest2() {
        PMToolV2Controller pmtool = new PMToolV2Controller();
        pmtool.filterConditions = '';
        pmtool.filterText = '';
        pmtool.loaddata();
        pmtool.getBusinessMarkets();
        pmtool.populateProjectManagersList('');
        pmtool.populateFilterList(null);
        pmtool.getEvalConditions();
        
        ApexPages.currentPage().getParameters().put('customerId', '#');
        pmtool.viewCustomerDetail();
        pmtool.loaddata();
    }
    
    public static testMethod void unitTest3() {
        List<Business_Installation_Step__c> bisFilterList = new List<Business_Installation_Step__c>();
        
        Business_Status__c bStatus1 = new  Business_Status__c(name='Not Applicable',score__c=-1);
        insert bStatus1;
        Business_Status__c bStatus2 = new  Business_Status__c(name='Not Started',score__c=0);
        insert bStatus2;
        Business_Status__c bStatus3 = new  Business_Status__c(name='PM Review',score__c=1);
        insert bStatus3;
        Business_Status__c bStatus4 = new  Business_Status__c(name='In Process',score__c=2);
        insert bStatus4;
        Business_Status__c bStatus5 = new  Business_Status__c(name='Complete',score__c=3);
        insert bStatus5;
        Business_Status__c bStatus6 = new  Business_Status__c(name='Confirmed Completed',score__c=4);
        insert bStatus6;
        
        Business_Market__c bm = new Business_Market__c(name='NY');
        insert bm;
        
        String recordTypeId1  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account pAcc= new Account(
        RecordTypeID=recordTypeId1 ,
        FirstName='Test FName',
        LastName='Test LName',
        PersonMailingStreet='test@yahoo.com',
        PersonMailingPostalCode='12345',
        PersonMailingCity='SFO',
        PersonEmail='test@yahoo.com',
        PersonHomePhone='1234567',
        PersonMobilePhone='12345678' 
        );
        insert pAcc;
        
        Property__c prop = new Property__c();
        prop.State__c = 'NY';
        prop.Account__c = pAcc.id;
        prop.Address_Line_1__c = 'Address1 Test';
        insert prop;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
   
        User u = new User(); 
        u.Username =  'Hello'+ '@testPMToolV2' + '.org'; 
        u.ProfileId = p.Id; 
        u.LastName = 'test'; 
        u.Alias = 'test1'; 
        u.Email =  'name'+ '@test' + '.org'; 
        u.TimeZoneSidKey = 'America/Los_Angeles'; 
        u.localesidkey='en_US'; 
        u.emailencodingkey='UTF-8';
        u.languagelocalekey='en_US'; 
        insert u;
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test1';
        opp.Project_Manager__c = u.id;
        opp.Property__c = prop.id;
        opp.StageName = 'Layout Approval';
        opp.CloseDate = system.today();
        opp.Accountid = pAcc.id;
        insert opp;
        
        PM_Tool_V2__c pm = new PM_Tool_V2__c();
        pm.Opportunity__c = opp.id;
        pm.Project_Status__c = 'Active';
        insert pm;
        
        Business_Stage__c bs = new Business_Stage__c(Name='Feasibility', Business_Market__c = bm.id);
        insert bs;
        
        for(Integer i = 0; i < 5; i++) {
            Business_Installation_Step__c bis = new Business_Installation_Step__c();
            bis.name = 'Test '+i;
            bis.Business_Stage__c = bs.id;
            bisFilterList.add(bis);         
        }
        insert bisFilterList;
        
        pm.Completion_Average__c = 0.0;
        pm.Lease_Type__c = ''; 
        update pm;
        
        PM_Steps__c pms = new PM_Steps__c();
        pms.Aging__c = 1;
        pms.Business_Installation_Step__c = new Business_Installation_Step__c(name='test1',Business_Stage__c=bs.id).id;
        pms.End_Date__c = null; 
        pms.In_Process_Aging__c = 2; 
        pms.In_Process_Aging_Exception__c = false; 
        pms.In_Process_End_Date__c = null; 
        pms.In_Process_Start_Date__c = null; 
        pms.NA_Override__c = false; 
        pms.PM_Review_Aging__c = 3; 
        pms.PM_Review_Aging_Exception__c = true; 
        pms.PM_Review_End_Date__c = null; 
        pms.PM_Review_Start_Date__c = null;
        pms.PM_Tool_V2__c = pm.id; 
        pms.Start_Date__c = null;
        insert pms;
        
        PMToolV2Controller pmtool = new PMToolV2Controller();
        pmtool.selectedProjectManager = 'Dev';
        pmtool.stateChanged = false;
        pmtool.selectedMarket = 'NY';
        pmtool.filterConditions = '';
        pmtool.loaddata();
        pmtool.getBusinessMarkets();
        pmtool.populateProjectManagersList('');
        pmtool.populateFilterList(bisFilterList);
        pmtool.getEvalConditions();
        
        ApexPages.currentPage().getParameters().put('customerId', pm.id);
        pmtool.viewCustomerDetail();
        pmtool.loaddata();
    }
    
    public static testMethod void unitTest4() {
        List<Business_Installation_Step__c> bisFilterList = new List<Business_Installation_Step__c>();
        
        Business_Status__c bStatus1 = new  Business_Status__c(name='Not Applicable',score__c=-1);
        insert bStatus1;
        Business_Status__c bStatus2 = new  Business_Status__c(name='Not Started',score__c=0);
        insert bStatus2;
        Business_Status__c bStatus3 = new  Business_Status__c(name='PM Review',score__c=1);
        insert bStatus3;
        Business_Status__c bStatus4 = new  Business_Status__c(name='In Process',score__c=2);
        insert bStatus4;
        Business_Status__c bStatus5 = new  Business_Status__c(name='Complete',score__c=3);
        insert bStatus5;
        Business_Status__c bStatus6 = new  Business_Status__c(name='Confirmed Completed',score__c=4);
        insert bStatus6;
        
        Business_Market__c bm = new Business_Market__c(name='LA');
        insert bm;
        
        String recordTypeId1  = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account pAcc= new Account(
        RecordTypeID=recordTypeId1 ,
        FirstName='Test FName',
        LastName='Test LName',
        PersonMailingStreet='test@yahoo.com',
        PersonMailingPostalCode='12345',
        PersonMailingCity='SFO',
        PersonEmail='test@yahoo.com',
        PersonHomePhone='1234567',
        PersonMobilePhone='12345678' 
        );
        insert pAcc;
        
        Property__c prop = new Property__c();
        prop.State__c = 'LA';
        prop.Account__c = pAcc.id;
        prop.Address_Line_1__c = 'Address1 Test';
        insert prop;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
   
        User u = new User(); 
        u.Username =  'Hello'+ '@testPMToolV2' + '.org'; 
        u.ProfileId = p.Id; 
        u.LastName = 'test'; 
        u.Alias = 'test1'; 
        u.Email =  'name'+ '@test' + '.org'; 
        u.TimeZoneSidKey = 'America/Los_Angeles'; 
        u.localesidkey='en_US'; 
        u.emailencodingkey='UTF-8';
        u.languagelocalekey='en_US'; 
        insert u;
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test1';
        opp.Project_Manager__c = u.id;
        opp.Property__c = prop.id;
        opp.StageName = 'Layout Approval';
        opp.CloseDate = system.today();
        opp.Accountid = pAcc.id;
        insert opp;
        
        PM_Tool_V2__c pm = new PM_Tool_V2__c();
        pm.Opportunity__c = opp.id;
        pm.Project_Status__c = 'Active';
        insert pm;
        
        Business_Stage__c bs = new Business_Stage__c(Name='Feasibility', Business_Market__c = bm.id);
        insert bs;
        
        for(Integer i = 0; i < 5; i++) {
            Business_Installation_Step__c bis = new Business_Installation_Step__c();
            bis.name = 'Test '+i;
            bis.Business_Stage__c = bs.id;
            bisFilterList.add(bis);         
        }
        insert bisFilterList;
        
        pm.Completion_Average__c = 0.0;
        pm.Lease_Type__c = ''; 
        update pm;
        
        PM_Steps__c pms = new PM_Steps__c();
        pms.Aging__c = 1;
        pms.Business_Installation_Step__c = new Business_Installation_Step__c(name='test1',Business_Stage__c=bs.id).id;
        pms.End_Date__c = null; 
        pms.In_Process_Aging__c = 2; 
        pms.In_Process_Aging_Exception__c = false; 
        pms.In_Process_End_Date__c = null; 
        pms.In_Process_Start_Date__c = null; 
        pms.NA_Override__c = false; 
        pms.PM_Review_Aging__c = 3; 
        pms.PM_Review_Aging_Exception__c = true; 
        pms.PM_Review_End_Date__c = null; 
        pms.PM_Review_Start_Date__c = null;
        pms.PM_Tool_V2__c = pm.id; 
        pms.Start_Date__c = null;
        insert pms;
        
        PMToolV2Controller pmtool = new PMToolV2Controller();
        pmtool.selectedMarket = '';
        pmtool.selectedProjectManager = null;
        pmtool.stateChanged = true;
        pmtool.loaddata();
        
        pmtool.filterConditions = '';
        pmtool.getBusinessMarkets();
        pmtool.populateProjectManagersList('LA');
        pmtool.populateFilterList(bisFilterList);
        pmtool.getEvalConditions();
        
        ApexPages.currentPage().getParameters().put('customerId', pm.id);
        pmtool.viewCustomerDetail();
        pmtool.loaddata();
    }
}