posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Referring_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referring Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customers Referred</relationshipLabel>
        <relationshipName>Accounts_Referred</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Municipality</fullName>
        <active>true</active>
        <description>The government which has domain over the resident. (i.e. the entity that issues Permits)</description>
        <label>Municipality</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Allows_for_Multiple_Members__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allows for Multiple Members</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount_Paid_Out_For_Each_Referee__c</fullName>
        <label>Amount Paid Out For Each Referee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_for_Single_Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity for Single Referral</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Single Referral Opps</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referrals I Have Referred</relationshipLabel>
        <relationshipName>Referral</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Referral</fullName>
        <active>true</active>
        <description>one of these for any given ‘event’ to tie it to the Campaign and track earned vs paid</description>
        <label>Referral</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Intacct_Entity__c.object
<CustomObject>
    <label>Intacct Entity</label>
    <nameField>
        <label>Intacct Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intacct Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Municipality__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Which Municipality is this property in?</inlineHelpText>
        <label>Municipality</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Municipality</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads In This Municipality</relationshipLabel>
        <relationshipName>Leads_In_This_Municipality</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Type__c</fullName>
        <inlineHelpText>Was this a single referral or was the person referred at a party / group event</inlineHelpText>
        <label>Referral Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HistoricData</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.RecordTypeId</field>
                <operation>equals</operation>
                <value>Referral</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <formula>Referral__r.Referrer__r.FirstName  &amp; &quot; &quot; &amp;  Referral__r.Referrer__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Referrer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referring_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referring Customer/Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads Referred</relationshipLabel>
        <relationshipName>Leads_Referred</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Municipality__c.object
<CustomObject>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Are_black_panels_required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Are black panels required?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Intacct_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intacct Entity</label>
        <referenceTo>Intacct_Entity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Type__c</fullName>
        <label>Referral Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Party</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Campaign.RecordTypeId</field>
                <operation>equals</operation>
                <value>Referral</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities (Referral)</relationshipLabel>
        <relationshipName>Referral_Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Opportunities</relationshipLabel>
        <relationshipName>Referrer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referring_Customer__c</fullName>
        <formula>Account.Referring_Customer__r.Name</formula>
        <label>Referring Customer</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/Test_ReferralManagementApp.cls
@isTest (SeeAllData=true)
public class Test_ReferralManagementApp {
    
static testMethod void testReferralInsertion()
    {
        final Date closeDate = date.newInstance(2014, 8, 11);
        
        
        User u1 = [SELECT Id FROM User WHERE Alias='susco'];
        
        System.runAs(u1) {
            
            test.startTest();
            Intacct_Entity__c testIntacctEntity = new Intacct_Entity__c(Name = 'PG of LA');
            insert testIntacctEntity;
            
            Intacct_Entity__c testIntacctEntity2 = new Intacct_Entity__c(Name = 'PG of CT');
            insert testIntacctEntity2;
            
            Intacct_Entity__c testIntacctEntity3 = new Intacct_Entity__c(Name = 'PG of NY');
            insert testIntacctEntity3; 
            
            RecordType referralProgramCampaign = [SELECT Id FROM RecordType WHERE Name = 'Referral Programs' AND sObjectType = 'Campaign' LIMIT 1];
            
            Campaign referralCampaign = new Campaign (Name = 'Test Referral Campaign', IsActive = TRUE, Type = 'Referral Campaign', Amount_Paid_Out_For_Each_Referee__c = 100, StartDate = closeDate
                                                     , RecordTypeId = referralProgramCampaign.Id, Allows_For_Multiple_Members__c = FALSE);
            insert referralCampaign;
            
            Opportunity testOpp = [SELECT Id, Name, Referrer__c, LeadSource, Referral_Type__c FROM Opportunity WHERE Name = 'Brock Lee- 12345 Main St.'];
            Account testReferrer = [SELECT Id, FirstName, LastName FROM Account WHERE LastName = 'Jones' LIMIT 1];
            Account testReferrer2 = [SELECT Id, FirstName, LastName FROM Account WHERE LastName = 'Smith' LIMIT 1];
            
            
            
            testOpp.Referrer__c = testReferrer.Id;
            testOpp.LeadSource = 'Referral';
            testOpp.Referral_Type__c = 'Single';
            update testOpp;
            
            
            
            testOpp = [SELECT Id, Referral__c, Referrer__c FROM Opportunity WHERE Id = : testOpp.Id ];
            Test.stopTest();
            
            //Campaign referral = [SELECT Id, HierarchyNumberOfContacts FROM Campaign WHERE Opportunity_For_Single_Referral__c = : testOpp.Id];
            
            System.assert(testOpp.Referral__c != null,  testOpp.Referrer__c);
            //System.assertEquals(1, referral.HierarchyNumberOfContacts);
            /*
            Campaign referral = [SELECT Id, Referrer__c FROM Campaign WHERE Opportunity_For_Single_Referral__c = : testOpp.Id];
            referral.Referrer__c = testReferrer2.Id;
            update referral;
            
            referral = [SELECT Id, Referrer__c FROM Campaign WHERE Id = : referral.Id];
            System.assertEquals(testReferrer2.Id, referral.Referrer__c);*/
 			/*
            RecordType referralAccount = [SELECT Id FROM RecordType WHERE Name = 'Referral Account' AND sObjectType = 'Account' LIMIT 1];
            RecordType referralProgramCampaign = [SELECT Id FROM RecordType WHERE Name = 'Referral Programs' AND sObjectType = 'Campaign' LIMIT 1];
            RecordType personAccount = [SELECT Id FROM RecordType WHERE Name = 'Person Account' AND sObjectType = 'Account' LIMIT 1];
            
            Account municipality = [SELECT Id FROM Account WHERE Name = 'Orleans Parish, LA'];
            Account testReferrer = new Account (LastName = 'Referrer', FirstName = 'Jeff');
            insert testReferrer;
            
            Campaign referralCampaign = new Campaign (Name = 'Test Referral Campaign', IsActive = TRUE, Type = 'Referral Campaign', Amount_Paid_Out_For_Each_Referee__c = 100, StartDate = closeDate
                                                      , RecordTypeId = referralProgramCampaign.Id, Allows_For_Multiple_Members__c = FALSE);
            insert referralCampaign;
            
            Lead testLead = new Lead();
            testLead.FirstName = 'Mike';
            testLead.LastName = 'The Referred';
            testLead.Municipality__c = municipality.id;
            testLead.Status = 'Open';
            testLead.Phone = '(504)555-1234';
            testLead.LeadSource = 'Referral';
            testLead.Referral_Type__c = 'Single';
            testLead.Referring_Customer__c = testReferrer.Id;
            insert testLead;
            
            Database.LeadConvert lc = new Database.LeadConvert();
            lc.setLeadId(testLead.Id);
                    
            LeadStatus convertStatus = [Select Id, MasterLabel FROM LeadStatus WHERE MasterLabel = 'Qualified' LIMIT 1];
        	lc.setConvertedStatus(convertStatus.MasterLabel);
            
            Database.LeadConvertResult lcr = Database.convertLead(lc);
            
            

            
           // Account testAccount = [new Account (LastName = 'The Referred', FirstName = 'Mike', RecordTypeId = personAccount.Id)];
            //insert testAccount;
            //System.debug(testAccount);
            

            
            //Opportunity testOpp = new Opportunity (Name = 'Test Opp at Blank Location', Account = testAccount, Referrer__c = testReferrer.Id, LeadSource = 'Referral', Referral_Type__c = 'Single'
            //                                       , StageName = 'Schedule Appointment', CloseDate = closeDate);
            //insert testOpp;
            
            //testOpp.Are_black_panels_required__c = TRUE;
            //update testOpp;
            
            Opportunity testOpp = [SELECT Id, Referral__c FROM Opportunity WHERE Name = : lc.OpportunityName ];
            
            Campaign referral = [SELECT Id FROM Campaign WHERE Opportunity_For_Single_Referral__c = : testOpp.Id];
            
            System.assert(testOpp.Referral__c != null);
            System.assertEquals(1, referral.HierarchyNumberOfContacts);
*/
        }
    }
}