posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Contacting Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Not Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Existing Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Can&apos;t Reach Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Support Vendors (Accounting, Professional Services, etc)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Id__c</fullName>
        <label>Boxclient Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Secret__c</fullName>
        <label>Boxclient Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxrefresh_token__c</fullName>
        <label>Boxrefresh token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Box_Errors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserEmail__c</fullName>
        <label>UserEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Pipeline_Stage__c</fullName>
        <formula>IF( AND(Permanent_Removal__c, NOT(ISNULL(R_P_Removal_Date__c))), &quot;Removed &amp; Terminated&quot;,
IF( Num_of_LD_Leases__c &gt; 0
	, &quot;Boarded&quot;,
    IF(TEXT( StageName ) = &quot;Closed Won&quot;,
		IF( OR( Lease_Boarding_Status__c = &quot;Upload to LD (based on CAO File)&quot;,Lease_Boarding_Status__c = &quot;Boarded&quot;, Has_Been_Boarded__c )
			, &quot;Boarded&quot;
			, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c)) &amp;&amp; NOT(ISNULL(EU_Completed_Date__c))
				, &quot;Need to Board&quot;
				, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Solar Panels&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Uptown Solar Lease&quot;)) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c))
					, &quot;Need to Board&quot;
					, IF( AND( NOT(ISNULL(PVI_Net_Meter_Install_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
						, &quot;Need to Board&quot;
						, IF(  AND(  NOT(ISNULL(PVI_Placed_In_Service_Date__c)), ISNULL(EU_Completed_Date__c), Has_EE_as_a_Solar_Product__c )
							, &quot;Pending EU&quot;
							, IF( AND( NOT(ISNULL(PVI_Placed_In_Service_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
								, &quot;Pending Net Meter&quot;
								, IF ( AND(ISNULL(PVI_Placed_In_Service_Date__c ), NOT(ISNULL(PVI_Rails_and_Panels_Left_WH_Date__c)))
									, &quot;PV System Left Warehouse&quot; 
									, TEXT( StageName )
								)
							)
						)
					)
				)
			)
        )
        ,TEXT( StageName )
	)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity_Collaboration_Recovery__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Opportunity Collaboration Recovery</relationshipLabel>
        <relationshipName>Opportunity_Collaboration_Recovery</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserEmail__c</fullName>
        <label>UserEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Collaboration Recovery</label>
    <nameField>
        <label>Opportunity Collaboration Recovery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Collaboration Recovery</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Child_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestOpportunityCollaborationRecovery.cls
@isTest
public class TestOpportunityCollaborationRecovery{ 

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        List<Sub_folder__c> subList = new List<Sub_folder__c>();
        Map<String,String> profileMap = new Map<String,String>(); 
        Account acc =new Account();
        acc.name = 'irfan khan';
        upsert acc;
        
      
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Closed Won';
        upsert opp;
        
        opportunity op =[Select id, Pipeline_stage__c from opportunity where stageName='Closed Won' and id=:opp.id];
        
        
      //  System.assert(false,[select id,stageName From opportunity where id=:opp.id]);             
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        upsert testBox;
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Funding-Vendor';
        sf.cf_opportunity__c = op.id;
        sf.cf_box_folder_id__c = '11446498';
        upsert sf;
       
        Sub_folder__c sflst =[Select id,cf_box_folder_id__c,cf_opportunity__c,name, cf_opportunity__r.Pipeline_stage__c from Sub_folder__c where id=:sf.id];
        
        subList.add(sflst);
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
       
        Profile prf= [select id,Name From Profile Where Name='EE Partner User'];
        profileMap.put(prf.Name,prf.id);
        
        
        List<Box_error__c> OppList = new List<Box_error__c>();
        box_error__c bxerr = new box_error__c();
        bxerr.Opportunity__c = opp.id; 
        bxerr.name = '409'; 
        bxerr.Message__c = 'Attachment id-'; 
        bxerr.Body__c = '{"type":"error","status":409,"code":"item_name_in_use","context_info":{"conflicts":{"type":"folder","id":"5045260509","sequence_id":"0","etag":"0","name":"2796_9019apricotst_JamesTobias"}},"help_url":"http:developers.box.com","message":"Item with the same name already exists","request_id":"1145339348561cbaa279ec4"}';
        bxerr.Type__c = 'EE';
        bxerr.Status__c = 'Error';  
        OppList.add(bxerr); 
       
        List<Opportunity_Collaboration_Recovery__c> lstclb = new List<Opportunity_Collaboration_Recovery__c>();
        Opportunity_Collaboration_Recovery__c clb = new Opportunity_Collaboration_Recovery__c(BoxCollaboration_Id__c='123456',Sub_Folder__c =sf.id,UserEmail__c='anki@abc.com',Profile_Id__c=prf.id);
        upsert clb;
        lstclb.add(clb);
        
        Batch_OpportunityCollaborationRecovery bcb = new Batch_OpportunityCollaborationRecovery('EE');
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestFolderInfoMock());
        bcb.execute(BC,subList);
        Test.stopTest();         
    }
  static testMethod void myUnitTest2() {
        // TO DO: implement unit test
        List<Sub_folder__c> subList = new List<Sub_folder__c>();
        Map<String,String> profileMap = new Map<String,String>(); 
        Account acc =new Account();
        acc.name = 'irfan khan';
        upsert acc;
        
      
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Closed Won';
        upsert opp;
        
        opportunity op =[Select id, Pipeline_stage__c from opportunity where stageName='Closed Won' and id=:opp.id];
        
        
      //  System.assert(false,[select id,stageName From opportunity where id=:opp.id]);             
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        upsert testBox;
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Funding-Vendor';
        sf.cf_opportunity__c = op.id;
        sf.cf_box_folder_id__c = '11446498';
        upsert sf;
       
        Sub_folder__c sflst =[Select id,cf_box_folder_id__c,cf_opportunity__c,name, cf_opportunity__r.Pipeline_stage__c from Sub_folder__c where id=:sf.id];
        
        subList.add(sflst);
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
       
        Profile prf= [select id,Name From Profile Where Name='EE Partner User'];
        profileMap.put(prf.Name,prf.id);
        
        
        List<Box_error__c> OppList = new List<Box_error__c>();
        box_error__c bxerr = new box_error__c();
        bxerr.Opportunity__c = opp.id; 
        bxerr.name = '409'; 
        bxerr.Message__c = 'Attachment id-'; 
        bxerr.Body__c = '{"type":"error","status":409,"code":"item_name_in_use","context_info":{"conflicts":{"type":"folder","id":"5045260509","sequence_id":"0","etag":"0","name":"2796_9019apricotst_JamesTobias"}},"help_url":"http:developers.box.com","message":"Item with the same name already exists","request_id":"1145339348561cbaa279ec4"}';
        bxerr.Type__c = 'EE';
        bxerr.Status__c = 'Error';  
        OppList.add(bxerr); 
       
        List<Opportunity_Collaboration_Recovery__c> lstclb = new List<Opportunity_Collaboration_Recovery__c>();
        Opportunity_Collaboration_Recovery__c clb = new Opportunity_Collaboration_Recovery__c(BoxCollaboration_Id__c='123456',Sub_Folder__c =sf.id,UserEmail__c='anki@abc.com',Profile_Id__c=prf.id);
        upsert clb;
        lstclb.add(clb);
        
        Batch_OpportunityCollaborationRecovery bcb = new Batch_OpportunityCollaborationRecovery('EE');
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        bcb.execute(BC,subList);
        Test.setMock(HttpCalloutMock.class, new TestFolderInfoMock());
        Test.stopTest();         
    }  
   
        
}