posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Support Vendors (Accounting, Professional Services, etc)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Profile__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_SubFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix SubFolder</label>
        <referenceTo>BoxAccessMatrix_SubFolder__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Profiles</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Profile</label>
    <nameField>
        <label>BoxAccessMatrix Profiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Stage__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix Profile</label>
        <referenceTo>BoxAccessMatrix_Profile__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Stages</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box_Permission__c</fullName>
        <label>Box Permission</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previewer Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer Uploader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Stage</label>
    <nameField>
        <label>BoxAccessMatrix Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_SubFolder__c.object
<CustomObject>
    <fields>
        <fullName>SubFolder_Name__c</fullName>
        <label>SubFolder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix SubFolder</label>
    <nameField>
        <label>BoxAccessMatrix SubFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix SubFolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CloseDate__c</fullName>
        <label>CloseDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opp_Pipeline_Stage__c</fullName>
        <formula>Opportunity__r.Pipeline_Stage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StageName__c</fullName>
        <label>StageName</label>
        <picklist>
            <picklistValues>
                <fullName>Schedule Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reschedule Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Input Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docusign Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docusign Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduct Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Submitted to DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Rejected by DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Contract Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Layout and Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Rejected by DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Rejected by UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Submitted to DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Submitted to UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Sunrun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Layout Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release to Installer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Not Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Layout Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Cancelled After Install Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed/Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestBoxPermissionController.cls
@isTest
public class TestBoxPermissionController{
   
 
  public static testmethod void TestBoxPermissionController1(){
     
    Profile pf = [Select Id , name from Profile where Name ='System Administrator'];
    Account acc =new Account();
    acc.name = 'irfan khan';
    upsert acc;
   
    Deal__c opp = new Deal__c();								
    //opp.name = 'Test opp';
    opp.Account__c = acc.id;
    opp.CloseDate__c = date.today();
    opp.stageName__c = 'Closed Won';
    upsert opp;
        
    Deal__c op =[Select id, Opp_Pipeline_Stage__c from Deal__c where stageName__c='Closed Won' and id=:opp.id];
     
     BoxAccessMatrix_SubFolder__c bsf = new BoxAccessMatrix_SubFolder__c(Name = 'Sales',SubFolder_Name__c='Sales');
     insert bsf;
     
     BoxAccessMatrix_Profile__c bsp = new BoxAccessMatrix_Profile__c(BoxAccessMatrix_SubFolder__c = bsf.id,Profile_Id__c=pf.id,Profile_Name__c = pf.name);
     insert bsp;
     
     BoxAccessMatrix_Stage__c bms = new BoxAccessMatrix_Stage__c(BoxAccessMatrix_Profile__c = bsp.id,Box_Permission__c='Editor',Check__c=true,Stage__c='Closed Won');
     insert bms;
     
     BoxPermissionController bp = new BoxPermissionController();
     
     bp.saveSales();
  
  }
  public static testmethod void TestBoxPermissionController2(){
     
     Profile pf = [Select Id , name from Profile where Name ='System Administrator'];
     Account acc =new Account();
     acc.name = 'irfan khan';
     upsert acc;
   
    Deal__c opp = new Deal__c();
    //opp.name = 'Test opp';
    opp.Account__c = acc.id;
    opp.CloseDate__c = date.today();
    opp.stageName__c = 'Closed Won';
    upsert opp;
        
    Deal__c op =[Select id, Opp_Pipeline_Stage__c from Deal__c where stageName__c='Closed Won' and id=:opp.id];
     
     BoxAccessMatrix_SubFolder__c bsf = new BoxAccessMatrix_SubFolder__c(Name = 'Application',SubFolder_Name__c='Application');
     insert bsf;
     
     BoxAccessMatrix_Profile__c bsp = new BoxAccessMatrix_Profile__c(BoxAccessMatrix_SubFolder__c = bsf.id,Profile_Id__c=pf.id,Profile_Name__c = pf.name);
     insert bsp;
     
     BoxAccessMatrix_Stage__c bms = new BoxAccessMatrix_Stage__c(BoxAccessMatrix_Profile__c = bsp.id,Box_Permission__c='Editor',Check__c=true,Stage__c='Closed Won');
     insert bms;
     
     BoxPermissionController bp = new BoxPermissionController();
     
     bp.saveApplication();
  
  } 
  public static testmethod void TestBoxPermissionController3(){
     
     Profile pf = [Select Id , name from Profile where Name ='System Administrator'];
     
    
     Account acc =new Account();
     acc.name = 'irfan khan';
     upsert acc;
   
    Deal__c opp = new Deal__c();
    //opp.name = 'Test opp';
    opp.Account__c = acc.id;
    opp.CloseDate__c= date.today();  					
    opp.stageName__c = 'Closed Won';
    upsert opp;
     
     BoxAccessMatrix_SubFolder__c bsf = new BoxAccessMatrix_SubFolder__c(Name = 'Funding-Vendor',SubFolder_Name__c='Funding-Vendor');
     insert bsf;
     
     BoxAccessMatrix_Profile__c bsp = new BoxAccessMatrix_Profile__c(BoxAccessMatrix_SubFolder__c = bsf.id,Profile_Id__c=pf.id,Profile_Name__c = pf.name);
     insert bsp;
     
     BoxAccessMatrix_Stage__c bms = new BoxAccessMatrix_Stage__c(BoxAccessMatrix_Profile__c = bsp.id,Box_Permission__c='Editor',Check__c=true,Stage__c='Closed Won');
     insert bms;
     
     BoxPermissionController bp = new BoxPermissionController();
     
     bp.saveFunding();
  
  }
   public static testmethod void TestBoxPermissionController4(){
     
     Profile pf = [Select Id , name from Profile where Name ='System Administrator'];
     
       
     Account acc =new Account();
     acc.name = 'irfan khan';
     upsert acc;
   
    Deal__c opp = new Deal__c();
    //opp.name = 'Test opp';
    opp.Account__c = acc.id;
    opp.CloseDate__c = date.today();
    opp.stageName__c = 'Closed Won';   
    upsert opp;
     
     BoxAccessMatrix_SubFolder__c bsf = new BoxAccessMatrix_SubFolder__c(Name = 'EE',SubFolder_Name__c='EE');
     insert bsf;
     
     BoxAccessMatrix_Profile__c bsp = new BoxAccessMatrix_Profile__c(BoxAccessMatrix_SubFolder__c = bsf.id,Profile_Id__c=pf.id,Profile_Name__c = pf.name);
     insert bsp;
     
     BoxAccessMatrix_Stage__c bms = new BoxAccessMatrix_Stage__c(BoxAccessMatrix_Profile__c = bsp.id,Box_Permission__c='Editor',Check__c=true,Stage__c='Closed Won');
     insert bms;
     
     BoxPermissionController bp = new BoxPermissionController();
     
     bp.saveEE();
  
   } 
 }