posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Lead_Numeric_Id_Text__c</fullName>
        <description>Allows the Lead Numeric ID autonumber field to propagate to the Account object on Lead conversion</description>
        <label>Lead Numeric Id Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Intacct_Entity__c.object
<CustomObject>
    <label>Intacct Entity</label>
    <nameField>
        <label>Intacct Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Intacct Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Intacct_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intacct Entity</label>
        <referenceTo>Intacct_Entity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Numeric_ID_Text__c</fullName>
        <description>Text field for mapping Lead Numeric ID on conversion.</description>
        <label>Lead Numeric ID Text</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/CreatePropertyFromOppTest.cls
@isTest
public class CreatePropertyFromOppTest 
{
    public static testMethod void CreatePropertyFromOppTestMethod()
    {
        Account acct = new Account();
        acct.LastName = 'Test Account';
        acct.FirstName = 'Trigger';
        acct.BillingState = 'Louisiana';
        acct.BillingCountry = 'United States';
        insert acct;
        
		Intacct_Entity__c testIntacctEntity = new Intacct_Entity__c(Name = 'PG of LA');
        insert testIntacctEntity;
            
        Intacct_Entity__c testIntacctEntity2 = new Intacct_Entity__c(Name = 'PG of CT');
        insert testIntacctEntity2;
            
        Intacct_Entity__c testIntacctEntity3 = new Intacct_Entity__c(Name = 'PG of NY');
        insert testIntacctEntity3;        
        
        Opportunity opp = new Opportunity();
        opp.Lead_Numeric_ID_Text__c = '1';
        opp.StageName = 'Schedule Appointment';
        opp.Name = 'TEST NAME';
        opp.CloseDate = datetime.now().date();
        opp.AccountId = acct.Id;
        Test.startTest();
        insert opp;
        System.assertNotEquals(opp, null);
        Test.stopTest();
    }
}