posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Contacting Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Not Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Existing Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Can&apos;t Reach Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Number__c</fullName>
        <displayFormat>PROJ-{000000}</displayFormat>
        <externalId>true</externalId>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete - Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subcontractor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subcontractor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Subcontractor, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/AccountProjectTableController.cls
public without sharing class AccountProjectTableController
{
    public List<Project__c> projects;
    private List<Opportunity> AccountOppIds;
    private ID[] oppIds;
    //

    public AccountProjectTableController()
    {
        AccountOppIds = [SELECT Id FROM Opportunity WHERE Account.Id IN (:(Id)ApexPages.currentPage().getParameters().get('id'))];

        oppIds = new List<Id>();


        for(Opportunity oppId: AccountOppIds)
        {
            oppIds.add(oppId.Id);
        }

        //Pull the current project id,name, and related milestones from database
        projects = [SELECT
         Id,
         Name,
         Subcontractor__r.Id,
         Subcontractor__r.Name,
         Opportunity__c,
         Opportunity__r.Name,
         Kickoff__c,
         Deadline__c,
         Status__c,
         RecordType.Name
         FROM Project__c
         WHERE Opportunity__c
         IN :oppIds
         ORDER BY Project_Number__c
               ];
    }

    public List<Project__c> getprojects()
    {
        return projects;
    }
}