posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Support Vendors (Accounting, Professional Services, etc)</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Profile__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_SubFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix SubFolder</label>
        <referenceTo>BoxAccessMatrix_SubFolder__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Profiles</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Profile</label>
    <nameField>
        <label>BoxAccessMatrix Profiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Stage__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix Profile</label>
        <referenceTo>BoxAccessMatrix_Profile__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Stages</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box_Permission__c</fullName>
        <label>Box Permission</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previewer Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer Uploader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Stage</label>
    <nameField>
        <label>BoxAccessMatrix Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_SubFolder__c.object
<CustomObject>
    <fields>
        <fullName>SubFolder_Name__c</fullName>
        <label>SubFolder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix SubFolder</label>
    <nameField>
        <label>BoxAccessMatrix SubFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix SubFolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Allows_for_Multiple_Members__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allows for Multiple Members</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referrals I Have Referred</relationshipLabel>
        <relationshipName>Referral</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Referral</fullName>
        <active>true</active>
        <description>one of these for any given ‘event’ to tie it to the Campaign and track earned vs paid</description>
        <label>Referral</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contracts_Approved_Date__c</fullName>
        <inlineHelpText>Enter Date Contracts were Approved</inlineHelpText>
        <label>Contracts Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pipeline_Stage__c</fullName>
        <formula>IF( AND(Permanent_Removal__c, NOT(ISNULL(R_P_Removal_Date__c))), &quot;Removed &amp; Terminated&quot;,
IF( Num_of_LD_Leases__c &gt; 0
	, &quot;Boarded&quot;,
    IF(TEXT( StageName ) = &quot;Closed Won&quot;,
		IF( OR( Lease_Boarding_Status__c = &quot;Upload to LD (based on CAO File)&quot;,Lease_Boarding_Status__c = &quot;Boarded&quot;, Has_Been_Boarded__c )
			, &quot;Boarded&quot;
			, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c)) &amp;&amp; NOT(ISNULL(EU_Completed_Date__c))
				, &quot;Need to Board&quot;
				, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Solar Panels&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Uptown Solar Lease&quot;)) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c))
					, &quot;Need to Board&quot;
					, IF( AND( NOT(ISNULL(PVI_Net_Meter_Install_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
						, &quot;Need to Board&quot;
						, IF(  AND(  NOT(ISNULL(PVI_Placed_In_Service_Date__c)), ISNULL(EU_Completed_Date__c), Has_EE_as_a_Solar_Product__c )
							, &quot;Pending EU&quot;
							, IF( AND( NOT(ISNULL(PVI_Placed_In_Service_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
								, &quot;Pending Net Meter&quot;
								, IF ( AND(ISNULL(PVI_Placed_In_Service_Date__c ), NOT(ISNULL(PVI_Rails_and_Panels_Left_WH_Date__c)))
									, &quot;PV System Left Warehouse&quot; 
									, TEXT( StageName )
								)
							)
						)
					)
				)
			)
        )
        ,TEXT( StageName )
	)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referral_Type__c</fullName>
        <label>Referral Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Party</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Opportunities</relationshipLabel>
        <relationshipName>Referrer</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Release</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subcontractor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subcontractor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Subcontractor, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Child_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Trigger_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Opportunity_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opportunity Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Setting</label>
</CustomObject>

posiGen_FullsendBox/src/classes/TestOpportunityTriggerHandler.cls
@isTest 
public class TestOpportunityTriggerHandler{
    static testMethod void unitTest()
    {
      try{
       // RecordType rt2 = [Select id from RecordType where name='EE'];
        Set<Id>oppSet = new Set<Id>(); 
        final Date closeDate = date.newInstance(2014,11, 18);

        Account testAcct = new Account(LastName = 'Test Account', FirstName = 'Trigger', BillingState = 'Louisiana', BillingCountry = 'United States');
        insert testAcct;
        
        Trigger_Setting__c ts = new Trigger_Setting__c(Opportunity_Trigger__c =true);
        insert ts; 
        
        OpportunityTriggerHandler.firstRunPmTool = true;
        Opportunity testOpp = new Opportunity(Contracts_approved_date__c = Date.Today(), Name = 'Test Opp', AccountId = testAcct.Id, StageName = 'Schedule Appointment', CloseDate = closeDate);
        insert testOpp;

        
       /* Project__c pj = new Project__c();
        pj.RecordTypeId=rt2.id;
        pj.Name = 'old prj';
        pj.Opportunity__c = testOpp.id;
        pj.Subcontractor__c = testAcct.id;
       
        insert pj;*/
        oppSet.add(testOpp.id);
        OpportunityTriggerHandler.firstRun =true;
        
        opportunity op =[Select id, Pipeline_stage__c from opportunity where id=:testOpp.id];
        
         Profile prf= [select id,Name From Profile Where Name='EE Admin'];
         
          
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='EE';
        bams.Name='EE';
        upsert bams;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='EE Admin';
        
        upsert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=op.Pipeline_stage__c;
        BAM.check__c=true;
        upsert BAM;
     
        List<String> sflst = new List<String>(); 
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = bams.Name;
        sf.cf_opportunity__c = op.id;
        sf.cf_box_folder_id__c = '11446498';
        insert sf;
        
       sflst.add(sf.cf_box_folder_id__c );
            
       
        
        
       
        testOpp.StageName = 'Closed Won';
        
        update testOpp;
        OpportunityTriggerHandler.firstRun =true;
       
          
        
        
      
      
        
        
        
       
                      
        OpportunityTriggerHandler ot = new OpportunityTriggerHandler();
        
        ot.bulkBefore();
        ot.bulkAfter();
        ot.beforeInsert();
        ot.beforeUpdate();
        ot.afterDelete();
        ot.afterUnDelete();
        //PMTool.createPMRecord(oppSet);
        
        delete op;
        
       }
      catch(Exception e){
        //system.assert(false,e.getstacktracestring()+'hiii'+e.getmessage());
       }  
    }
    
    static testMethod void unitTest2()
    {
        User usr1 = [select id, Name, ProfileId  from User where Profile.Name = 'Sales Manager'  and IsActive = true limit 1 ];
        System.runAs(usr1) {  
        
            final Date closeDate = date.newInstance(2014,11, 18);
            
            Account testAcct = new Account(LastName = 'Test Account', FirstName = 'Trigger', BillingState = 'Louisiana', BillingCountry = 'United States');
            insert testAcct;
            System.assert(testAcct.id!=null);
            
            OpportunityTriggerHandler.firstRunPmTool = true;
            Opportunity testOpp = new Opportunity(Contracts_approved_date__c = Date.Today(), Name = 'Test Opp', AccountId = testAcct.Id, StageName = 'Schedule Appointment', CloseDate = closeDate);
            insert testOpp;
            System.assert(testOpp.id!=null);
            
            Sub_Folder__c sc2= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=testOpp.id,Name='Funding-Vendor');
            insert sc2;
            system.assert(sc2.id!=null);
            
            RecordType referralProgramRecordType = [SELECT Id FROM RecordType WHERE sObjectType = 'Campaign' AND Name = 'Referral Programs'];
           
            Campaign camp = new Campaign();
            camp.RecordTypeId = referralProgramRecordType.Id;
            camp.Name = 'test camp';
            camp.Allows_For_Multiple_Members__c = false;
            camp.IsActive = true;
            insert camp;
            //system.assert(false, camp);
            
             UtilityController.CreateReferralrecursive = true;
            testOpp.LeadSource = 'Referral';
            testOpp.Referral_Type__c = 'Single';
            testOpp.Referrer__c =testAcct.id;
            
            update testOpp ;
        }
        
        
    }   
    
    static testMethod void unitTest3()
    {
         
        
            final Date closeDate = date.newInstance(2014,11, 18);
            
            Account testAcct = new Account(LastName = 'Test Account', FirstName = 'Trigger', BillingState = 'Louisiana', BillingCountry = 'United States');
            insert testAcct;
            System.assert(testAcct.id!=null);
            
            Opportunity testOpp = new Opportunity(Name = 'Test Opp', AccountId = testAcct.Id, StageName = 'Schedule Appointment', CloseDate = closeDate);
            insert testOpp;
            System.assert(testOpp.id!=null);
            
            RecordType referralProgramRecordType = [SELECT Id FROM RecordType WHERE sObjectType = 'Campaign' AND Name = 'Referral Programs'];
           
            Campaign camp = new Campaign();
            
            String abc = camp.id;    

            //system.assert(false, camp);

            
            update testOpp ;
       
        
        
    } 
        
}