posiGen_FullsendBox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Days_Delinquent__c</fullName>
        <label>LD Lease Days Delinquent</label>
        <summarizedField>LD_Lease__c.Days_Delinquent__c</summarizedField>
        <summaryForeignKey>LD_Lease__c.Account__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Employer_Phone__c</fullName>
        <label>Employer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>LD_Lease_Total_Past_Due__c</fullName>
        <description>Roll-up summary of the total amount past due.</description>
        <label>LD Lease Total Past Due</label>
        <summarizedField>LD_Lease__c.Total_Past_Due__c</summarizedField>
        <summaryForeignKey>LD_Lease__c.Account__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NVMContactWorld__NVM_Phone__c</fullName>
        <description>NewVoiceMedia click to dial Phone</description>
        <formula>IF( 
        LEN(  Phone  )&gt;0 , 
        HYPERLINK( &quot;/apex/NVMContactWorld__NVM_AgentUI_ClickToDialInitiator?number=&quot; &amp; 
                   SUBSTITUTE(Phone, &quot;+&quot;, &quot;%2B&quot;) &amp; 
                   &quot;&amp;oid=&quot; &amp; Id &amp; 
                   &quot;&amp;name=&quot; &amp;  Name &amp;
                   &quot;&amp;type=Account&quot;, 
                   Phone, &quot;nvm-clicktodial&quot;) 
                   &amp; &quot; &quot; &amp; IMAGE( &quot;../servlet/servlet.FileDownload?file=015A0000000FU0f&quot;, &quot;Dial&quot;), &quot;&quot;)</formula>
        <inlineHelpText>Click to dial Phone</inlineHelpText>
        <label>NVM Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numeric_ID__c</fullName>
        <externalId>true</externalId>
        <label>Numeric ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Contacting Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Not Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned - Existing Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Can&apos;t Reach Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employer_Phone__c</fullName>
        <label>Employer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Numeric_ID__c</fullName>
        <label>Numeric ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Solar_Product__c</fullName>
        <label>Solar Product</label>
        <picklist>
            <picklistValues>
                <fullName>Solar Hot Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Efficiency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solar Panels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uptown Solar Lease</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>System_Size_in_KW__c</fullName>
        <description>From PV Project</description>
        <label>System Size in KW</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Issue__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Issues (Account Name)</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseAgeDays__c</fullName>
        <formula>Today()-DATEVALUE(CreatedDate__c)</formula>
        <label>Case Age (Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseNumber__c</fullName>
        <label>CaseNumber</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>PG_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PG Product</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Issues</relationshipLabel>
        <relationshipName>Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request to Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request for Contractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Manager Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Meter Provisioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/LD_Lease__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account the record is related to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LD Leases</relationshipLabel>
        <relationshipName>LD_Leases</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Committed_Date__c</fullName>
        <label>Committed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_No__c</fullName>
        <description>Contract Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Contract Number</inlineHelpText>
        <label>Contract No</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Days_Delinquent__c</fullName>
        <description># of days the oldest past due invoice is delinquent</description>
        <inlineHelpText># of days the oldest past due invoice is delinquent</inlineHelpText>
        <label>Days_Delinquent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Interaction__c</fullName>
        <label>Last Interaction</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Past_Due__c</fullName>
        <description>Payment Amount Invoiced with a prior payment date, not yet paid. (Includes Base Rent, Fees, &amp; Taxes)</description>
        <inlineHelpText>Payment Amount Invoiced with a prior payment date, not yet paid. (Includes Base Rent, Fees, &amp; Taxes)</inlineHelpText>
        <label>Total_Past_Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>LD Lease</label>
    <nameField>
        <label>LD Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LD Leases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ordered_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ordered By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Projects__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Related Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Phone__c</fullName>
        <formula>Opportunity__r.Account.Secondary_Phone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Secondary Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete - Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subcontractor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subcontractor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Subcontractor, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>NVMContactWorld__NVM_Phone__c</fullName>
        <description>NewVoiceMedia click to dial Phone</description>
        <formula>IF( 
        LEN( Phone )&gt;0 , 
        HYPERLINK( &quot;/apex/NVMContactWorld__NVM_AgentUI_ClickToDialInitiator?number=&quot; &amp; 
                   SUBSTITUTE(Phone, &quot;+&quot;, &quot;%2B&quot;) &amp; 
                   &quot;&amp;oid=&quot; &amp; Id &amp; 
                   &quot;&amp;name=&quot; &amp; FirstName &amp; &quot;%20&quot; &amp;  LastName &amp; 
                   &quot;&amp;type=User&quot;, 
                   Phone, &quot;nvm-clicktodial&quot;) 
                   &amp; &quot; &quot; &amp; IMAGE( &quot;../servlet/servlet.FileDownload?file=015A0000000FU0f&quot;, &quot;Dial&quot;), &quot;&quot;)</formula>
        <inlineHelpText>Click to dial Phone</inlineHelpText>
        <label>NVM Phone</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/AccountDetailsController.cls
//Controller Class for AccountDetails

Public without sharing class AccountDetailsController{

   
    //Class Instances (get,set)
    Public String accountId {get;set;}  
    Public List<Account > allAccounts {get;set;}    
    Public String selMan {get;set;}
    Public String selAcc {get;set;}
    Public List<SelectOption> listProjMan {get;set;} 
    Public List<SelectOption> listAccMan {get;set;} 
    Public Account accRecord {get;set;}     
    Public transient List<wrapaccount> wrapperList{get;set;} 
      
    //constructor
    Public AccountDetailsController()
    {    
        
      try{  selMan = '-None-';
            selAcc = '-None-';
            accountId ='';
            wrapperList = new List<wrapaccount>();
            /*
               Account Manager List
            */
            listProjMan = new List<SelectOption>();
            listProjMan.add(new SelectOption('-None-','-None-'));
            for(User u : [select id, name from user where userrole.name ='Account Manager' AND IsActive =true]) {    
                listProjMan.add(new SelectOption(u.id,u.name));
            }
            
            /*
                 Lease Days Delinquent List
            */  
            listAccMan = new List<SelectOption>();          
            listAccMan.add(new SelectOPtion('-None-','-None-'));
            listAccMan.add(new SelectOption('11-30','11-30'));
            listAccMan.add(new SelectOption('31-60','31-60'));
            listAccMan.add(new SelectOption('61-90','61-90'));
            listAccMan.add(new SelectOption('91-180','91-180'));
            listAccMan.add(new SelectOption('180+','180+'));
            /**
                Load Accounts
            **/
            loadAccounts();
            accountId = UserInfo.getUserId();
      }
      catch (QueryException e) {
             //ApexPages.addMessages(e);   
             system.assert(false, e.getLineNumber()+'--'+e.getMessage());
      }
    }
    
    public void loadAccounts(){         
        try{
            resetAccs();
           
           string query='Select id,Days_Delinquent__c,LD_Lease_Total_Past_Due__c, LastActivityDate, Name,BillingCountry, phone,BillingStreet, AccountNumber,BillingCity, BillingAddress, BillingState, BillingPostalCode, PersonMobilePhone, PersonEmail, PersonHomePhone, (Select id, Last_Interaction__c, Committed_Date__c From LD_Leases__r order by LastModifiedDate desc limit 1 ) From Account ';
           
           if(selMan != '-None-' && selAcc == '-None-'){    
              query += 'where OwnerId =: selMan order by name';
           }else if(selMan == '-None-' && selAcc != '-None-'){
                if(selAcc == '180+'){
                	query += 'where Days_Delinquent__c >= 180 order by name';                    
                }else{
                    List<String> daysValue = selAcc.split('-');
                    Decimal strt= Decimal.ValueOF(daysValue[0].trim());
                    Decimal stp =Decimal.ValueOF(daysValue[1].trim());  
                    query += 'where Days_Delinquent__c >=:strt and Days_Delinquent__c <=:stp order by name';                      
                }
            }else if(selMan != '-None-' && selAcc != '-None-'){    
                if(selAcc == '180+'){
                	query += 'where Days_Delinquent__c >= 180 and OwnerId =: selMan order by name';                    
                }else{
                    List<String> daysValue = selAcc.split('-');
                    Decimal strt= Decimal.ValueOF(daysValue[0].trim());
                    Decimal stp =Decimal.ValueOF(daysValue[1].trim());  
                    query += 'where Days_Delinquent__c >=:strt and Days_Delinquent__c <=:stp and OwnerId =: selMan order by name';                     
                }  
            }
            
            if(selMan == '-None-' && selAcc == '-None-') {
                wrapperList = new List<wrapaccount>();  
            }else{
            	for(Account a : Database.query(query)){
            		wrapperList.add(new wrapaccount(a));    
            	}
            }         
        }  			
        catch (Exception ex) {  
             system.assert(false, ex.getLineNumber()+'--'+ex.getMessage());  
        }
    }
      
    
    /*  
    Fetch specific account details when clicked on Account name
    */  
    Public void getAccountDetails(){  
       try{              
           accRecord = [Select id, NVMContactWorld__NVM_Phone__c, Secondary_Phone__c, Employer_Phone__c, PersonAssistantPhone, phone, Name,  BillingCountry, BillingStreet, AccountNumber,BillingCity, BillingAddress, BillingState, BillingPostalCode, PersonMobilePhone, PersonEmail, PersonHomePhone, LastActivityDate , (Select id, Name, Status__c, RecordType.Name, createdDate from Projects__r),  (Select id, Name,  Days_Delinquent__c, Total_Past_Due__c, Contract_No__c From LD_Leases__r),(Select id, Name, System_Size_in_KW__c, Solar_Product__c, Numeric_ID__c from Deals__r), (Select id, CaseNumber__c, CaseAgeDays__c, Status__c From Issues__r), (select id, Type, ActivityDate, Description, Owner.Name from tasks order by ActivityDate desc) From Account Where Id =: accountId];         
       }
       catch (Exception ex) {
             system.assert(false, ex.getLineNumber()+'--'+ex.getMessage());  
        }  
        
    }       
    Public void resetAccs() {
        accRecord = null;
        wrapperList = new List<wrapaccount>();        
       // accountId = null;
    }
    
    //##THIS IS WRAPPER CLASS			  
    public class wrapaccount{
    
	    public Id accId{get;set;}
	    public string accName{get;set;}
	    public string accPhone{get;set;}
	    public Decimal accDaysDelinquent{get;set;}  
	    public Decimal accLeaseTotalPastDue{get;set;}
	    public Date accLastActivity{get;set;}  	    
	    public string ldLeaseLastInteraction{get;set;}
	    public Date ldCommittedDate{get;set;}    
     
	    public wrapaccount(account acc){    	 
		     this.accId=acc.Id;
		     this.accName=acc.Name;
		     this.accPhone=acc.phone;
		     this.accDaysDelinquent=acc.Days_Delinquent__c;
		     this.accLeaseTotalPastDue=acc.LD_Lease_Total_Past_Due__c;
		     this.accLastActivity=acc.LastActivityDate;
		     
		     if(acc.LD_Leases__r.size()> 0)
		     {
			     this.ldLeaseLastInteraction=acc.LD_Leases__r[0].Last_Interaction__c;
			     this.ldCommittedDate=acc.LD_Leases__r[0].Committed_Date__c;			    
		     }	     
	   }   
    }   
    
    
}