posiGen_FullsendBox/src/objects/Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <controllingField>State__c</controllingField>
            <picklistValues>
                <fullName>01CT- PVAssessment Schematics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment Breaker Box photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment Pathfinder Trace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment Powerclerk Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment PV Assessment site photo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment Roof photo’s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- PVAssessment Site Survey form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>01CT- Permitting Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Attachment C NYSERDA Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Close out Images</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Conditional Utility Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Field Verification Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Final Utility Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Inspection Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Permits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Posigen QC Checklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY Install Site Safety Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment 3 Line Electric Drawing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Agent Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Attachment B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Pathfinder Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Pre-site Assessment Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Site Photos (NYSERDA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Site Visit/Clipboard Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02NY- PVAssessment Utility Interconnect Auth Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03CTNY- Engineering Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03CTNY- PV Assessment Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03CTNY- PV Install Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03CTNY- Design/Engineering Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breaker Box Picture</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <displayFormat>ATT-{000000}</displayFormat>
        <label>Attachment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manual_Url__c</fullName>
        <label>Manual Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Existing Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete - Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Sub_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/AttachmentUploaderSchedulerCustom.cls
public without sharing class AttachmentUploaderSchedulerCustom {
    public static String base_url = 'https://app.box.com/files/0/f/';
    
    public AttachmentUploaderSchedulerCustom() {
        
    }   
         
   public static void runUploadCustom(){
        try{
           system.debug('AttachmentUploaderSchedulerCustom----------------'+datetime.now());
            Set<String> boxErrorList = new Set<String>();
            for(Box_Error__c bxer:[Select Id,Deal__c ,name ,Type__c ,Status__c , Message__c, body__c from Box_Error__c where name like 'Heap Size Exceed%' and Type__c = 'Custom Doc' and Status__c = 'Error' limit 9]){
                    system.debug('##################################'+ bxer.id);
                    boxErrorList.add(String.valueOf(bxer.id)); 
             }
             AttachmentUploaderSchedulerCustom.uploadattachments(boxErrorList);

        }
        catch(Exception e){
            system.debug('AttachmentUploaderSchedulerCustom Exception----------------'+e.getMessage());
        }
        
    }     
    
    @future(callout=true)
    public static void uploadattachments(Set<String> bxErrSet){
        Set<String> attachmentIdSet = new Set<String>();
        List<Box_Error__c> updateBoxErrorList = new List<Box_Error__c>();
        List<Box_Error__c> bxErrList = new List<Box_Error__c>();
        
        try{
            List<Box_Error__c> boxErrorList = new List<Box_Error__c>();
            for(Box_Error__c bxer:[Select Id,Deal__c ,name ,Type__c ,Status__c , Message__c, body__c from Box_Error__c where id in: bxErrSet]){
                   boxErrorList.add(bxer); 
              }
    
              Map<String,Box_Error__c> bxAttachMap = new Map<String,Box_Error__c>();
              Set<String> attachmentSet = new Set<String>();
              for(Box_Error__c bx: boxErrorList){
                  List<String> a1 = bx.Message__c.split('-');
                  List<string> a2 = a1[1].split(',');
                  attachmentSet.add(a2[0]);
                  bxAttachMap.put(a2[0], bx); 
              }
              
              Map<Id,String> fvSubFoldersMap = new Map<Id,String>();
              for(Sub_folder__c subFolder : [select cf_Deal__c, cf_box_folder_id__c, name from sub_folder__c where name = 'Funding-Vendor']){
                  fvSubFoldersMap.put(subFolder.cf_Deal__c, subFolder.cf_box_folder_id__c);
              }
              
              Map<String,String> customAttachmentsCMap = new Map<String,String>();
              Map<String,String> errorMap = new Map<String,String>();
              for(Attachment__c att : [select id, project__r.Deal__c from attachment__c]){
                   if(fvSubFoldersMap.containsKey(att.project__r.Deal__c)){
                      
                          customAttachmentsCMap.put(att.id, fvSubFoldersMap.get(att.project__r.Deal__c));
                          errorMap.put(att.id,att.project__r.Deal__c);
                   }
              }
              
              for(Attachment attachmentObj : [select id, name, body, parentId from Attachment where id in: attachmentSet]){
                   if(attachmentIdSet == null || !attachmentIdSet.contains(attachmentObj.id)){
                          system.debug('################################## attachmentObj2 '+ attachmentObj.id);
                          attachmentIdSet.add(attachmentObj.id);
                      if(attachmentObj.body.size()<12000000 || Test.isRunningTest()){
                  
                        system.debug('############################### attachmentObj name'+attachmentObj.name); 
                    
                        String boundary = '----------------------------'+String.valueOf(DateTime.now().getTime())+'';
                        String header = '--'+boundary+'\nContent-Disposition: form-data; name="file"; filename="'+attachmentObj.name+'";\nContent-Type: application/octet-stream';
                        String footer = '--'+boundary+'--';
                        String headerEncoded = EncodingUtil.base64Encode(Blob.valueOf(header+'\r\n\r\n'));
                        transient String bodyEncoded='';
                        transient String last4Bytes ='';
                        while(headerEncoded.endsWith('=')){
                            header+=' ';
                            headerEncoded = EncodingUtil.base64Encode(Blob.valueOf(header+'\r\n\r\n'));
                        }
                       bodyEncoded = EncodingUtil.base64Encode(attachmentObj.body);
                       
                       Blob bodyBlob = null;
                     if(bodyEncoded!=null && bodyEncoded!='') 
                       last4Bytes = bodyEncoded.substring(bodyEncoded.length()-4,bodyEncoded.length());
                     if(last4Bytes.endsWith('==')) {
                        last4Bytes = last4Bytes.substring(0,2) + '0K';
                    
                        bodyEncoded = bodyEncoded.substring(0,bodyEncoded.length()-4) + last4Bytes; 
                        String footerEncoded = EncodingUtil.base64Encode(Blob.valueOf(footer));
                        bodyBlob = EncodingUtil.base64Decode(headerEncoded+bodyEncoded+footerEncoded);
                      } 
                     else if(last4Bytes.endsWith('=')) {
                        last4Bytes = last4Bytes.substring(0,3) + 'N';
                        bodyEncoded = bodyEncoded.substring(0,bodyEncoded.length()-4) + last4Bytes;
                        footer = '\n' + footer;
                        String footerEncoded = EncodingUtil.base64Encode(Blob.valueOf(footer)); 
                        bodyBlob = EncodingUtil.base64Decode(headerEncoded+bodyEncoded+footerEncoded);
                       }
                     else{
                        footer = '\r\n' + footer;
                        String footerEncoded = EncodingUtil.base64Encode(Blob.valueOf(footer));
                        bodyBlob = EncodingUtil.base64Decode(headerEncoded+bodyEncoded+footerEncoded);  
                      }
                      
                    Box__c bx = Box__c.getInstance();                  
                    HttpRequest reqfile = new HttpRequest();
                 
                    reqfile.setHeader('Content-Type', 'multipart/form-data; boundary=' + boundary);
                    // Set method and endpoint
                    reqfile.setMethod('POST');
                    reqfile.setEndpoint('https://upload.box.com/api/2.0/files/content?parent_id='+customAttachmentsCMap.get(attachmentObj.parentId));
                    reqfile.setBodyAsBlob(bodyBlob);
                    reqfile.setTimeout(120000);
                    reqfile.setHeader('Authorization','Bearer '+bx.BoxAccess_Token__c);        
                    reqfile.setHeader('Content-Length',String.valueof(reqfile.getBodyAsBlob().size()));
                    // Send HTTP request and get HTTP response
                    Http httpfile = new Http();
                    HTTPResponse resfile = httpfile.send(reqfile);
                    if(resfile.getStatusCode() == 201){
                          system.debug('######################################## resfile.getBody()'+ resfile.getBody());
                                 FileWrapper fw = (FileWrapper) System.JSON.deserialize(resfile.getBody(), FileWrapper.class);
                                 for(Entries_Z entry: fw.entries){
                                   
                                   system.debug('######################################## entry.parent.id'+ entry.parent.id);
                                   system.debug('######################################## parent_folder'+ customAttachmentsCMap.get(attachmentObj.parentId));
                                
                                     
                                     Box_Error__c bxerr = bxAttachMap.get(attachmentObj.id);
                                     bxerr.Deal__c = errorMap.get(attachmentObj.parentId); 
                                     bxerr.name = String.valueOf(resfile.getStatusCode()); 
                                     bxerr.Message__c = 'Attachment id-'+attachmentObj.id; 
                                     bxerr.Body__c = resfile.getBody();
                                     bxerr.Type__c = 'Custom Doc';
                                     bxerr.Status__c = 'Success';
                                     
                                  // constructing manual url
                                     String manual_url = base_url;
                                     manual_url += customAttachmentsCMap.get(attachmentObj.parentId);
                                     manual_url += '/1/';
                                     manual_url += 'f_'+entry.id;
                                     
                                     bxerr.Manual_Url__c = manual_url;
                                     
                                     system.debug('######################################## manual_url'+ manual_url);
                                     
                                     updateBoxErrorList.add(bxerr);
                                   
                          }
                        
                      }
                     else{
                               Box_Error__c bxerr = bxAttachMap.get(attachmentObj.id);
                               bxerr.Deal__c = errorMap.get(attachmentObj.parentId); 
                               bxerr.name = String.valueOf(resfile.getStatusCode())+'-Duplicate Attachment'; 
                               bxerr.Message__c = 'Attachment id-'+attachmentObj.id; 
                               bxerr.Body__c = resfile.getBody();
                               bxerr.Type__c = 'Custom Doc';
                               bxerr.Status__c = 'Error';
                         
                               updateBoxErrorList.add(bxerr);
                        }  
                    }                    
               }
            }
        }
        catch(Exception e){
             system.debug('######################################## Exception '+ e.getMessage());
             system.debug('######################################## Exception '+ e.getStackTraceString());
             Box_Error__c bxerr = new Box_Error__c();
             bxerr.name = 'Exception';
             bxerr.Status__c = 'Error';
             bxerr.Type__c = 'Docusign Doc'; 
             bxerr.Message__c = e.getMessage(); 
             bxerr.Body__c = e.getStackTraceString();
             
             bxErrList.add(bxerr);
        }
        finally{
                update updateBoxErrorList;
                insert bxErrList;
                
              
           }

    }
    
    public class FileWrapper {
    public Integer total_count;
    public List<Entries_Z> entries;
  }
  
  public class Parent {
    public String type;
    public String id;
    public String sequence_id;
    public String etag;
    public String name;
  }


  public class Entries_Z {
    public String type;
    public String id;
    public String sequence_id;
    public String etag;
    public String sha1;
    public String name;
    public String description;
    public Integer size;
    public String created_at;
    public String modified_at;
    public Object trashed_at;
    public Object purged_at;
    public String content_created_at;
    public String content_modified_at;
    public Object shared_link;
    public Parent parent;
    public String item_status;
  }       
}