posiGen_FullsendBox/src/objects/Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <displayFormat>ATT-{000000}</displayFormat>
        <label>Attachment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_User__c.object
<CustomObject>
    <fields>
        <fullName>BoxUser_Id__c</fullName>
        <label>BoxUser Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_User_Id__c</fullName>
        <label>SF User Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box User</label>
    <nameField>
        <label>Box User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <externalId>true</externalId>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxFolder_Id__c</fullName>
        <label>BoxFolder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxUser_Id__c</fullName>
        <label>BoxUser Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>O_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Pipeline_Stage__c</fullName>
        <formula>Opportunity__r.Pipeline_Stage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pipeline_Stage__c</fullName>
        <label>Pipeline Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>O_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pipeline_Stage__c</fullName>
        <formula>IF( AND(Permanent_Removal__c, NOT(ISNULL(R_P_Removal_Date__c))), &quot;Removed &amp; Terminated&quot;,
IF( Num_of_LD_Leases__c &gt; 0
	, &quot;Boarded&quot;,
    IF(TEXT( StageName ) = &quot;Closed Won&quot;,
		IF( OR( Lease_Boarding_Status__c = &quot;Upload to LD (based on CAO File)&quot;,Lease_Boarding_Status__c = &quot;Boarded&quot;, Has_Been_Boarded__c )
			, &quot;Boarded&quot;
			, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c)) &amp;&amp; NOT(ISNULL(EU_Completed_Date__c))
				, &quot;Need to Board&quot;
				, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Solar Panels&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Uptown Solar Lease&quot;)) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c))
					, &quot;Need to Board&quot;
					, IF( AND( NOT(ISNULL(PVI_Net_Meter_Install_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
						, &quot;Need to Board&quot;
						, IF(  AND(  NOT(ISNULL(PVI_Placed_In_Service_Date__c)), ISNULL(EU_Completed_Date__c), Has_EE_as_a_Solar_Product__c )
							, &quot;Pending EU&quot;
							, IF( AND( NOT(ISNULL(PVI_Placed_In_Service_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
								, &quot;Pending Net Meter&quot;
								, IF ( AND(ISNULL(PVI_Placed_In_Service_Date__c ), NOT(ISNULL(PVI_Rails_and_Panels_Left_WH_Date__c)))
									, &quot;PV System Left Warehouse&quot; 
									, TEXT( StageName )
								)
							)
						)
					)
				)
			)
        )
        ,TEXT( StageName )
	)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Pipeline_Stage__c</fullName>
        <formula>Opportunity__r.Pipeline_Stage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Sub_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CF_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Child_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/SoqlServices.cls
public with sharing class SoqlServices{

   /* Author: Irfan Khan (Appcino Technologies Pvt. Ltd.)
    * Function for getting opportunity object list.
    * Params:
    *     1. Name: OppIds, Type: Set of Id, Description: Opportunity record ids Set 
    * 
    * Return value:
    *     It will return opportunity list 'OppList', each record contains Id, Name, Owner-Id and Owner-email   
    */
    public static List<Opportunity> getOpportunityList(Set<Id> OppIds){
        List<Opportunity> OppList = new List<Opportunity>();
        if(OppIds.size() > 0){
            OppList = [select Id, Name,Pipeline_Stage__c, owner.email, ownerId from Opportunity where Id in: OppIds];
        }
        return OppList;
    }
      
    //***************New Method*********************** This Method for Deal Attachment to Box***************************************************    
     public static List<Deal__c> getDealList(Set<Id> OppIds){                       
        List<Deal__c> OppList = new List<Deal__c>();
        if(OppIds.size() > 0){
            OppList = [select Id, Name,Opp_Pipeline_Stage__c, owner.email, ownerId from Deal__c where Id in: OppIds];
        }           
        return OppList;          
    }
    //********************************************************************************************************************************************
    
   /* Author: Irfan Khan (Appcino Technologies Pvt. Ltd.)
    * Function for getting opportunity object record.
    * Params:
    *     1. Name: opportunityId, Type: Id, Description: Opportunity record id. 
    * 
    * Return value:
    *     It will return opportunity single record 'opp', this record contains Name, Box folder id and stage of opportunity.   
    */
    public static Opportunity getOpportunityById(Id opportunityId){
        Opportunity opp = [select name, O_Box_Folder_Id__c, Pipeline_Stage__c from Opportunity where id =: opportunityId];
        return opp;
    } 		
    
    public static List<Sub_Folder__c> getChildFolders(String OppId){
        List<Sub_Folder__c> ChList = new List<Sub_Folder__c>();
        if(OppId!=null && OppId!='')
        {
            for(Sub_Folder__c CF : [select Id, Name, CF_Box_Folder_Id__c from Sub_Folder__c where CF_Deal__c =: OppId order by createdDate asc]){
                ChList.add(CF);
            }
        }
        return ChList;
    }
    
    
    public static List<Collaboration__c> getCollobration(String OppBoxUserId, string FolderId){
      List<Collaboration__c>CollList = new List<Collaboration__c>();
      for(Collaboration__c col:[Select id,BoxCollaboration_Id__c from Collaboration__c where BoxUser_Id__c =:OppBoxUserId and BoxFolder_Id__c =:FolderId]){
           CollList.add(col); 
        }
      return CollList; 
     }
                
    //************************************** This Method for Deal Attachment to Box***************************************************
    public static List<Sub_Folder__c > getsubfolder(String folderIds, String objectName){
      List<Sub_Folder__c>foldList = new List<Sub_Folder__c >();
      if(objectName == 'Deal__c' && folderIds!=null){           // Opportunity
        system.debug('soql controller-----61 Line------------'+objectName) ;
         for(Sub_Folder__c fol:[Select id,Name,CF_Box_Folder_Id__c,CF_Deal__c from Sub_Folder__c where CF_Deal__c =:folderIds and name=:'Sales']){
           foldList.add(fol);                   
        }
      }
      else if(objectName == 'Attachment__c' && folderIds!=null){
         Attachment__c cAttach = [select project__r.Deal__c from Attachment__c where id =: folderIds];
         for(Sub_Folder__c fol:[Select id,Name,CF_Box_Folder_Id__c,CF_Deal__c from Sub_Folder__c where CF_Deal__c =:cAttach.project__r.Deal__c and name=:'Funding-Vendor']){
           foldList.add(fol); 
        }
      }
      return foldList; 
     }      
     
     
    public static List<Attachment> getAttachment(String parId){
      List<Attachment>AttList = new List<Attachment>();
      for(Attachment fol:[Select id, Name, Body, parentId from Attachment where parentId =:parId]){
           AttList.add(fol); 
        }
      return AttList; 
     }     
     
    public static Sub_Folder__c getSubFolder(Id opportunityId, String subFolderName){
        Sub_Folder__c childFolder = [select id, CF_Box_Folder_Id__c from Sub_Folder__c where CF_Opportunity__c =: opportunityId and name =: subFolderName];
        return childFolder;
    } 

    public static List<dsfs__DocuSign_Status__c> getDocusignStatusList(Id opportunityId){
        List<dsfs__DocuSign_Status__c> docuSignStatusList = new List<dsfs__DocuSign_Status__c>();
        for(dsfs__DocuSign_Status__c docuSignStatus : [select id, dsfs__Subject__c from dsfs__DocuSign_Status__c where dsfs__Opportunity__c =: opportunityId]){
            docuSignStatusList.add(docuSignStatus);
        }
        return docuSignStatusList;
    } 

    public static dsfs__DocuSign_Status__c getDocusignStatus(Id docusignId){
        return [select id, dsfs__Subject__c, dsfs__Opportunity__c from dsfs__DocuSign_Status__c where id =: docusignId];
    } 

    public static List<Attachment__c> getCustomAttachmentsList(Id opportunityId){
        List<Attachment__c> customAttachmentList = new List<Attachment__c>();
        for(Attachment__c att : [select id, project__r.opportunity__c from attachment__c where project__r.opportunity__c =: opportunityId]){
            customAttachmentList.add(att);
        }
        return customAttachmentList;
    } 
    
    public static List<Attachment> getAttachmentListBySet(Set<Id> attIds){
        List<Attachment> attList = new List<Attachment>();
        if(attIds.size() > 0){
            attList = [Select id, Name, Body, parentId from Attachment where Id in: attIds];
        }
        return attList;
    }
   public static List<String> getContactList(Id contId){
     List<String> conList = new List<String>();
     if(contId!=null){
      for(Contact con:[Select id from Contact where AccountId=:contId]){
          conList.add(con.id);
        }
      } 
     return conList;
   
   }
  public static List<String>getAccountContList(List<String> aacIdlst){
    List<String> contList = new  List<String>();
    for(Contact cont:[Select id from Contact where AccountId in:aacIdlst]){
        contList.add(cont.id);
     }
    return contList;
  } 
 public static List<String> getUserList(List<String> ownIdlst){
   List<String> usList = new  List<String>();
    for(Box_User__c bxusr: [select BoxUser_Id__c from Box_User__c where SF_User_Id__c in:ownIdlst]){
        usList.add(bxusr.BoxUser_Id__c);
     }
    return usList;
 
  }  

}