posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Id__c</fullName>
        <label>Boxclient Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Secret__c</fullName>
        <label>Boxclient Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxrefresh_token__c</fullName>
        <label>Boxrefresh token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Group__c.object
<CustomObject>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Group</label>
    <nameField>
        <label>Box Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Log__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Box Log</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Box Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Profile__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_SubFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix SubFolder</label>
        <referenceTo>BoxAccessMatrix_SubFolder__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Profiles</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lookup_Field_Name__c</fullName>
        <label>Lookup Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Profile</label>
    <nameField>
        <label>BoxAccessMatrix Profiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Stage__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix Profile</label>
        <referenceTo>BoxAccessMatrix_Profile__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Stages</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box_Permission__c</fullName>
        <label>Box Permission</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previewer Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer Uploader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Stage</label>
    <nameField>
        <label>BoxAccessMatrix Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_SubFolder__c.object
<CustomObject>
    <fields>
        <fullName>SubFolder_Name__c</fullName>
        <label>SubFolder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix SubFolder</label>
    <nameField>
        <label>BoxAccessMatrix SubFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix SubFolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CloseDate__c</fullName>
        <label>CloseDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Concierge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Concierge</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ConciergeDeal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Pipeline_Stage__c</fullName>
        <formula>Opportunity__r.Pipeline_Stage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StageName__c</fullName>
        <label>StageName</label>
        <picklist>
            <picklistValues>
                <fullName>Schedule Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reschedule Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Input Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docusign Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docusign Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduct Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Submitted to DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Rejected by DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Contract Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Layout and Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Rejected by DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Rejected by UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Submitted to DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Submitted to UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Sunrun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Layout Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release to Installer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Not Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Layout Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Cancelled After Install Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed/Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Pipeline_Stage__c</fullName>
        <formula>Opportunity__r.Pipeline_Stage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Release</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Sub_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestCreateCollaborationStageChangeBatch.cls
@isTest
public class TestCreateCollaborationStageChangeBatch { 
    static testMethod void myUnitTest() {
         List<Sub_folder__c> subList = new List<Sub_folder__c>();
         
        RecordType rt = [Select id from RecordType where name='Subcontractor'];
        Account acc =new Account();
        acc.name = 'irfan khan';
        acc.RecordTypeId = rt.Id;
        upsert acc;
        
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='test2@test.com',AccountId=acc.id);
        upsert con;
        Set<String> emailSet = new Set<String>();
        emailSet.add(con.email);
        
        Deal__c opp = new Deal__c();
        //opp.name = 'Test opp';
        opp.Account__c = acc.id;
        opp.CloseDate__c = date.today();
        opp.stageName__c = 'Closed Won';
        upsert opp;
       
       Deal__c oppr =[Select id, Opp_Pipeline_Stage__c from Deal__c where stageName__c='Closed Won' and id=:opp.id];
        
      //  System.assert(false,[select id,stageName From Deal__c where id=:opp.id]);             
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        upsert testBox;
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Application';
        sf.cf_Deal__c = oppr.id;
        sf.cf_box_folder_id__c = '11446498';
        upsert sf;
        subList.add(sf);
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
        //System.assert(false,[Select id,CF_Box_Folder_Id__c,cf_Deal__r.stagename from Sub_Folder__c  where name=:'Funding-Vendor']);
        Profile prf= [select id,Name From Profile Where Name='System Administrator'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Application';
        bams.Name='Application';
        upsert bams;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='System Administrator';
       // bamp.Lookup_Field_Name__c='Concierge__c';
        upsert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=oppr.Opp_Pipeline_Stage__c;
        BAM.check__c=true;
        upsert BAM;
        
       
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        upsert bg;
        
        
        Project__c pj = new Project__c();
        pj.Name = 'old prj';
        pj.Deal__c = oppr.id;
        pj.Subcontractor__c = acc.id;
        insert pj;
        
        List<box_log__c> OppList = new List<box_log__c>();
        box_log__c bxerr = new box_log__c(Deal__c = opp.id,Status__c = 'Success',Sub_Folder__c = sf.id,Type__c ='Create Collaboration');
        insert  bxerr ; 
        OppList.add(bxerr); 
       
        List<Collaboration__c> lstclb = new List<Collaboration__c>();
        Collaboration__c clb = new Collaboration__c(BoxCollaboration_Id__c='123456',BoxFolder_Id__c=sf.cf_box_folder_id__c,BoxGroup_Id__c=bg.BoxGroup_Id__c,Sub_folder__c = sf.id,Role__c='Uploader');
        insert clb;
        lstclb.add(clb);
        
        CreateCollaborationOnStageChangeBatch bcb = new CreateCollaborationOnStageChangeBatch('Application','Closed Won','11446498');
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        bcb.CreateUserGroupCollaboration(subList,bg.BoxGroup_Id__c,'Uploader',prf.Id,lstclb,OppList);
        bcb.CreateLookupUserCollaboration(subList,prf.Id,emailSet,'Uploader',OppList,lstclb);
        bcb.CreatePrfLookupUserCollaboration(subList,emailSet,'Uploader',prf.Id,OppList,lstclb);
        Test.setMock(HttpCalloutMock.class, new TestFileUploadMock());
        bcb.execute(BC,subList);
        bcb.finish(BC);
        
        bcb.CreateUserGroupCollaboration(subList,bg.BoxGroup_Id__c,'Uploader',prf.Id,lstclb,OppList);
        bcb.CreateLookupUserCollaboration(subList,prf.Id,emailSet,'Uploader',OppList,lstclb);
        bcb.CreatePrfLookupUserCollaboration(subList,emailSet,'Uploader',prf.Id,OppList,lstclb);
        
        
        
    }
   static testMethod void myUnitTestNew() {
         List<Sub_folder__c> subList = new List<Sub_folder__c>();
        RecordType rt = [Select id from RecordType where name='Subcontractor'];
        Account acc =new Account();
        acc.name = 'irfan khan';
        acc.RecordTypeId = rt.Id;
        upsert acc;
        
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='test2@test.com',AccountId=acc.id);
        upsert con;
         Set<String> emailSet = new Set<String>();
        emailSet.add(con.email);
        
        Deal__c opp = new Deal__c();
        //opp.name = 'Test opp';
        opp.Account__c = acc.id;
        opp.CloseDate__c = date.today();
        opp.stageName__c = 'Closed Won';
        upsert opp;
       
       Deal__c oppr =[Select id, Opp_Pipeline_Stage__c from Deal__c where stageName__c='Closed Won' and id=:opp.id];
        
      //  System.assert(false,[select id,stageName From Deal__c where id=:opp.id]);             
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        upsert testBox;
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Sales';
        sf.cf_Deal__c = oppr.id;
        sf.cf_box_folder_id__c = '11446498';
        upsert sf;
        subList.add(sf);
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
        //System.assert(false,[Select id,CF_Box_Folder_Id__c,cf_Deal__r.stagename from Sub_Folder__c  where name=:'Funding-Vendor']);
        Profile prf= [select id,Name From Profile Where Name='Project Manager'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Sales';
        bams.Name='Sales';
        upsert bams;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c=prf.name;
       // bamp.Lookup_Field_Name__c='Concierge__c';
        upsert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=oppr.Opp_Pipeline_Stage__c;
        BAM.check__c=true;
        upsert BAM;
        
       
        
        
       
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        upsert bg;
        
        
        Project__c pj = new Project__c();
        pj.Name = 'old prj';
        pj.Deal__c = oppr.id;
        pj.Subcontractor__c = acc.id;
        insert pj;
        
       List<box_log__c> OppList = new List<box_log__c>();
        box_log__c bxerr = new box_log__c(Deal__c = opp.id,Status__c = 'Success',Sub_Folder__c = sf.id,Type__c ='Create Collaboration');
        insert  bxerr ; 
        OppList.add(bxerr); 
       
        List<Collaboration__c> lstclb = new List<Collaboration__c>();
        Collaboration__c clb = new Collaboration__c(BoxCollaboration_Id__c='123456',BoxFolder_Id__c='34567',BoxGroup_Id__c=bg.BoxGroup_Id__c,Role__c='Viewer');
        upsert clb;
        lstclb.add(clb);
        
        CreateCollaborationOnStageChangeBatch bcb = new CreateCollaborationOnStageChangeBatch('Sales','Closed Won','11446498');
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        bcb.CreateUserGroupCollaboration(subList,bg.BoxGroup_Id__c,'Uploader',prf.Id,lstclb,OppList);
        bcb.CreateLookupUserCollaboration(subList,prf.Id,emailSet,'Uploader',OppList,lstclb);
        bcb.CreatePrfLookupUserCollaboration(subList,emailSet,'Uploader',prf.Id,OppList,lstclb);
        Test.setMock(HttpCalloutMock.class, new TestFileUploadMock());
        bcb.execute(BC,subList);
        bcb.finish(BC);
        
        bcb.CreateUserGroupCollaboration(subList,bg.BoxGroup_Id__c,'Uploader',prf.Id,lstclb,OppList);
        bcb.CreateLookupUserCollaboration(subList,prf.Id,emailSet,'Uploader',OppList,lstclb);
        bcb.CreatePrfLookupUserCollaboration(subList,emailSet,'Uploader',prf.Id,OppList,lstclb);
        
        
        
    }  
    
   static testMethod void myUnitTest1() {
         List<Sub_folder__c> subList = new List<Sub_folder__c>();
        RecordType rt = [Select id from RecordType where name='Subcontractor'];
        Account acc =new Account();
        acc.name = 'irfan khan';
        acc.RecordTypeId = rt.Id;
        upsert acc;
        
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='test2@test.com',AccountId=acc.id);
        upsert con;
        
         Set<String> emailSet = new Set<String>();
        emailSet.add(con.email);
        
        Deal__c opp = new Deal__c();   
        //opp.name = 'Test opp';
        opp.Account__c = acc.id;
        opp.CloseDate__c = date.today();
        opp.stageName__c = 'Closed Won';
        upsert opp;
       	
       Deal__c oppr =[Select id, Opp_Pipeline_Stage__c from Deal__c where stageName__c='Closed Won' and id=:opp.id];
        
      //  System.assert(false,[select id,stageName From Deal__c where id=:opp.id]);             
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        upsert testBox;
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Application';
        sf.cf_Deal__c = oppr.id;
        sf.cf_box_folder_id__c = '11446498';
        upsert sf;
        subList.add(sf);
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
        //System.assert(false,[Select id,CF_Box_Folder_Id__c,cf_Deal__r.stagename from Sub_Folder__c  where name=:'Funding-Vendor']);
        Profile prf= [select id,Name From Profile Where Name='EE Partner User'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Application';
        bams.Name='Application';
        upsert bams;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='EE Partner User';
        bamp.Lookup_Field_Name__c='Subcontractor__c';
        upsert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=oppr.Opp_Pipeline_Stage__c;
        BAM.check__c=true;
        upsert BAM;
        
       
        
        
       
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        upsert bg;
        
        
        Project__c pj = new Project__c();
        pj.Name = 'old prj';
        pj.Deal__c = oppr.id;
        pj.Subcontractor__c = acc.id;
        insert pj;
        
        List<box_log__c> OppList = new List<box_log__c>();
        box_log__c bxerr = new box_log__c(Deal__c = opp.id,Status__c = 'Success',Sub_Folder__c = sf.id,Type__c ='Create Collaboration');
        insert  bxerr ; 
        OppList.add(bxerr);  
       
        List<Collaboration__c> lstclb = new List<Collaboration__c>();
        Collaboration__c clb = new Collaboration__c(BoxCollaboration_Id__c='123456',BoxFolder_Id__c='34567',BoxGroup_Id__c=bg.BoxGroup_Id__c,Role__c='Viewer');
        upsert clb;
        lstclb.add(clb);
        
        CreateCollaborationOnStageChangeBatch bcb = new CreateCollaborationOnStageChangeBatch('Application','Closed Won','11446498');
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        bcb.CreateUserGroupCollaboration(subList,bg.BoxGroup_Id__c,'Uploader',prf.Id,lstclb,OppList);
        bcb.CreateLookupUserCollaboration(subList,prf.Id,emailSet,'Uploader',OppList,lstclb);
        bcb.CreatePrfLookupUserCollaboration(subList,emailSet,'Uploader',prf.Id,OppList,lstclb);
        Test.setMock(HttpCalloutMock.class, new TestFileUploadMock());
        bcb.execute(BC,subList);
        bcb.finish(BC);
        bcb.CreateUserGroupCollaboration(subList,bg.BoxGroup_Id__c,'Uploader',prf.Id,lstclb,OppList);
        bcb.CreateLookupUserCollaboration(subList,prf.Id,emailSet,'Uploader',OppList,lstclb);
        bcb.CreatePrfLookupUserCollaboration(subList,emailSet,'Uploader',prf.Id,OppList,lstclb);
        
        
        
    }
    
    static testMethod void myUnitTest2() {
         List<Sub_folder__c> subList = new List<Sub_folder__c>();
        
        RecordType rt = [Select id from RecordType where name='Subcontractor'];
        Account acc =new Account();
        acc.name = 'irfan khan';
        acc.RecordTypeId = rt.Id;
        upsert acc;
        
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='test2@test.com',AccountId=acc.id);
        upsert con;
         Set<String> emailSet = new Set<String>();
        emailSet.add(con.email);
        
        Deal__c opp = new Deal__c();
        ///opp.name = 'Test opp';
        opp.Account__c = acc.id;
        opp.CloseDate__c = date.today();
        opp.stageName__c = 'Closed Won';
        upsert opp;
       
       Deal__c oppr =[Select id, Opp_Pipeline_Stage__c from Deal__c where stageName__c='Closed Won' and id=:opp.id];
        
      //  System.assert(false,[select id,stageName From Deal__c where id=:opp.id]);             
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        upsert testBox;   						
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Application';
        sf.cf_Deal__c = oppr.id;
        sf.cf_box_folder_id__c = '11446498';
        upsert sf;
        subList.add(sf);
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
        //System.assert(false,[Select id,CF_Box_Folder_Id__c,cf_Deal__r.stagename from Sub_Folder__c  where name=:'Funding-Vendor']);
        Profile prf= [select id,Name From Profile Where Name='EE Assessor'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Application';
        bams.Name='Application';
        upsert bams;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='EE Assessor';
        bamp.Lookup_Field_Name__c='EE_Assessor__c';
        upsert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=oppr.Opp_Pipeline_Stage__c;	
        BAM.check__c=true;
        upsert BAM;
        
       
        
        
       
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        upsert bg;
        
        
        String orgId = UserInfo.getOrganizationId(); 
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-',''); 
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000)); 
        String uniqueName = orgId + dateString + randomInt; 
         
        User u = new User(); 
        u.Username =  uniqueName + '@test' + orgId + '.org'; 
        u.ProfileId = prf.Id; 
        u.LastName = 'test'; 
        u.Alias = 'test1'; 
        u.Email =  uniqueName + '@test' + orgId + '.org'; 
        u.TimeZoneSidKey = 'America/Los_Angeles'; 
        u.localesidkey='en_US'; 
        u.emailencodingkey='UTF-8'; 
        u.languagelocalekey='en_US'; 
        insert u; 

        
        Project__c pj = new Project__c();
        pj.Name = 'old prj';
        pj.Deal__c = oppr.id;
        pj.EE_Assessor__c = u.id;
        insert pj;
        
        List<box_log__c> OppList = new List<box_log__c>();
        box_log__c bxerr = new box_log__c(Deal__c = opp.id,Status__c = 'Success',Sub_Folder__c = sf.id,Type__c ='Create Collaboration');
        insert  bxerr ; 
        OppList.add(bxerr);  
       
        List<Collaboration__c> lstclb = new List<Collaboration__c>();
        Collaboration__c clb = new Collaboration__c(BoxCollaboration_Id__c='123456',BoxFolder_Id__c='34567',BoxGroup_Id__c=bg.BoxGroup_Id__c,Role__c='Viewer');
        upsert clb;
        lstclb.add(clb);
        
        CreateCollaborationOnStageChangeBatch bcb = new CreateCollaborationOnStageChangeBatch('Application','Closed Won','11446498');
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        bcb.CreateUserGroupCollaboration(subList,bg.BoxGroup_Id__c,'Uploader',prf.Id,lstclb,OppList);
        bcb.CreateLookupUserCollaboration(subList,prf.Id,emailSet,'Uploader',OppList,lstclb);
        bcb.CreatePrfLookupUserCollaboration(subList,emailSet,'Uploader',prf.Id,OppList,lstclb);
        Test.setMock(HttpCalloutMock.class, new TestFileUploadMock4());
        bcb.execute(BC,subList);
        bcb.finish(BC);
        bcb.CreateUserGroupCollaboration(subList,bg.BoxGroup_Id__c,'Uploader',prf.Id,lstclb,OppList);
        bcb.CreateLookupUserCollaboration(subList,prf.Id,emailSet,'Uploader',OppList,lstclb);
        bcb.CreatePrfLookupUserCollaboration(subList,emailSet,'Uploader',prf.Id,OppList,lstclb);
        
        
        
    }
}