posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Id__c</fullName>
        <label>Boxclient Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Secret__c</fullName>
        <label>Boxclient Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxrefresh_token__c</fullName>
        <label>Boxrefresh token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Group__c.object
<CustomObject>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxGroup_Name__c</fullName>
        <label>BoxGroup Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Profile_Id__c</fullName>
        <label>SF Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Group</label>
    <nameField>
        <label>Box Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Profile__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_SubFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix SubFolder</label>
        <referenceTo>BoxAccessMatrix_SubFolder__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Profiles</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lookup_Field_Name__c</fullName>
        <label>Lookup Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Profile</label>
    <nameField>
        <label>BoxAccessMatrix Profiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Stage__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix Profile</label>
        <referenceTo>BoxAccessMatrix_Profile__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Stages</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box_Permission__c</fullName>
        <label>Box Permission</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previewer Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer Uploader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Stage</label>
    <nameField>
        <label>BoxAccessMatrix Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_SubFolder__c.object
<CustomObject>
    <fields>
        <fullName>SubFolder_Name__c</fullName>
        <label>SubFolder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix SubFolder</label>
    <nameField>
        <label>BoxAccessMatrix SubFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix SubFolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CloseDate__c</fullName>
        <label>CloseDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opp_Pipeline_Stage__c</fullName>
        <formula>Opportunity__r.Pipeline_Stage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StageName__c</fullName>
        <label>StageName</label>
        <picklist>
            <picklistValues>
                <fullName>Schedule Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reschedule Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Input Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docusign Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docusign Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduct Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Submitted to DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Rejected by DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Contract Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Layout and Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Rejected by DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Rejected by UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Submitted to DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Submitted to UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Sunrun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Layout Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release to Installer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Not Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Layout Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Cancelled After Install Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed/Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Existing Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Sub_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Trigger_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>User_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Setting</label>
</CustomObject>

posiGen_FullsendBox/src/classes/TestBoxlogsCollaborationBatch.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.  
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class TestBoxlogsCollaborationBatch { 

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        List<Sub_folder__c> subList = new List<Sub_folder__c>();
        
        Account acc =new Account();
        acc.name = 'irfan khan';
        upsert acc;
        
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='test2@test.com',AccountId=acc.id);
        upsert con;
        
        
         Profile profiles=[Select Id From Profile Where Name='System Administrator']; 
     
        String orgId = UserInfo.getOrganizationId(); 
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-',''); 
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000)); 
        String uniqueName = orgId + dateString + randomInt; 
        
        Trigger_Setting__c ts = new Trigger_Setting__c(User_Trigger__c =true);
        insert ts; 
         
        User u = new User(); 
        u.Username =  uniqueName + '@test' + orgId + '.org'; 
        u.ProfileId = profiles.Id; 
        u.LastName = 'test'; 
        u.Alias = 'test1'; 
        u.Email =  uniqueName + '@test' + orgId + '.org'; 
        u.TimeZoneSidKey = 'America/Los_Angeles'; 
        u.localesidkey='en_US'; 
        u.emailencodingkey='UTF-8'; 
        u.languagelocalekey='en_US'; 
        insert u; 
        
        List<String>lstemail= new List<String>();
        lstemail.add(u.email);
        Map<String,String>Usmap = new Map<String,String>();
        Usmap.put(u.email,u.profileId);
        
        
       
       Set<String> opset = new Set<String>();  
        Deal__c opp = new Deal__c();
        //opp.name = 'Test opp';
        opp.Account__c = acc.id;
        opp.CloseDate__c = date.today();
        opp.stageName__c = 'Closed Won';
        upsert opp;
        opset.add(opp.id);				
        
        Deal__c op =[Select id, Opp_Pipeline_Stage__c from Deal__c where stageName__c='Closed Won' and id=:opp.id];
        
        
      //  System.assert(false,[select id,stageName From Deal__c where id=:opp.id]);             
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        upsert testBox;
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Funding-Vendor';
        sf.cf_Deal__c = op.id;
        sf.cf_box_folder_id__c = '11446498';   			
        upsert sf;
       
        Sub_folder__c sflst =[Select id,cf_box_folder_id__c,cf_Deal__c,name, cf_Deal__r.Opp_Pipeline_Stage__c from Sub_folder__c where id=:sf.id];
        
        subList.add(sflst);
        Set<String> fldsubList = new Set<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
       
        Profile prf= [select id,Name From Profile Where Name='EE Partner User'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Funding-Vendor';
        bams.Name='Funding-Vendor';
        upsert bams;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='EE Partner User';
        bamp.Lookup_field_Name__c='Subcontractor__c';
        upsert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=op.Opp_Pipeline_Stage__c;			
        BAM.check__c=true;
        upsert BAM;
        
        BoxAccessMatrix_Stage__c BAMl = [Select BoxAccessMatrix_Profile__r.Profile_Id__c ,Box_Permission__c from BoxAccessMatrix_Stage__c  where id=:BAM.id];
        Map<String,String>promap = new Map<String,String>();
        promap.put(BAMl.BoxAccessMatrix_Profile__r.Profile_Id__c,BAMl.Box_Permission__c);
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        upsert bg;
        
        List<Box_error__c> OppList = new List<Box_error__c>();
        box_error__c bxerr = new box_error__c();
        bxerr.Deal__c = opp.id; 
        bxerr.name = '409'; 
        bxerr.Message__c = 'Attachment id-'; 
        bxerr.Body__c = '{"type":"error","status":409,"code":"item_name_in_use","context_info":{"conflicts":{"type":"folder","id":"5045260509","sequence_id":"0","etag":"0","name":"2796_9019apricotst_JamesTobias"}},"help_url":"http:developers.box.com","message":"Item with the same name already exists","request_id":"1145339348561cbaa279ec4"}';
        bxerr.Type__c = 'EE';
        bxerr.Status__c = 'Error';  
        OppList.add(bxerr); 
       
       List<Collaboration__c> lstclb = new List<Collaboration__c>();
        Collaboration__c clb = new Collaboration__c(BoxCollaboration_Id__c='123456',BoxFolder_Id__c='34567',BoxGroup_Id__c=bg.BoxGroup_Id__c,Role__c='Viewer');
        upsert clb;
        
        BoxlogsCollaborationBatch bcb = new BoxlogsCollaborationBatch('Sales',lstemail,fldsubList);
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestFileUploadMock());
        bcb.execute(bc,subList);
        BoxlogsCollaborationBatch.CreateLookupUserCollaboration(lstemail,sf,Usmap,promap,lstclb,OppList);
        Test.stopTest();         
  }
 }