posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <externalId>true</externalId>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxFolder_Id__c</fullName>
        <label>BoxFolder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxUser_Id__c</fullName>
        <label>BoxUser Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/BoxDeleteOpportunityCollaborationBatch.cls
public with sharing class BoxDeleteOpportunityCollaborationBatch implements Database.Batchable<Deal__c>,Database.AllowsCallouts, Database.Stateful{
    public List<Deal__c> opplist;    
    public List<Sub_Folder__c> subFolderList;
    public BoxDeleteOpportunityCollaborationBatch (List<Deal__c> opplist,List<Sub_folder__c>subFolderList){
        this.opplist=opplist;     
        this.subFolderList=subFolderList;    
    }
    public Iterable<Deal__c> start(Database.BatchableContext BC){
        return opplist;
    }
     
    public void execute(Database.BatchableContext BC, List<Deal__c> DealList){
        List<Box_Error__c> bxErrList = new List<Box_Error__c>();
        try{
            List<Collaboration__c> deleteCollaborationList = new List<Collaboration__c>();
          
            
            Set<Id> oppIds = new Set<Id>();
            for(Deal__c opp: DealList){
                oppIds.add(opp.id);
            }  
            system.debug('################################### oppIds size'+oppIds.size());
            system.debug('################################### oppIds'+oppIds);
            
            Set<String> subFolders = new Set<String>();
            for(Sub_Folder__c subFolder:subFolderList){
                subFolders.add(subFolder.CF_Box_Folder_Id__c);
            }
            system.debug('################################### subFolders size'+subFolders.size());
            system.debug('################################### subFolders'+subFolders);
            
            List<Collaboration__c> collaborations = new List<Collaboration__c>();
            for(Collaboration__c collab: [select id, BoxCollaboration_Id__c, BoxUser_Id__c from Collaboration__c where BoxFolder_Id__c in: subFolders]){
                    collaborations.add(collab);
               }
            system.debug('################################### collaborations size'+collaborations.size());
            system.debug('################################### collaborations'+collaborations);
            
            Box__c box = Box__c.getInstance();
            
            for(Collaboration__c collaboration: collaborations){
                
                HttpRequest req2 = new HttpRequest();
                req2.setEndpoint('https://api.box.com/2.0/collaborations/'+collaboration.BoxCollaboration_Id__c+'');
                req2.setMethod('DELETE');
                req2.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
                HTTPResponse res2 = new Http().send(req2);
                
                system.debug('##########################res2 status code'+res2.getStatusCode());
                if(res2.getStatusCode() == 204){
                    deleteCollaborationList.add(collaboration);
                }
                else{
                    Box_Error__c bxerr = new Box_Error__c();
                    bxerr.name = String.valueOf(res2.getStatusCode()); 
                    bxerr.Message__c = 'collaboration id: '+collaboration.id; 
                    bxerr.Body__c = res2.getBody();
                    
                    bxErrList.add(bxerr);
                }
            }
            delete deleteCollaborationList;
           } 
        catch(Exception e){          
            system.debug('###############################'+e.getMessage());
            Box_Error__c bxerr = new Box_Error__c();
            bxerr.name = 'delete Deal__c Exception'; 
            bxerr.Message__c = e.getMessage(); 
            bxerr.Body__c = e.getStackTraceString();
            
            bxErrList.add(bxerr);
        }
       insert bxErrList; 
     }
     
     public void finish(Database.BatchableContext BC){
        
        
     }
}