posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manual_Url__c</fullName>
        <label>Manual Url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <label>Opportunity Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Box_Errors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Dropbox_Files_in_Box__c.object
<CustomObject>
    <fields>
        <fullName>Box_Folder_Id__c</fullName>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Directory_Path__c</fullName>
        <label>Directory Path</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Folder_Name__c</fullName>
        <label>Folder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <label>Opportunity Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>done__c</fullName>
        <defaultValue>false</defaultValue>
        <label>done</label>
        <type>Checkbox</type>
    </fields>
    <label>Dropbox Files in Box</label>
    <nameField>
        <displayFormat>F-{00000}</displayFormat>
        <label>File Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dropbox Files in Box</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_ID__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/BoxDropboxUnmatchedFolderMigrationBatch.cls
public with sharing class BoxDropboxUnmatchedFolderMigrationBatch implements Database.Batchable<Sobject>,Database.AllowsCallouts, Database.Stateful{
	public String base_url = 'https://posigen.app.box.com/files/0/f/';
	public Integer record_count = 0; 
	public Integer record_count_stop = 0;
	
	public BoxDropboxUnmatchedFolderMigrationBatch(Integer record_count_stop){
		this.record_count_stop = record_count_stop;
	} 
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('select Id, directory_path__c, folder_name__c, box_folder_id__c, opportunity_id__c, type__c, done__c from Dropbox_Files_in_Box__c where opportunity_id__c = null and done__c = false');
    }
    
    public void execute(Database.BatchableContext BC, List<Dropbox_Files_in_Box__c> dropboxList){
       List<Box_Error__c> bxErrList = new List<Box_Error__c>();
       try{
       	
            List<Dropbox_Files_in_Box__c> updatedDropboxList = new List<Dropbox_Files_in_Box__c>();
            
            system.debug('##################################### dropboxList.size'+dropboxList.size());
            Box__c box = Box__c.getInstance();
            
            for(Dropbox_Files_in_Box__c dropBoxFile : dropboxList){
	            
                HttpRequest req = new HttpRequest();
                req.setEndpoint('https://api.box.com/2.0/folders/'+dropBoxFile.box_folder_id__c+'/copy');
                req.setMethod('POST');
                req.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
                req.setBody('{"parent": {"id" : 4408116546}}');
                
                Http http = new Http();
                HTTPResponse res = http.send(req);
                  if(res.getStatusCode() == 201){
                  	dropBoxFile.done__c = true;
                    updatedDropboxList.add(dropBoxFile);
                    
                    Box_Error__c bxerr = new Box_Error__c();
			   		bxerr.Opportunity__c = dropBoxFile.opportunity_id__c; 
			   		bxerr.name = String.valueOf(res.getStatusCode()); 
			   		bxerr.Message__c = 'opportunity id: '+dropBoxFile.opportunity_id__c+'--- folder id'+dropBoxFile.box_folder_id__c; 
			   		bxerr.Body__c = res.getBody();
			   		bxerr.Type__c = dropBoxFile.type__c;
			   		bxerr.Status__c = 'Success';
			   		FolderWrapper fw = (FolderWrapper)JSON.deserialize(res.getBody(),FolderWrapper.class);
			   		
					// constructing manual url
			   		String manual_url = base_url;
			   		manual_url += fw.id;
			   		manual_url += '/';
			   		
			   		String folder_name = fw.name;
			   		folder_name = folder_name.trim();
			   		folder_name = folder_name.replaceAll('(\\s+)', '_');
			   		folder_name = EncodingUtil.urlEncode(folder_name, 'UTF-8');
			   		
			   		manual_url += folder_name;
			   		bxerr.Manual_Url__c = manual_url;
			   		
			   		system.debug('######################################## manual_url'+ manual_url);
			   		
			   		bxErrList.add(bxerr);
                    
                  }
                  else{
                  	Box_Error__c bxerr = new Box_Error__c();
			   		bxerr.Opportunity__c = dropBoxFile.opportunity_id__c; 
			   		bxerr.name = String.valueOf(res.getStatusCode()); 
			   		bxerr.Message__c = 'opportunity id: '+dropBoxFile.opportunity_id__c+'--- folder id'+dropBoxFile.box_folder_id__c; 
			   		bxerr.Body__c = res.getBody();
			   		bxerr.Type__c = 'KDH Folder move';
			   		bxerr.Status__c = 'Error';
			   		
			   		bxErrList.add(bxerr);
                  }
            }
            
            update updatedDropboxList;
            insert bxErrList;
            
            record_count += dropboxList.size();
            if(record_count == record_count_stop){
		   		system.debug('######################################## job aborted record_count is'+ record_count);
		   		System.abortJob(BC.getJobId());
            }
    
        }
        catch(Exception e){
            System.debug(' ***Error '+e.getMessage());
          	Box_Error__c bxerr = new Box_Error__c();
	   		bxerr.name = 'Exception'; 
	   		bxerr.Message__c = e.getMessage(); 
	   		bxerr.Body__c = e.getStackTraceString();
	   		
	   		bxErrList.add(bxerr);
        }
    }
    
    
   public void finish(Database.BatchableContext BC){}
    
   public class FolderWrapper{
        public String Type;
        public String Id;
        public String Name;
    } 
}