posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Child_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestBoxRecoverRemainingFeedItems.cls
@isTest
public class TestBoxRecoverRemainingFeedItems{
    
     static testmethod void myTest() {
     
        Account acc =new Account();
        acc.name = 'irfan khan';
        insert acc;
        
                   
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Closed won';
        insert opp;
                    
        
        Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='sales');
        insert sc1;
                
        
        FeedItem  fdi = new FeedItem(ContentFileName='Testa.pdf', ContentData=Blob.valueOf('Test Data'), parentid=opp.id);
        insert fdi;
       
        
        FeedItem  fdi1 = new FeedItem(ContentFileName='Test1.pdf', ContentData=Blob.valueOf('Test1 Data'), parentid=opp.id);
        insert fdi1;
        
        List<FeedItem> feedItemList = new List<FeedItem>();
        feedItemList.add(fdi);
       
        
        Box_error__c bx = new Box_error__c();
        bx.name = '201';
        bx.message__c = 'Attachment id-'+fdi1.id;
        bx.type__c = 'Feed Item Standard';
        insert bx;
        
       Database.BatchableContext bc;
       BoxRecoverRemainingFeedItems bfb = new BoxRecoverRemainingFeedItems();
       
        bfb.start(bc);
       
       Test.startTest();
       bfb.execute(bc,feedItemList);
       bfb.finish(bc);
       Test.stopTest();
          

     }
}