posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Id__c</fullName>
        <label>Boxclient Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Secret__c</fullName>
        <label>Boxclient Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxrefresh_token__c</fullName>
        <label>Boxrefresh token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Child_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestBoxUploadFeedItems.cls
@isTest
public class TestBoxUploadFeedItems{
    
     static testmethod void myTest() {
     
        Account acc =new Account();
        acc.name = 'irfan khan';
        insert acc;
        //System.assert(acc.id!=null); 
                   
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Closed won';
        insert opp;
        //System.assert(opp.id!=null); 
        
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        insert testBox;
       // System.assert(testBox.id!=null);                   
        
        Sub_Folder__c sc1= new Sub_Folder__c(CF_Box_Folder_Id__c='890384',CF_Opportunity__c=opp.id,Name='sales');
        insert sc1;
       // system.assert(sc1.id!=null);           

        FeedItem  fdi = new FeedItem(ContentFileName='Test.pdf', ContentData=Blob.valueOf('Test Data'), parentid=opp.id);
        insert fdi;
       // system.assert(fdi.id!=null);
        
        FeedItem  fdi1 = new FeedItem(ContentFileName='Test1.pdf', ContentData=Blob.valueOf('Test1 Data'), parentid=opp.id);
        insert fdi1;
       // system.assert(fdi1.id!=null);
        
        Box_error__c bx = new Box_error__c();
        bx.name = '201';
        bx.message__c = 'Attachment id-'+fdi1.id;
        bx.type__c = 'Feed Item Standard';
        insert bx;
       
       // system.assert(bx.id!=null);
           BoxUploadFeedItems bfd = new BoxUploadFeedItems();
           BoxUploadFeedItems.uploadFeedItem();

     }
}