posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Existing Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/BoxUploadFeedItems.cls
public class BoxUploadFeedItems{

    public BoxUploadFeedItems(){
    
        
    }
    
    
    @future(callout=true)  
    public static void uploadFeedItem(){
          
         try{  
            Set<String> attchmentIdSet = new Set<String>();
            Set<String> attchmentIdList1 = new Set<String>();
            for(Box_Error__c bxer:[Select Deal__c ,name ,Type__c ,Status__c , Message__c from Box_Error__c where type__c like 'Feed%' and name = '201']){
                       
                    List<String> a1 = bxer.Message__c.split('-');
                    attchmentIdSet.add(a1[1]);
             }
             
               
               List<Box_Error__c> bxErrList = new List<Box_Error__c>(); 
               for(FeedItem att: [SELECT id, parentid FROM FeedItem WHERE id not in: attchmentIdSet]){
               
                   Schema.SObjectType sobjectType = att.ParentId.getSObjectType();
                     String sobjectName = sobjectType.getDescribe().getName();
               
                     if(sobjectName == 'Opportunity'){  
                         Box_Error__c bxerr = new Box_Error__c();
                         bxerr.Deal__c = att.parentId;
                         bxerr.name = '401';
                         bxerr.Message__c = 'Attachment id-'+att.id; 
                         bxerr.Body__c = '';
                         bxerr.Type__c = 'Feed Item Standard';
                         bxerr.Status__c = 'Error';
                   
                         bxErrList.add(bxerr);
                     }    
               }
               insert bxErrList;
     }

       catch(Exception e){
           system.assert(false,e.getMessage()+'--'+e.getStackTraceString());
       }
       
      
  }
}