posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Profile__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_SubFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix SubFolder</label>
        <referenceTo>BoxAccessMatrix_SubFolder__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Profiles</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lookup_Field_Name__c</fullName>
        <label>Lookup Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Profile</label>
    <nameField>
        <label>BoxAccessMatrix Profiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Stage__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix Profile</label>
        <referenceTo>BoxAccessMatrix_Profile__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Stages</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box_Permission__c</fullName>
        <label>Box Permission</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previewer Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer Uploader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Stage</label>
    <nameField>
        <label>BoxAccessMatrix Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_SubFolder__c.object
<CustomObject>
    <label>BoxAccessMatrix SubFolder</label>
    <nameField>
        <label>BoxAccessMatrix SubFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix SubFolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <externalId>true</externalId>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxFolder_Id__c</fullName>
        <label>BoxFolder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxUser_Id__c</fullName>
        <label>BoxUser Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFProfile_Id__c</fullName>
        <label>SFProfile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFUser_Email__c</fullName>
        <label>SFUser Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Pipeline_Stage__c</fullName>
        <formula>IF( AND(Permanent_Removal__c, NOT(ISNULL(R_P_Removal_Date__c))), &quot;Removed &amp; Terminated&quot;,
IF( Num_of_LD_Leases__c &gt; 0
	, &quot;Boarded&quot;,
    IF(TEXT( StageName ) = &quot;Closed Won&quot;,
		IF( OR( Lease_Boarding_Status__c = &quot;Upload to LD (based on CAO File)&quot;,Lease_Boarding_Status__c = &quot;Boarded&quot;, Has_Been_Boarded__c )
			, &quot;Boarded&quot;
			, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c)) &amp;&amp; NOT(ISNULL(EU_Completed_Date__c))
				, &quot;Need to Board&quot;
				, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Solar Panels&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Uptown Solar Lease&quot;)) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c))
					, &quot;Need to Board&quot;
					, IF( AND( NOT(ISNULL(PVI_Net_Meter_Install_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
						, &quot;Need to Board&quot;
						, IF(  AND(  NOT(ISNULL(PVI_Placed_In_Service_Date__c)), ISNULL(EU_Completed_Date__c), Has_EE_as_a_Solar_Product__c )
							, &quot;Pending EU&quot;
							, IF( AND( NOT(ISNULL(PVI_Placed_In_Service_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
								, &quot;Pending Net Meter&quot;
								, IF ( AND(ISNULL(PVI_Placed_In_Service_Date__c ), NOT(ISNULL(PVI_Rails_and_Panels_Left_WH_Date__c)))
									, &quot;PV System Left Warehouse&quot; 
									, TEXT( StageName )
								)
							)
						)
					)
				)
			)
        )
        ,TEXT( StageName )
	)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Child_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/Batch_UpdateEmailCollaboration.cls
public with sharing class Batch_UpdateEmailCollaboration implements Database.Batchable<Sobject>,Database.AllowsCallouts, Database.Stateful{
 
  public String base_url = 'https://app.box.com/files/0/f/';
  public List<BoxAccessMatrix_Stage__c> bxStageList;
  public String UserEmail;
  public String role;
  Box__c box ;
  List<Box_Error__c> bxErrList ;
  public Map<String,String> roleMap;
   
  public Batch_UpdateEmailCollaboration(List<BoxAccessMatrix_Stage__c> bxStageList,String UserEmail,String role){
    this.bxStageList =bxStageList;
    roleMap = new Map<String,String>();
    this.UserEmail = UserEmail;
    this.role = role;
  } 
  
  public Database.QueryLocator start(Database.BatchableContext BC){
        box = Box__c.getInstance();
        Set<String> stageSet = new Set<String>();
        Set<String> profileSet = new Set<String>();
        Set<String> NameSet = new Set<String>();
        Set<String> folderIdSet = new Set<String>();
        roleMap = new Map<String,String>(); 
        for(BoxAccessMatrix_Stage__c bstge:[select id, Box_Permission__c,BoxAccessMatrix_Profile__r.BoxAccessMatrix_SubFolder__r.SubFolder_Name__c,BoxAccessMatrix_Profile__r.Lookup_field_Name__c,BoxAccessMatrix_Profile__r.Profile_Name__c, BoxAccessMatrix_Profile__r.Profile_Id__c, Stage__c,check__c from BoxAccessMatrix_Stage__c where id in:bxStageList]){
            stageSet.add(bstge.Stage__c);
            profileSet.add(bstge.BoxAccessMatrix_Profile__r.Profile_Id__c);
            NameSet.add(bstge.BoxAccessMatrix_Profile__r.BoxAccessMatrix_SubFolder__r.SubFolder_Name__c);
            roleMap.put(bstge.BoxAccessMatrix_Profile__r.Profile_Id__c,bstge.Box_Permission__c);
            
         }
      for(Sub_folder__c sf:[Select id,CF_Box_Folder_Id__c,cf_opportunity__r.Pipeline_Stage__c from Sub_Folder__c where name in:NameSet and cf_opportunity__r.Pipeline_Stage__c in:stageSet]){
        
           folderIdSet.add(sf.CF_Box_Folder_Id__c);
         }   
  
        return Database.getQueryLocator('select BoxUser_Id__c,BoxFolder_Id__c ,role__c, SFProfile_Id__c, BoxCollaboration_Id__c from Collaboration__c  where BoxCollaboration_Id__c!= null and SFProfile_Id__c in:profileSet and BoxFolder_Id__c in:folderIdSet and SfUser_email__c=:UserEmail and role__c!=:role');
  }
  
  public void execute(Database.BatchableContext BC, List<Collaboration__c> collaborations){
     bxErrList = new List<Box_Error__c>();
        
     for(Collaboration__c clb :collaborations){
       system.debug('------'+roleMap.get(clb.SFProfile_Id__c)); 
        Batch_UpdateEmailCollaboration.updateCollaboration(clb,roleMap.get(clb.SFProfile_Id__c), box, bxErrList ); 
      } 
   
     update collaborations;
     insert bxErrList; 
          
  } 
  
  public void finish(Database.BatchableContext BC){
   
   
  
  }
  
  
  
   
   public static void updateCollaboration(Collaboration__c colb,String role,Box__c box,List<Box_Error__c> bxErrList){
     try{
        
            boolean isCallSuccess = true;

            
            HttpRequest req = new HttpRequest();
            req.setEndpoint('https://api.box.com/2.0/collaborations/'+colb.BoxCollaboration_Id__c);
            req.setMethod('PUT');
            req.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
            req.setBody('{"role": "'+role+'"}');
            HTTPResponse res = new Http().send(req);
            if(res.getStatuscode()==200){
                 colb.role__c = role;
               }
            else if(res.getStatusCode() == 401){
                BoxREFRESHAccessTokenScheduler.getToken();
             }
            else{
             Box_Error__c bxerr = new Box_Error__c();
             bxerr.name = ''+res.getStatusCode();
             bxerr.Message__c ='' ; 
             bxerr.Body__c = ''+res.getBody();
             bxerr.Type__c = 'Update Collaboration';
             bxerr.Status__c = 'Error';
             bxErrList.add(bxerr); 
            }    
           
        }
        catch(Exception e){
            Box_Error__c bxerr = new Box_Error__c();
             bxerr.name = 'Col Exception';
             bxerr.Message__c ='' ; 
             bxerr.Body__c = '';
             bxerr.Type__c = 'Collaboration';
             bxerr.Status__c = 'Error';
             bxErrList.add(bxerr); 
        }
        finally{
         
         
         }
   }  
  
      
   
 }