posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserEmail__c</fullName>
        <label>UserEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_SubFolder__c.object
<CustomObject>
    <fields>
        <fullName>SubFolder_Name__c</fullName>
        <label>SubFolder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix SubFolder</label>
    <nameField>
        <label>BoxAccessMatrix SubFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix SubFolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/boxLogClass.cls
public with sharing  class  boxLogClass {
   
   public boxLogClass(){}
   
   public void createUserCollaboratoion(List<Box_error__c> BoxLogList){
      List<String>emailList = new List<String>(); 
      Set<String>folderIdSet = new Set<String>();
      for(Box_error__c be:BoxLogList){
          emailList.add(be.Useremail__c);
          folderIdSet.add(be.Sub_folder__c);
      }
 
     
      for(BoxAccessMatrix_subfolder__c Bas:[Select Subfolder_Name__c from BoxAccessMatrix_subfolder__c]){
    
                  Database.executeBatch(new BoxlogsCollaborationBatch(Bas.Subfolder_Name__c,emailList,folderIdSet),1);
            }
                   
      
        }
   


}