posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Group__c.object
<CustomObject>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxGroup_Name__c</fullName>
        <label>BoxGroup Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Profile_Id__c</fullName>
        <label>SF Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Group</label>
    <nameField>
        <label>Box Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Log__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Box Log</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Box Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Lookup_Field_Name__c</fullName>
        <label>Lookup Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Profile</label>
    <nameField>
        <label>BoxAccessMatrix Profiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Stage__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix Profile</label>
        <referenceTo>BoxAccessMatrix_Profile__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Stages</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box_Permission__c</fullName>
        <label>Box Permission</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previewer Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer Uploader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Stage</label>
    <nameField>
        <label>BoxAccessMatrix Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <externalId>true</externalId>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxFolder_Id__c</fullName>
        <label>BoxFolder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxUser_Id__c</fullName>
        <label>BoxUser Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFProfile_Id__c</fullName>
        <label>SFProfile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFUser_Email__c</fullName>
        <label>SFUser Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Opp_Pipeline_Stage__c</fullName>
        <formula>Opportunity__r.Pipeline_Stage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pipeline_Stage__c</fullName>
        <label>Pipeline Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EE_Assessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This to for capturing the user that is doing the EE Assessment, whether they are Internal or External.</inlineHelpText>
        <label>EE Assessor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects_EE_Assessing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opp_Pipeline_Stage__c</fullName>
        <formula>Opportunity__r.Pipeline_Stage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opp Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Release</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subcontractor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subcontractor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Subcontractor, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Sub_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/BoxUpdateCollaborationBatch.cls
public with sharing class BoxUpdateCollaborationBatch implements Database.Batchable<Sobject>,Database.AllowsCallouts, Database.Stateful{
 
  public String base_url = 'https://app.box.com/files/0/f/';
  public Integer record_count = 0; 
  public Integer record_count_stop = 0;   
  public string  foldername ='';
  public BoxAccessMatrix_Stage__c bs;
   
  public BoxUpdateCollaborationBatch(String folderName,Integer record_count_stop, BoxAccessMatrix_Stage__c bs){
    this.record_count_stop = record_count_stop;
    this.foldername =foldername; 
    this.bs=bs;
    system.debug('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');  
  } 
  
  Map<string,string> Usermap;
  Map<string,List<string>> Contactmap;
  public Database.QueryLocator start(Database.BatchableContext BC){
     String pipeStage = bs.Stage__c;
     system.debug('======'+pipeStage);
      Usermap = new Map<string,string>();
      Contactmap = new Map<string,List<string>>(); 
     for(User u:[Select id ,email from user]){
          Usermap.put(u.id,u.email);
      } 
      
    for(Account acc:[Select id, (Select email from contacts where email!=null) from Account]){
        if(acc.contacts!=null){  
        for(Contact con :acc.contacts){
            
            if(!Contactmap.containsKey(acc.id)){
                Contactmap.put(acc.id, new List<string>());
            }
            Contactmap.get(acc.id).add(con.email);
          }
         }  
      
       } 
     
     return Database.getQueryLocator('Select id,CF_Box_Folder_Id__c,cf_Deal__r.Opp_Pipeline_Stage__c from Sub_Folder__c where name=:folderName and cf_Deal__r.Pipeline_Stage__c=:pipeStage');
  }			
  
   public void execute(Database.BatchableContext BC, List<Sub_Folder__c> fldList){
  
   List<Collaboration__c> lstcollab = new List<Collaboration__c>();
    List<Box_Log__c> bxErrList = new List<Box_Log__c>();     
    
    Map<String,String> profileGroupMap = new Map<String,String>();
  
    Map<String,List<String>> profileUserMap = new Map<String,List<String>>();
    profileUserMap.put(bs.BoxAccessMatrix_Profile__r.Profile_Id__c,new List<String>());
    for(Profile prf:[Select id,(Select id,email from users where isActive=true) from profile where id in:profileUserMap.keyset()]){
         
         for(User us: prf.Users){
               profileUserMap.get(prf.id).add(us.email);
             }
       }

    List<String> foldIdlst = new List<String>(); 
    Set<String> BoxfoldIdlst = new Set<String>(); 
    Map<String,Id> folderOppMap = new Map<String,Id>(); 
    Map<Id,Id> OppFolderMap = new Map<Id,Id>();
    Map<String,String> folderIdMap= new Map<String,String>();       
    for(Sub_Folder__c sb:fldList){
            foldIdlst.add(sb.CF_Box_Folder_Id__c);
            BoxfoldIdlst.add(sb.cf_Deal__c);
            folderIdMap.put(sb.cf_Deal__c,sb.CF_Box_Folder_Id__c); 
            folderOppMap.put(sb.CF_Box_Folder_Id__c,sb.cf_Deal__c);
            OppFolderMap.put(sb.cf_Deal__c,sb.id);
        }
   
    
    List<Collaboration__c > delclblst = new List<Collaboration__c >();
    for(Collaboration__c clb:[Select id,BoxCollaboration_Id__c,BoxFolder_Id__c,BoxGroup_Id__c,BoxUser_Id__c from Collaboration__c where BoxFolder_Id__c in:foldIdlst and SFprofile_Id__c=:bs.BoxAccessMatrix_Profile__r.Profile_Id__c]){
        
        if(clb.BoxCollaboration_Id__c!=null)
           delclblst.add(clb) ;
          
       }
    if(delclblst.size()>0 && bs.check__c==false){
      
         BoxUpdateCollaborationBatch.deletCollBatch(delclblst);
         
      }
    
    if(foldIdlst.size() > 0 && bs.check__c==true){
         for(Box_Group__c  bg : [Select SF_Profile_Id__c, BoxGroup_Id__c,BoxGroup_Name__c from Box_Group__c]){
             profileGroupMap.put(bg.SF_Profile_Id__c, bg.BoxGroup_Id__c);
         }
      if(bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c != null){
                 String query ;
                 String sObjName;
                 
                 String FolderIDstring; 
                 
                   integer i = 1;  
                   FolderIDstring = '(';
                   for(String str:BoxfoldIdlst){
                   
                       if(BoxfoldIdlst.size() == i){
                           FolderIDstring += '\''+str+'\'';
                       }
                       else{
                           FolderIDstring += '\''+str+'\',';
                       }
                       i++;
                    }
                   FolderIDstring += ')';
                 
                  system.debug('********'+FolderIDstring);  
                 
                 
                 if(bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c=='Subcontractor__c'||bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c=='EE_Assessor__c')
                   query = 'Select id, ownerId from Deal__c where id in '+FolderIDstring;
                 else{
                   query = 'Select '+bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c+' from Deal__c where id in '+FolderIDstring;
                   }			
                system.debug('======'+query);   									
              
              for(Deal__c opp : Database.query(query)){ 
                 
                 if(bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c=='Subcontractor__c'){
                    
                       String prjquery = 'Select '+ bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c+', RecordType.Name from project__c where  Deal__c=\''+opp.id+'\'';
                        system.debug('----'+prjquery);
                       for(Project__c prj:Database.query(prjquery)){
                          if(prj.get(bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c)!=null){ 
                               Id LookupPrjId = String.valueOf(prj.get(bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c));
                               string LookUpAccId = String.valueof(LookupPrjId);
                               
                            if((prj.RecordType.Name == 'EE Assessment'|| prj.RecordType.Name == 'EE Upgrade') && folderName == 'EE'){
                               for(String acSt:Contactmap.get(LookUpAccId)){
                                    if(acSt!=null)
                                       BoxUpdateCollaborationBatch.CreatePrfLookupUserCollaboration(OppFolderMap, opp.id,folderIdMap.get(opp.id),acSt,bs.Box_Permission__c,bs.BoxAccessMatrix_Profile__r.Profile_Id__c,lstcollab,bxErrList);
                                 }
                               }
                            if((prj.RecordType.Name != 'EE Assessment'&& prj.RecordType.Name != 'EE Upgrade') && folderName != 'EE'){
                               for(String acSt:Contactmap.get(LookUpAccId)){
                                    if(acSt!=null)
                                       BoxUpdateCollaborationBatch.CreatePrfLookupUserCollaboration(OppFolderMap, opp.id,folderIdMap.get(opp.id),acSt,bs.Box_Permission__c,bs.BoxAccessMatrix_Profile__r.Profile_Id__c,lstcollab,bxErrList);
                                 }
                               }     
                          } 
                       }
                     
                   }
               else if(bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c=='EE_Assessor__c'){
                    String prjquery = 'Select '+ bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c+' from project__c where Deal__c=\''+opp.id+'\'';
                    
                     for(Project__c prj:Database.query(prjquery)){
                           Id LookupPrjId = String.valueOf(prj.get(bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c)); 
                          
                            if(LookupPrjId!=null) 
                                 BoxUpdateCollaborationBatch.CreatePrfLookupUserCollaboration(OppFolderMap, opp.id,folderIdMap.get(opp.id),Usermap.get(LookupPrjId),bs.Box_Permission__c,bs.BoxAccessMatrix_Profile__r.Profile_Id__c,lstcollab,bxErrList);
                          }
                    }   
                else{			
                     if(opp.get(bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c)!=null && opp.ownerId == opp.get(bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c)){
                       Id LookupId = String.valueOf(opp.get(bs.BoxAccessMatrix_Profile__r.Lookup_Field_Name__c));
                       system.debug('#######'+LookupId);
                       string LookUpuserId = String.valueof(LookupId);
                       BoxUpdateCollaborationBatch.CreatePrfLookupUserCollaboration(OppFolderMap, opp.id,folderIdMap.get(opp.id),Usermap.get(LookUpuserId),bs.Box_Permission__c,bs.BoxAccessMatrix_Profile__r.Profile_Id__c,lstcollab,bxErrList);
                     }  
                       
                     }       
                  } 
             
                }
             else{
               if(bs.BoxAccessMatrix_Profile__r.Profile_Name__c=='Document Controller'||bs.BoxAccessMatrix_Profile__r.Profile_Name__c=='Concierge'||bs.BoxAccessMatrix_Profile__r.Profile_Name__c=='System Administrator '){
                   system.debug('&&&&&'+bs.BoxAccessMatrix_Profile__r.Profile_Name__c);
                  BoxUpdateCollaborationBatch.CreateUserGroupCollaboration(OppFolderMap, folderOppMap,foldIdlst,profileGroupMap.get(bs.BoxAccessMatrix_Profile__r.Profile_Id__c),bs.Box_Permission__c,bs.BoxAccessMatrix_Profile__r.Profile_Id__c,lstcollab,bxErrList); 
                  }
             else {
                    
                     for(String stEmail:profileUserMap.get(bs.BoxAccessMatrix_Profile__r.Profile_Id__c)){
                          system.debug('########################################'+ stEmail);
                          if(stEmail!=null)
                           BoxUpdateCollaborationBatch.CreateLookupUserCollaboration(OppFolderMap, folderOppMap,foldIdlst,stEmail,bs.Box_Permission__c,bs.BoxAccessMatrix_Profile__r.Profile_Id__c,lstcollab,bxErrList);   
                        
                        } 
                   
               
                 }                 
             }
             
         
         insert lstcollab;
         insert bxErrList; 
        
        }
       record_count += fldList.size();
      if(record_count == record_count_stop){
       system.debug('######################################## job aborted record_count is'+ record_count);
       System.abortJob(BC.getJobId());
       }     
    
          
  } 
  
  public void finish(Database.BatchableContext BC){
    
    List<Messaging.SingleEmailMessage> msgList = new List<Messaging.SingleEmailMessage>(); 
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    mail.setTargetObjectId(UserInfo.getUserId());  
    mail.setToAddresses(new String[]{UserInfo.getUserEmail()});
    mail.setSaveasactivity(false);
    mail.setSubject('Permission Batch Status');
    mail.setPlainTextBody('Permission batch Completed successfully for '+folderName+' folder at '+bs.stage__c+' pipeline Stage');
    msgList.add(mail);
    Messaging.sendEmail(msgList);
  
  
  }
  
  
     public static void CreatePrfLookupUserCollaboration(Map<Id,Id> OppFolderMap, Id oppid, string fId,String userEmail, String role,String ProfId,List<Collaboration__c> lstcollab,List<Box_Log__c> bxErrList){
        String status = '';
        try{

          system.debug(fId+'-------'+userEmail+'%%%%%%%'+role);
            if(fId!= null && userEmail!= null && role != null){
                Box__c box = Box__c.getInstance();
                HttpRequest req = new HttpRequest();
                req.setEndpoint('https://api.box.com/2.0/collaborations');
                req.setMethod('POST');
                req.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
                req.setBody('{"item": { "id": "'+fId+'", "type": "folder"}, "accessible_by": { "login": "'+userEmail+'", "type": "user" }, "role": "'+role+'"}');
                HTTPResponse res = new Http().send(req);
                // Collaboration__c clb; 
                CollaborationUserWrapper cuw = new CollaborationUserWrapper ();
                system.debug(res.getStatusCode()+'hiiiii'+res.getbody());
                if(res.getStatusCode() == 201){
                    cuw = (CollaborationUserWrapper)JSON.deserialize(res.getBody(),CollaborationUserWrapper.class);
                    Collaboration__c clb = new Collaboration__c();
                    if(cuw.accessibleby!=null){
                        clb.BoxCollaboration_Id__c = cuw.Id;
                        clb.Role__c= cuw.role;
                        clb.BoxFolder_Id__c= fId;
                        clb.BoxUser_Id__c=cuw.accessibleby.id;
                       }
                    else{
                        clb.BoxCollaboration_Id__c = cuw.id;
                        clb.Role__c= cuw.role;
                        clb.BoxFolder_Id__c= fId;
                        clb.BoxUser_Id__c='';
                       } 
                    clb.SFUser_Email__c = userEmail;
                    clb.SFProfile_Id__c = ProfId;
                    clb.sub_folder__c = OppFolderMap.get(oppid);
                    lstcollab.add(clb);
                    
                    status = 'Success';
                } 
                else{
                     status = 'Error';  
                }
                BoxLogs.createLogs('BoxUpdateCollaborationBatch-CreatePrfLookupUserCollaborationPrj',oppid, null, res.getBody(), 'Create Collaboration' , status, res.getStatusCode()+'', userEmail, role, bxErrList);
            }
            
        }
        catch(Exception e){
             status = 'Exception';
             BoxLogs.createLogs('BoxUpdateCollaborationBatch-CreateUserGroupCollaboration',oppid, null, e.getMessage() +'#' +e.getStacktraceString(), 'Create Collaboration' , status, '', userEmail, role, bxErrList);

        }
        finally{
         
         
         }
   } 
  
  public static void deletCollBatch(List<Collaboration__c> deletecollList){
       
       try{
         
            List<Collaboration__c> updatedcollList = new List<Collaboration__c>();
            
            system.debug('##################################### collList.size'+deletecollList.size());
            
            
            
            Collaboration__c colFile;
            system.debug('======='+deletecollList.size());
            for(integer i=0; i<deletecollList.size(); i++){
                  
                colFile  = deletecollList[i];
            
                Box__c bx = Box__c.getInstance();
                HttpRequest req = new HttpRequest();
                req.setEndpoint('https://api.box.com/2.0/collaborations/'+colFile.BoxCollaboration_Id__c);
                req.setMethod('DELETE');
                req.setHeader('Authorization','Bearer '+bx.BoxAccess_Token__c);
                
                Http http = new Http();
                HTTPResponse res = http.send(req);
                  if(res.getStatusCode() == 204){
                    // success
                     updatedcollList.add(colFile);
                    
                  }
                
                  else{
                     //error
                  }
            }
            
            delete updatedcollList;
    
        }
        catch(Exception e){
           // exception
        }
   }  
 
  public static void CreateUserGroupCollaboration(Map<Id,Id> OppFolderMap, Map<String,Id> folderOppMap,List<String>fIdlst,String groupId, String role,String ProfId,List<Collaboration__c> lstcollab,List<Box_Log__c> bxErrList){
           
        String status = '';   

        boolean isCallSuccess = true;
        Integer lastIndex = -1;
        String collfld;
        
         for(integer i=0; i<fIdlst.size(); i++){
             
                   if(!isCallSuccess)
                       i = lastIndex; 
                lastIndex = i;
                collfld = fIdlst[i];
               system.debug('======='+collfld);
                if(collfld!= null && groupId!= null && role != null){
                Id oppid = folderOppMap.get(collfld);
                try{
                    
                    
                    Box__c box = Box__c.getInstance();
                    HttpRequest req = new HttpRequest();
                    req.setEndpoint('https://api.box.com/2.0/collaborations');
                    req.setMethod('POST');
                    req.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
                    req.setBody('{"item": { "id": "'+collfld+'", "type": "folder"}, "accessible_by": { "id": "'+groupId+'", "type": "group" }, "role": "'+role+'"}');
                    HTTPResponse res = new Http().send(req);
                    // Collaboration__c clb; 
                    Collaborationwrapper cw = new Collaborationwrapper();
                    system.debug(res.getStatusCode()+'hiiiii'+res.getbody());
                    if(res.getStatusCode() == 201){
                        cw = (Collaborationwrapper)JSON.deserialize(res.getBody(),Collaborationwrapper.class);
                        Collaboration__c clb = new Collaboration__c();
                        clb.BoxCollaboration_Id__c = cw.Id;
                        clb.Role__c= cw.role;
                        clb.BoxFolder_Id__c= collfld;
                        clb.BoxGroup_Id__c=groupId;
                        clb.SFUser_Email__c = 'group@test.com';
                        clb.SFProfile_Id__c = ProfId;
                        clb.sub_folder__c = OppFolderMap.get(oppid);
                        lstcollab.add(clb);
                        status = 'Success';
                     }
                    else{
                         
                        status = 'Error';
                    }
                    BoxLogs.createLogs('BoxUpdateCollaborationBatch-CreateUserGroupCollaboration',oppid, null, res.getBody(), 'Create Collaboration' , status, res.getStatusCode()+'', '', role, bxErrList);
                    }
                    catch(Exception e){
                        status = 'Exception';
                        BoxLogs.createLogs('BoxUpdateCollaborationBatch-CreateUserGroupCollaboration',oppid, null, e.getMessage() +'#' +e.getStacktraceString(), 'Create Collaboration' , status, '', '', role, bxErrList);
                          
                    }
                    finally{
                     
                     
                     }    
                }
            
          }  
        
   }  
   
   public static void CreateLookupUserCollaboration(Map<Id,Id> OppFolderMap, Map<String,Id> folderOppMap,List<String>fIdlst,String userEmail, String role,String ProfId,List<Collaboration__c> lstcollab,List<Box_Log__c> bxErrList){
           
        String status = '';   
        
        
        boolean isCallSuccess = true;
        Integer lastIndex = -1;
        String  collfld;
        
        system.debug('======='+fIdlst+'hii'+userEmail+'ggggg'+role);
        for(integer i=0; i<fIdlst.size(); i++){
               if(!isCallSuccess)
                i = lastIndex; 
            lastIndex = i;
            collfld = fIdlst[i];
        
            if(collfld!= null && userEmail!= null && role != null){
            Id oppid = folderOppMap.get(collfld);
            try{
                Box__c box = Box__c.getInstance();
                HttpRequest req = new HttpRequest();
                req.setEndpoint('https://api.box.com/2.0/collaborations');
                req.setMethod('POST');
                req.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
                req.setBody('{"item": { "id": "'+collfld+'", "type": "folder"}, "accessible_by": { "login": "'+userEmail+'", "type": "user" }, "role": "'+role+'"}');
                system.debug('sanjay--------'+req);         
                HTTPResponse res = new Http().send(req);
                // Collaboration__c clb; 
                CollaborationUserWrapper cuw = new CollaborationUserWrapper ();
                system.debug(res.getStatusCode()+'hiiiii'+res.getbody());
                if(res.getStatusCode() == 201){
                    cuw = (CollaborationUserWrapper)JSON.deserialize(res.getBody(),CollaborationUserWrapper.class);
                    Collaboration__c clb = new Collaboration__c();
                    if(cuw.accessibleby!=null){
                        clb.BoxCollaboration_Id__c = cuw.Id;
                        clb.Role__c= cuw.role;
                        clb.BoxFolder_Id__c= collfld;
                        clb.BoxUser_Id__c=cuw.accessibleby.id;
                       }
                    else{
                        clb.BoxCollaboration_Id__c = cuw.id;
                        clb.Role__c= cuw.role;
                        clb.BoxFolder_Id__c= collfld;
                        clb.BoxUser_Id__c='';
                       } 
                    clb.SFUser_Email__c = userEmail;
                    clb.SFProfile_Id__c = ProfId; 
                    clb.sub_folder__c = OppFolderMap.get(oppid);
                    lstcollab.add(clb);
                    status = 'Success';
                } 
                else{
                     status = 'Error';
                    
                }
                BoxLogs.createLogs('BoxUpdateCollaborationBatch-CreateLookupUserCollaboration',oppid, null, res.getBody(), 'Create Collaboration' , status, res.getStatusCode()+'', userEmail, role, bxErrList);
                }
                catch(Exception e){
                    status = 'Exception';
                    BoxLogs.createLogs('BoxUpdateCollaborationBatch-CreateLookupUserCollaboration',oppid, null, e.getMessage() +'#' +e.getStacktraceString(), 'Create Collaboration' , status, '', userEmail, role, bxErrList);
        
        
                }
                finally{
                 
                 
                 }
            }
          }  
        
   } 

   
      
    
    
    public class CollaborationWrapper {
    
        public String type;
        public String id;
        public Accessible_by accessible_by;
        public String role;
        public String acknowledged_at;
    }
    
    public class Accessible_by {
        public String type;
        public String id;
        public String name;
    }
    
        
    public class CollaborationUserWrapper {
        public String id;
        public cls_accessible_by accessibleby;
        public String role; 
    }
       
        
    public class cls_accessible_by {
        public String type; 
        public String id;   
        public String name; 
        public String login;   
    } 
    
    public void testMethod3() {
    List<Account> lstAccount = new List<Account>();
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
        lstAccount.add(new Account(name ='test'));
    }
}