posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Log__c.object
<CustomObject>
    <fields>
        <fullName>Collaboration_Role__c</fullName>
        <label>Collaboration Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exception</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Log</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Box Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <externalId>true</externalId>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxFolder_Id__c</fullName>
        <label>BoxFolder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxUser_Id__c</fullName>
        <label>BoxUser Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFUser_Email__c</fullName>
        <label>SFUser Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Existing Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/Batch_BoxCreateCollaborationsFrom.cls
public with sharing class Batch_BoxCreateCollaborationsFrom implements Database.Batchable<Sobject>,Database.AllowsCallouts, Database.Stateful{
    
    public Batch_BoxCreateCollaborationsFrom(){		
        
    }   
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        
        Datetime dt = System.now()-1;
        return Database.getQueryLocator('select id, Error_Code__c, Deal__c, Sub_Folder__c,collaboration_role__c,email__c,Sub_Folder__r.CF_Box_Folder_Id__c, type__c,Status__c from Box_Log__c where Status__c != \'Success\' and Error_Code__c != \'404\' and Error_Code__c != \'400\' and Error_Code__c != \'409\' and Error_Code__c != \'201\' and createdDate >:dt');
    }
    
    public void execute(Database.BatchableContext BC,List<Box_Log__c> NewlstBoxLogs){
           
            List<Collaboration__c> createListCollaborations = new List<Collaboration__c>();
            Set<String> deleteListCollaborations = new Set<String>();
            List<Box_Log__c> lstBoxLogs = new List<Box_Log__c>();
            List<Box_Log__c> deleteListBoxLogs = new List<Box_Log__c>();
            
            for(Box_Log__c log :NewlstBoxLogs){
                if(log.type__c == 'Create Collaboration'){
                    Batch_BoxCreateCollaborationsFrom.createCollaborationForUser('', log, log.collaboration_role__c,log.Sub_Folder__c, log.email__c ,log.Deal__c, log.Sub_Folder__r.CF_Box_Folder_Id__c, lstBoxLogs, createListCollaborations, deleteListBoxLogs);
                }
                else if(log.type__c == 'Delete Collaboration'){
                    Batch_BoxCreateCollaborationsFrom.deleteCollaboration('', log, log.Deal__c, log.Sub_Folder__c, log.email__c, lstBoxLogs, deleteListCollaborations, deleteListBoxLogs);
                }
            }  
        
            system.debug('---createListCollaborations--- size='+createListCollaborations.size()+'----------- list='+createListCollaborations);
            if(createListCollaborations.size()>0){
                insert createListCollaborations;
            }
            
            system.debug('---deleteListCollaborations--- size='+deleteListCollaborations.size()+'----------- list='+deleteListCollaborations);
            
            if(deleteListCollaborations.size()>0){
                
                List<collaboration__c> clbList = new List<collaboration__c>();
                for(collaboration__c clb: [select id from collaboration__c where id in:deleteListCollaborations ]){
                    clbList.add(clb);
                }
                
                delete clbList;
            }
            
            system.debug('---lstBoxLogs--- size='+lstBoxLogs.size()+'----------- list='+lstBoxLogs);
            if(lstBoxLogs.size()>0){
                upsert lstBoxLogs;
            }
            
            system.debug('---deleteListBoxLogs--- size='+deleteListBoxLogs.size()+'----------- list='+deleteListBoxLogs);
            if(deleteListBoxLogs.size()>0){
                delete deleteListBoxLogs;
            } 
        
    } 
    
    public void finish(Database.BatchableContext BC){
        
        
    }
    
    
    
    
    public static void createCollaborationForUser(String reference, Box_Log__c bxLog, String role,String folderId, String email ,String oppId, String subFolderId, List<Box_Log__c> lstBoxLogs, List<Collaboration__c> createListCollaborations, List<Box_Log__c> deleteListBoxLogs) {
        
        system.debug('------------------createCollaborationForUser------------------');
        string status ='';
        try {
            if(folderId != null && email!= null && role != null){
                
                Box__c box = Box__c.getInstance();
                HttpRequest req = new HttpRequest();
                req.setEndpoint('https://api.box.com/2.0/collaborations');
                req.setMethod('POST');
                req.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
                req.setBody('{"item": { "id": "'+subFolderId+'", "type": "folder"}, "accessible_by": { "login": "'+email+'", "type": "user" }, "role": "'+role+'"}');
                HTTPResponse res = new Http().send(req);
                
                system.debug('{"item": { "id": "'+subFolderId+'", "type": "folder"}, "accessible_by": { "login": "'+email+'", "type": "user" }, "role": "'+role+'"}');
                
                if(res!=null){                   
                    Collaborationwrapper cw = new Collaborationwrapper();
                    if(res.getStatusCode() == 201){
                        cw = (Collaborationwrapper)JSON.deserialize(res.getBody(),Collaborationwrapper.class);
                        Collaboration__c clb = new Collaboration__c();
                        
                        
                        if(cw.accessible_by!=null){
                            clb.BoxUser_Id__c=cw.accessible_by.id;
                        }
                        else{
                            clb.BoxUser_Id__c='';
                        } 
                        clb.BoxCollaboration_Id__c = cw.id;
                        clb.Role__c= cw.role;
                        clb.BoxFolder_Id__c=subFolderId ;
                        clb.sub_folder__c=folderId;
                        clb.SFUser_Email__c =email;
                        clb.id = null;
                        createListCollaborations.add(clb);
                        deleteListBoxLogs.add(bxLog);
                        status  = 'Success';
                        //clonedEmails.remove(conEmail);
                    }
                    /*else if(res.getStatusCode() == 401){
                        
                        createCollaboration(reference, ProfId,role,folderId,clonedEmails,oppId,subFolderId,lstBoxLogs,lstCollaborations);
                        status  ='Error';
                    } */
                    else{
                        status  ='Error';
                        //clonedEmails.remove(conEmail);
                    }
                    BoxLogs.createLogs(reference,oppId, folderId, res.getBody(), BoxLogs.CREATE_COLLABORATION, status  , res.getStatusCode()+'', email, role, lstBoxLogs);
                    
                }
                else{
                    status  = 'Error';
                    BoxLogs.createLogs(reference,oppId, folderId, 'Response is Null', BoxLogs.CREATE_COLLABORATION, status , '', email, role, lstBoxLogs);
                }
            }
            
        } 
        catch(Exception e){
            status  = 'Exception';
            BoxLogs.createLogs(reference,oppId, folderId, e.getMessage() +'#' +e.getStacktraceString(), BoxLogs.CREATE_COLLABORATION, status  , '', email, role, lstBoxLogs);
        }
    }
    
    public static void deleteCollaboration(String reference, Box_Log__c bxLog, String oppId, String subFolderId, String collaborationId, List<Box_Log__c> lstBoxLogs, Set<String> deleteListCollaborations, List<Box_Log__c> deleteListBoxLogs) {
        
        system.debug('------------------deleteCollaboration------------------');
        string status ='';
        
        try{
            
            if(collaborationId !=null){
                
                Box__c box = Box__c.getInstance();
                HttpRequest req2 = new HttpRequest();
                req2.setEndpoint('https://api.box.com/2.0/collaborations/'+collaborationId +'');
                req2.setMethod('DELETE');
                req2.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
                HTTPResponse res2 = new Http().send(req2);
                
                   system.debug('https://api.box.com/2.0/collaborations/'+collaborationId +'');
                   
                    DeleteCollaborationWrapper dcw = new DeleteCollaborationWrapper();
                    if (res2.getStatuscode() == 204) {
                        //success
                        status  = 'Success';
                        deleteListCollaborations.add(collaborationId);
                        deleteListBoxLogs.add(bxLog);
                        //clonedCollaboration.remove(clb);
                        
                    }
                    /*else if(res2.getStatusCode() == 401){ 
                        // token expired
                        status  = 'Error';
                        deleteCollaboration(reference, oppId, subFolderId, clonedCollaboration,lstBoxLogs, lstCollaborations);
                        
                    } */
                    else{ 
                        // other errors
                        status  = 'Error';
                        //clonedCollaboration.remove(clb);
                        
                    }
                    BoxLogs.createLogs(reference, oppId, subFolderId, res2.getBody(), BoxLogs.DELETE_COLLABORATION, status  , res2.getStatusCode()+'', collaborationId, '', lstBoxLogs);
                }
              
            
        }
        catch(Exception e){
            status  = 'Exception';
            BoxLogs.createLogs(reference, oppId, subFolderId, e.getMessage() +'#' +e.getStacktraceString(), BoxLogs.CREATE_COLLABORATION, status, '', collaborationId, '', lstBoxLogs);
        }
    }
    
    
    public class CollaborationWrapper {
        
        public String type;
        public String id;
        public Created_by created_by;
        public String created_at;
        public String modified_at;
        public String expires_at;
        public String status;
        public Created_by accessible_by;
        public String role;
        public String acknowledged_at;
        public Item item;
        
    }
    
    public class Created_by {
        public String type;
        public String id;
        public String name;
        public String login;
    }
    
    public class Item {
        public String type;
        public String id;
        public String sequence_id;
        public String etag;
        public String name;
    }
    
    public class DeleteCollaborationWrapper {
        
        public Integer total_count;
        public List<Entries> entries;
    }
    
    public class Entries {
        public String type;
        public String id;
        public String created_by;
        public String created_at;
        public String modified_at;
        public String expires_at;
        public String status;
        public String role;
        public String acknowledged_at;
        public Item item;
    }
    
    
    
}