posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Log__c.object
<CustomObject>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Box Log</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Box Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Profile__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_SubFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix SubFolder</label>
        <referenceTo>BoxAccessMatrix_SubFolder__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Profiles</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lookup_Field_Name__c</fullName>
        <label>Lookup Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Profile</label>
    <nameField>
        <label>BoxAccessMatrix Profiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Stage__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix Profile</label>
        <referenceTo>BoxAccessMatrix_Profile__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Stages</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box_Permission__c</fullName>
        <label>Box Permission</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previewer Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer Uploader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Stage</label>
    <nameField>
        <label>BoxAccessMatrix Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_SubFolder__c.object
<CustomObject>
    <label>BoxAccessMatrix SubFolder</label>
    <nameField>
        <label>BoxAccessMatrix SubFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix SubFolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <externalId>true</externalId>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxFolder_Id__c</fullName>
        <label>BoxFolder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxUser_Id__c</fullName>
        <label>BoxUser Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFProfile_Id__c</fullName>
        <label>SFProfile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Opp_Pipeline_Stage__c</fullName>
        <formula>Opportunity__r.Pipeline_Stage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Sub_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/Batch_UpdateCollaboration.cls
public with sharing class Batch_UpdateCollaboration implements Database.Batchable<Sobject>,Database.AllowsCallouts, Database.Stateful{
 
  public String base_url = 'https://app.box.com/files/0/f/';
  public List<BoxAccessMatrix_Stage__c> bxStageList;
  public Map<String,String> roleMap;      			
        
  public Batch_UpdateCollaboration(List<BoxAccessMatrix_Stage__c> bxStageList){
    this.bxStageList =bxStageList;
    roleMap = new Map<String,String>();
  } 
  
  public Database.QueryLocator start(Database.BatchableContext BC){
        
        Set<String> stageSet = new Set<String>();
        Set<String> profileSet = new Set<String>();
        Set<String> NameSet = new Set<String>();
        Set<String> folderIdSet = new Set<String>();
        roleMap = new Map<String,String>(); 
        for(BoxAccessMatrix_Stage__c bstge:[select id, Box_Permission__c,BoxAccessMatrix_Profile__r.BoxAccessMatrix_SubFolder__r.SubFolder_Name__c,BoxAccessMatrix_Profile__r.Lookup_field_Name__c,BoxAccessMatrix_Profile__r.Profile_Name__c, BoxAccessMatrix_Profile__r.Profile_Id__c, Stage__c,check__c from BoxAccessMatrix_Stage__c where id in:bxStageList]){
            stageSet.add(bstge.Stage__c);
            profileSet.add(bstge.BoxAccessMatrix_Profile__r.Profile_Id__c);
            NameSet.add(bstge.BoxAccessMatrix_Profile__r.BoxAccessMatrix_SubFolder__r.SubFolder_Name__c);
            roleMap.put(bstge.BoxAccessMatrix_Profile__r.Profile_Id__c,bstge.Box_Permission__c);
            
         }
      for(Sub_folder__c sf:[Select id,CF_Box_Folder_Id__c,cf_Deal__r.Opp_Pipeline_Stage__c from Sub_Folder__c where name in:NameSet and cf_Deal__r.Opp_Pipeline_Stage__c in:stageSet ]){
          
           folderIdSet.add(sf.CF_Box_Folder_Id__c);
         }   
      
        return Database.getQueryLocator('select sub_folder__r.cf_Deal__c, BoxUser_Id__c,BoxFolder_Id__c ,role__c, SFProfile_Id__c, BoxCollaboration_Id__c from Collaboration__c  where BoxCollaboration_Id__c!= null and SFProfile_Id__c in:profileSet and BoxFolder_Id__c in:folderIdSet');
  }
  
  public void execute(Database.BatchableContext BC, List<Collaboration__c> collaborations){
     List<Box_Log__c> bxErrList = new List<Box_Log__c>();
     List<Collaboration__c> updateCollaborationsList = new List<Collaboration__c>();
     
     Box__c  box = Box__c.getInstance();  
     for(Collaboration__c clb :collaborations){
        
        Batch_UpdateCollaboration.updateCollaboration(clb,roleMap.get(clb.SFProfile_Id__c), box, bxErrList, updateCollaborationsList  ); 
      } 
   
    
     insert bxErrList;
     update updateCollaborationsList; 
          
  } 
  
  public void finish(Database.BatchableContext BC){
   
    /*List<Messaging.SingleEmailMessage> msgList = new List<Messaging.SingleEmailMessage>(); 
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    mail.setTargetObjectId(UserInfo.getUserId());  
    mail.setToAddresses(new String[]{UserInfo.getUserEmail()});
    mail.setSaveasactivity(false);
    mail.setSubject('Update Collabration Batch Status');
    mail.setPlainTextBody('Update Permission Batch Completed successfully');
    msgList.add(mail);
    Messaging.sendEmail(msgList);*/
  
  }
  
  
  
   
   public static void updateCollaboration(Collaboration__c colb,String role,Box__c box,List<Box_Log__c> lstBoxLogs,List<Collaboration__c> updateCollaborationsList){
     try{
        
            boolean isCallSuccess = true;

            
            HttpRequest req = new HttpRequest();
            req.setEndpoint('https://api.box.com/2.0/collaborations/'+colb.BoxCollaboration_Id__c);
            req.setMethod('PUT');
            req.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
            req.setBody('{"role": "'+role+'"}');
            HTTPResponse res = new Http().send(req);
            if(res.getStatuscode()==200){
                
                 colb.role__c = role;
                 updateCollaborationsList.add(colb);
                 
                 BoxLogs.createLogs('Batch_UpdateCollaboration.updateCollaboration',colb.sub_folder__r.cf_Deal__c, colb.sub_folder__c, res.getBody(), 'Update Collaboration' , 'Success', res.getStatusCode()+'', '', role, lstBoxLogs);

               }
          else{
             
                BoxLogs.createLogs('Batch_UpdateCollaboration.updateCollaboration',colb.sub_folder__r.cf_Deal__c, colb.sub_folder__c, res.getBody(), 'Update Collaboration' , 'Error', res.getStatusCode()+'', '', role, lstBoxLogs);
             }     
           
        }
        catch(Exception e){
           
           BoxLogs.createLogs('Batch_UpdateCollaboration.updateCollaboration',colb.sub_folder__r.cf_Deal__c, colb.sub_folder__c, e.getMessage() +'#' +e.getStacktraceString(), 'Update Collaboration' , 'Exception', '', '', role, lstBoxLogs);
 
        }
        
   }  
  
      
   
 }