posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Id__c</fullName>
        <label>Boxclient Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxclient_Secret__c</fullName>
        <label>Boxclient Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Boxrefresh_token__c</fullName>
        <label>Boxrefresh token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Box_Errors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Group__c.object
<CustomObject>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxGroup_Name__c</fullName>
        <label>BoxGroup Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Profile_Id__c</fullName>
        <label>SF Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Group</label>
    <nameField>
        <label>Box Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Log__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Log</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Box Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Profile__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_SubFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix SubFolder</label>
        <referenceTo>BoxAccessMatrix_SubFolder__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Profiles</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lookup_Field_Name__c</fullName>
        <label>Lookup Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Profile</label>
    <nameField>
        <label>BoxAccessMatrix Profiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Stage__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix Profile</label>
        <referenceTo>BoxAccessMatrix_Profile__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Stages</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box_Permission__c</fullName>
        <label>Box Permission</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previewer Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer Uploader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Stage</label>
    <nameField>
        <label>BoxAccessMatrix Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_SubFolder__c.object
<CustomObject>
    <fields>
        <fullName>SubFolder_Name__c</fullName>
        <label>SubFolder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix SubFolder</label>
    <nameField>
        <label>BoxAccessMatrix SubFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix SubFolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Pipeline_Stage__c</fullName>
        <formula>IF( AND(Permanent_Removal__c, NOT(ISNULL(R_P_Removal_Date__c))), &quot;Removed &amp; Terminated&quot;,
IF( Num_of_LD_Leases__c &gt; 0
	, &quot;Boarded&quot;,
    IF(TEXT( StageName ) = &quot;Closed Won&quot;,
		IF( OR( Lease_Boarding_Status__c = &quot;Upload to LD (based on CAO File)&quot;,Lease_Boarding_Status__c = &quot;Boarded&quot;, Has_Been_Boarded__c )
			, &quot;Boarded&quot;
			, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c)) &amp;&amp; NOT(ISNULL(EU_Completed_Date__c))
				, &quot;Need to Board&quot;
				, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Solar Panels&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Uptown Solar Lease&quot;)) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c))
					, &quot;Need to Board&quot;
					, IF( AND( NOT(ISNULL(PVI_Net_Meter_Install_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
						, &quot;Need to Board&quot;
						, IF(  AND(  NOT(ISNULL(PVI_Placed_In_Service_Date__c)), ISNULL(EU_Completed_Date__c), Has_EE_as_a_Solar_Product__c )
							, &quot;Pending EU&quot;
							, IF( AND( NOT(ISNULL(PVI_Placed_In_Service_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
								, &quot;Pending Net Meter&quot;
								, IF ( AND(ISNULL(PVI_Placed_In_Service_Date__c ), NOT(ISNULL(PVI_Rails_and_Panels_Left_WH_Date__c)))
									, &quot;PV System Left Warehouse&quot; 
									, TEXT( StageName )
								)
							)
						)
					)
				)
			)
        )
        ,TEXT( StageName )
	)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Release</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subcontractor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subcontractor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Subcontractor, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Child_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestBoxRemainingCollaborationBatch.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class TestBoxRemainingCollaborationBatch { 

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        List<Sub_folder__c> subList = new List<Sub_folder__c>();
        List<Box_Log__c> boxLogsLst = new List<Box_Log__c>();  
        
        Account acc =new Account();
        acc.name = 'irfan khan';
        upsert acc;
        
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='test2@test.com',AccountId=acc.id);
        upsert con;      
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Closed Won';
        upsert opp;
        
        opportunity op =[Select id, Pipeline_stage__c from opportunity where stageName='Closed Won' and id=:opp.id];
        
        
      //  System.assert(false,[select id,stageName From opportunity where id=:opp.id]);             
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        upsert testBox;
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Funding-Vendor';
        sf.cf_opportunity__c = op.id;
        sf.cf_box_folder_id__c = '11446498';
        upsert sf;
       
        Sub_folder__c sflst =[Select id,cf_box_folder_id__c,cf_opportunity__c,name, cf_opportunity__r.Pipeline_stage__c from Sub_folder__c where id=:sf.id];
        
        subList.add(sflst);
        Set<String>subSet = new Set<String>();
        subSet.add(sf.cf_box_folder_id__c);
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
       
        Profile prf= [select id,Name From Profile Where Name='EE Partner User'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Funding-Vendor';
        bams.Name='Funding-Vendor';
        upsert bams;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='EE Partner User';
        bamp.Lookup_field_Name__c='Subcontractor__c';
        upsert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=op.Pipeline_stage__c;
        BAM.check__c=true;
        upsert BAM;
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        upsert bg;
        
        Project__c proj= new Project__c();
        proj.Opportunity__c = opp.id;
        insert proj;
         
        List<Box_error__c> OppList = new List<Box_error__c>();
        box_error__c bxerr = new box_error__c();
        bxerr.Opportunity__c = opp.id; 
        bxerr.name = '409'; 
        bxerr.Message__c = 'Attachment id-'; 
        bxerr.Body__c = '{"type":"error","status":409,"code":"item_name_in_use","context_info":{"conflicts":{"type":"folder","id":"5045260509","sequence_id":"0","etag":"0","name":"2796_9019apricotst_JamesTobias"}},"help_url":"http:developers.box.com","message":"Item with the same name already exists","request_id":"1145339348561cbaa279ec4"}';
        bxerr.Type__c = 'EE';
        bxerr.Status__c = 'Error';  
        OppList.add(bxerr); 
       
        List<Collaboration__c> lstclb = new List<Collaboration__c>();
        Collaboration__c clb = new Collaboration__c(BoxCollaboration_Id__c='123456',BoxFolder_Id__c='34567',BoxGroup_Id__c=bg.BoxGroup_Id__c,Role__c='Viewer');
        upsert clb;
        
        BoxRemainingInitialCollaborationBatch bcb = new BoxRemainingInitialCollaborationBatch('Funding-Vendor',10,subSet);
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestFileUploadMock());
        bcb.execute(bc,subList);
        BoxRemainingInitialCollaborationBatch.CreateUserGroupCollaboration(fldsubList,string.valueof(bg.id),'Viewer',bamp.Profile_Id__c,lstclb,OppList);
        BoxRemainingInitialCollaborationBatch.CreateLookupUserCollaboration(fldsubList,'test@appcino.com','Viewer',bamp.Profile_Id__c,lstclb,OppList);
        BoxRemainingInitialCollaborationBatch.CreatePrfLookupUserCollaboration(sf.cf_box_folder_id__c,'test1@appcino.com','Viewer',bamp.Profile_Id__c,lstclb,OppList);
        Test.stopTest();         
    }
    
    
    static testMethod void myUnitTest1() {
        // TO DO: implement unit test
        List<Sub_folder__c> subList = new List<Sub_folder__c>();
        Account acc =new Account();
        acc.name = 'irfan khan';
        upsert acc;
        
        Contact con = new Contact(FirstName='Test2',LastName='State1',email='test1@test.com',AccountId=acc.id);
        upsert con;
        
       
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Closed Won';
        upsert opp;
       
        opportunity op =[Select id, Pipeline_stage__c from opportunity where stageName='Closed Won' and id=:opp.id];
        
      //  System.assert(false,[select id,stageName From opportunity where id=:opp.id]);             
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        upsert testBox;
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Funding-Vendor';
        sf.cf_opportunity__c = op.id;
        sf.cf_box_folder_id__c = '11446498';
        upsert sf;
        Sub_folder__c sflst =[Select id,cf_box_folder_id__c,cf_opportunity__c,name, cf_opportunity__r.Pipeline_stage__c from Sub_folder__c where id=:sf.id];
        
        subList.add(sflst);
        Set<String>subSet = new Set<String>();
        subSet.add(sf.cf_box_folder_id__c);
        
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
        //System.assert(false,[Select id,CF_Box_Folder_Id__c,cf_opportunity__r.stagename from Sub_Folder__c  where name=:'Funding-Vendor']);
        Profile prf= [select id,Name From Profile Where Name='System Administrator'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Funding-Vendor';
        bams.Name='Funding-Vendor';
        upsert bams;
        
        Project__c proj= new Project__c();
        proj.Opportunity__c = opp.id;
        insert proj;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='System Administrator';
        //bamp.Lookup_field_Name__c='Concierge__c';
        upsert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=op.Pipeline_stage__c;
        BAM.check__c=true;
        upsert BAM;
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';      
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        upsert bg;
        
        List<Collaboration__c> lstclb = new List<Collaboration__c>();
        Collaboration__c clb = new Collaboration__c(BoxCollaboration_Id__c='123456',BoxFolder_Id__c='34567',BoxGroup_Id__c=bg.BoxGroup_Id__c,Role__c='Viewer');
        upsert clb;
        
        List<Box_error__c> OppList = new List<Box_error__c>();
        box_error__c bxerr = new box_error__c();
        bxerr.Opportunity__c = opp.id; 
        bxerr.name = '409'; 
        bxerr.Message__c = 'Attachment id-'; 
        bxerr.Body__c = '{"type":"error","status":409,"code":"item_name_in_use","context_info":{"conflicts":{"type":"folder","id":"5045260509","sequence_id":"0","etag":"0","name":"2796_9019apricotst_JamesTobias"}},"help_url":"http:developers.box.com","message":"Item with the same name already exists","request_id":"1145339348561cbaa279ec4"}';
        bxerr.Type__c = 'Funding-Vendor';
        bxerr.Status__c = 'Error';  
        OppList.add(bxerr); 
        
        
        
        BoxRemainingInitialCollaborationBatch bcb = new BoxRemainingInitialCollaborationBatch('Funding-Vendor',10,subSet);
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestFileUploadMock3());
        bcb.execute(bc,subList);
        BoxRemainingInitialCollaborationBatch.CreateUserGroupCollaboration(fldsubList,string.valueof(bg.id),'Viewer',bamp.Profile_Id__c,lstclb,OppList);
        BoxRemainingInitialCollaborationBatch.CreateLookupUserCollaboration(fldsubList,'test1@appcino.com','Viewer',bamp.Profile_Id__c,lstclb,OppList);
        BoxRemainingInitialCollaborationBatch.CreatePrfLookupUserCollaboration(sf.cf_box_folder_id__c,'test1@appcino.com','Viewer',bamp.Profile_Id__c,lstclb,OppList);
        Test.stopTest();         
    }
  
  static testMethod void myUnitTest2() {
        // TO DO: implement unit test
        List<Sub_folder__c> subList = new List<Sub_folder__c>();
        Account acc =new Account();
        acc.name = 'irfan khan';
        upsert acc;
        
        Contact con = new Contact(FirstName='Test2',LastName='State1',email='test1@test.com',AccountId=acc.id);
        upsert con;
        
       
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Closed Won';
        upsert opp;
       
        opportunity op =[Select id, Pipeline_stage__c from opportunity where stageName='Closed Won' and id=:opp.id];
        
      //  System.assert(false,[select id,stageName From opportunity where id=:opp.id]);             
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        upsert testBox;
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Funding-Vendor';
        sf.cf_opportunity__c = op.id;
        sf.cf_box_folder_id__c = '11446498';
        upsert sf;
        Sub_folder__c sflst =[Select id,cf_box_folder_id__c,cf_opportunity__c,name, cf_opportunity__r.Pipeline_stage__c from Sub_folder__c where id=:sf.id];
        
        subList.add(sflst);
        Set<String>subSet = new Set<String>();
        subSet.add(sf.cf_box_folder_id__c);
        
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
        //System.assert(false,[Select id,CF_Box_Folder_Id__c,cf_opportunity__r.stagename from Sub_Folder__c  where name=:'Funding-Vendor']);
        Profile prf= [select id,Name From Profile Where Name='EE Assessor'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Funding-Vendor';
        bams.Name='Funding-Vendor';
        upsert bams;
        
        Project__c proj= new Project__c();
        proj.Opportunity__c = opp.id;
        insert proj;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='EE Assessor';
        bamp.Lookup_field_Name__c='EE_Assessor__c';
        upsert bamp;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=op.Pipeline_stage__c;
        BAM.check__c=true;
        upsert BAM;
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';      
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        upsert bg;
        
        List<Collaboration__c> lstclb = new List<Collaboration__c>();
        Collaboration__c clb = new Collaboration__c(BoxCollaboration_Id__c='123456',BoxFolder_Id__c='34567',BoxGroup_Id__c=bg.BoxGroup_Id__c,Role__c='Viewer');
        upsert clb;
        
        List<Box_error__c> OppList = new List<Box_error__c>();
        box_error__c bxerr = new box_error__c();
        bxerr.Opportunity__c = opp.id; 
        bxerr.name = '409'; 
        bxerr.Message__c = 'Attachment id-'; 
        bxerr.Body__c = '{"type":"error","status":409,"code":"item_name_in_use","context_info":{"conflicts":{"type":"folder","id":"5045260509","sequence_id":"0","etag":"0","name":"2796_9019apricotst_JamesTobias"}},"help_url":"http:developers.box.com","message":"Item with the same name already exists","request_id":"1145339348561cbaa279ec4"}';
        bxerr.Type__c = 'Funding-Vendor';
        bxerr.Status__c = 'Error';  
        OppList.add(bxerr); 
        
        
        
        BoxRemainingInitialCollaborationBatch bcb = new BoxRemainingInitialCollaborationBatch('Funding-Vendor',10,subSet);
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestFileUploadMock3());
        bcb.execute(bc,subList);
        BoxRemainingInitialCollaborationBatch.CreateUserGroupCollaboration(fldsubList,string.valueof(bg.id),'Viewer',bamp.Profile_Id__c,lstclb,OppList);
        BoxRemainingInitialCollaborationBatch.CreateLookupUserCollaboration(fldsubList,'test1@appcino.com','Viewer',bamp.Profile_Id__c,lstclb,OppList);
        BoxRemainingInitialCollaborationBatch.CreatePrfLookupUserCollaboration(sf.cf_box_folder_id__c,'test1@appcino.com','Viewer',bamp.Profile_Id__c,lstclb,OppList);
        Test.stopTest();         
    } 
   static testMethod void myUnitTest3() {
        // TO DO: implement unit test
        List<Sub_folder__c> subList = new List<Sub_folder__c>();
        
        Account acc =new Account();
        acc.name = 'irfan khan';
        upsert acc;
        
        Contact con = new Contact(FirstName='Test2',LastName='State1',email='test1@test.com',AccountId=acc.id);
        upsert con;
        
       
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Closed Won';
        upsert opp;
       
        opportunity op =[Select id, Pipeline_stage__c from opportunity where stageName='Closed Won' and id=:opp.id];
        
      //  System.assert(false,[select id,stageName From opportunity where id=:opp.id]);             
        Box__c testBox = new Box__c (BoxAccess_Token__c='sdgagfsgdgs2351254',Boxrefresh_token__c ='fbsdjjshvvjdfyugfdshag67324',Boxclient_Id__c ='12334asd',Boxclient_Secret__c='dsgzdfagadfh');
        upsert testBox;
        
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'Funding-Vendor';
        sf.cf_opportunity__c = op.id;
        sf.cf_box_folder_id__c = '11446498';
        upsert sf;
        Sub_folder__c sflst =[Select id,cf_box_folder_id__c,cf_opportunity__c,name, cf_opportunity__r.Pipeline_stage__c from Sub_folder__c where id=:sf.id];
        
        subList.add(sflst);
        Set<String>subSet = new Set<String>();
        subSet.add(sf.cf_box_folder_id__c);
        
        List<String> fldsubList = new List<String>();
        fldsubList.add(sf.cf_box_folder_id__c);
        //System.assert(false,[Select id,CF_Box_Folder_Id__c,cf_opportunity__r.stagename from Sub_Folder__c  where name=:'Funding-Vendor']);
        Profile prf= [select id,Name From Profile Where Name='Sales Manager'];
        
        BoxAccessMatrix_SubFolder__c bams = new BoxAccessMatrix_SubFolder__c();
        bams.SubFolder_Name__c='Funding-Vendor';
        bams.Name='Funding-Vendor';
        upsert bams;
        
        BoxAccessMatrix_Profile__c bamp = new BoxAccessMatrix_Profile__c();
        bamp.BoxAccessMatrix_SubFolder__c=bams.id;
        bamp.Profile_Id__c=prf.id;
        bamp.Profile_Name__c='Sales Manager';
       // bamp.Lookup_field_Name__c='EE_Assessor__c';
        upsert bamp;
        
        Project__c proj= new Project__c();
        proj.Opportunity__c = opp.id;
        insert proj;
        
        BoxAccessMatrix_Stage__c BAM = new BoxAccessMatrix_Stage__c();
        BAM.Box_Permission__c='Viewer';
        BAM.BoxAccessMatrix_Profile__c=bamp.id;
        BAM.Stage__c=op.Pipeline_stage__c;
        BAM.check__c=true;
        upsert BAM;
        
        Box_Group__c bg = new Box_Group__c();
        bg.BoxGroup_Id__c='34087847';      
        bg.BoxGroup_Name__c='test box grop';
        bg.SF_Profile_Id__c=prf.id;
        upsert bg;
        
        List<Collaboration__c> lstclb = new List<Collaboration__c>();
        Collaboration__c clb = new Collaboration__c(BoxCollaboration_Id__c='123456',BoxFolder_Id__c='34567',BoxGroup_Id__c=bg.BoxGroup_Id__c,Role__c='Viewer');
        upsert clb;
        
        List<Box_error__c> OppList = new List<Box_error__c>();
        box_error__c bxerr = new box_error__c();
        bxerr.Opportunity__c = opp.id; 
        bxerr.name = '409'; 
        bxerr.Message__c = 'Attachment id-'; 
        bxerr.Body__c = '{"type":"error","status":409,"code":"item_name_in_use","context_info":{"conflicts":{"type":"folder","id":"5045260509","sequence_id":"0","etag":"0","name":"2796_9019apricotst_JamesTobias"}},"help_url":"http:developers.box.com","message":"Item with the same name already exists","request_id":"1145339348561cbaa279ec4"}';
        bxerr.Type__c = 'Funding-Vendor';
        bxerr.Status__c = 'Error';  
        OppList.add(bxerr); 
        
        
        
        BoxRemainingInitialCollaborationBatch bcb = new BoxRemainingInitialCollaborationBatch('Funding-Vendor',10,subSet);
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new TestFileUploadMock3());
        bcb.execute(bc,subList);
        BoxRemainingInitialCollaborationBatch.CreateUserGroupCollaboration(fldsubList,string.valueof(bg.id),'Viewer',bamp.Profile_Id__c,lstclb,OppList);
        BoxRemainingInitialCollaborationBatch.CreateLookupUserCollaboration(fldsubList,'test1@appcino.com','Viewer',bamp.Profile_Id__c,lstclb,OppList);
        BoxRemainingInitialCollaborationBatch.CreatePrfLookupUserCollaboration(sf.cf_box_folder_id__c,'test1@appcino.com','Viewer',bamp.Profile_Id__c,lstclb,OppList);
        Test.stopTest();         
    }    
}