posiGen_FullsendBox/src/objects/Box__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>BoxAccess_Token__c</fullName>
        <label>BoxAccess Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box</label>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Error__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Box_Errors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Box Error Log</label>
    <nameField>
        <label>Error Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Group__c.object
<CustomObject>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxGroup_Name__c</fullName>
        <label>BoxGroup Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Profile_Id__c</fullName>
        <label>SF Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Box Group</label>
    <nameField>
        <label>Box Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Box Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Box_Log__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Box Logs</relationshipLabel>
        <relationshipName>Box_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Box Log</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Box Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Box Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Profile__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_SubFolder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix SubFolder</label>
        <referenceTo>BoxAccessMatrix_SubFolder__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Profiles</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lookup_Field_Name__c</fullName>
        <label>Lookup Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Profile</label>
    <nameField>
        <label>BoxAccessMatrix Profiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/BoxAccessMatrix_Stage__c.object
<CustomObject>
    <fields>
        <fullName>BoxAccessMatrix_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BoxAccessMatrix Profile</label>
        <referenceTo>BoxAccessMatrix_Profile__c</referenceTo>
        <relationshipLabel>BoxAccessMatrix Stages</relationshipLabel>
        <relationshipName>BoxAccessMatrix_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box_Permission__c</fullName>
        <label>Box Permission</label>
        <picklist>
            <picklistValues>
                <fullName>Co-owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previewer Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viewer Uploader</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Check__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix Stage</label>
    <nameField>
        <label>BoxAccessMatrix Stages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <externalId>true</externalId>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxFolder_Id__c</fullName>
        <label>BoxFolder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFProfile_Id__c</fullName>
        <label>SFProfile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFUser_Email__c</fullName>
        <label>SFUser Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>EE_Assessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EE Assessor Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_Assessor_For</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pipeline_Stage__c</fullName>
        <formula>IF( AND(Permanent_Removal__c, NOT(ISNULL(R_P_Removal_Date__c))), &quot;Removed &amp; Terminated&quot;,
IF( Num_of_LD_Leases__c &gt; 0
	, &quot;Boarded&quot;,
    IF(TEXT( StageName ) = &quot;Closed Won&quot;,
		IF( OR( Lease_Boarding_Status__c = &quot;Upload to LD (based on CAO File)&quot;,Lease_Boarding_Status__c = &quot;Boarded&quot;, Has_Been_Boarded__c )
			, &quot;Boarded&quot;
			, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c)) &amp;&amp; NOT(ISNULL(EU_Completed_Date__c))
				, &quot;Need to Board&quot;
				, IF( INCLUDES(Solar_Product__c,&quot;Solar Hot Water&quot;) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Energy Efficiency&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Solar Panels&quot;)) &amp;&amp; NOT(INCLUDES(Solar_Product__c,&quot;Uptown Solar Lease&quot;)) &amp;&amp; NOT(ISNULL(PVI_Placed_In_Service_Date__c))
					, &quot;Need to Board&quot;
					, IF( AND( NOT(ISNULL(PVI_Net_Meter_Install_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
						, &quot;Need to Board&quot;
						, IF(  AND(  NOT(ISNULL(PVI_Placed_In_Service_Date__c)), ISNULL(EU_Completed_Date__c), Has_EE_as_a_Solar_Product__c )
							, &quot;Pending EU&quot;
							, IF( AND( NOT(ISNULL(PVI_Placed_In_Service_Date__c )), OR( NOT(ISNULL(EU_Completed_Date__c)), NOT(Has_EE_as_a_Solar_Product__c) ) )
								, &quot;Pending Net Meter&quot;
								, IF ( AND(ISNULL(PVI_Placed_In_Service_Date__c ), NOT(ISNULL(PVI_Rails_and_Panels_Left_WH_Date__c)))
									, &quot;PV System Left Warehouse&quot; 
									, TEXT( StageName )
								)
							)
						)
					)
				)
			)
        )
        ,TEXT( StageName )
	)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pipeline Stage</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>EE_Assessor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This to for capturing the user that is doing the EE Assessment, whether they are Internal or External.</inlineHelpText>
        <label>EE Assessor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects_EE_Assessing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Release</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subcontractor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subcontractor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Subcontractor, Vendor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Child_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/BoxRemainingInitialCollaborationBatch.cls
public with sharing class BoxRemainingInitialCollaborationBatch implements Database.Batchable<Sobject>,Database.AllowsCallouts, Database.Stateful{
 
  public String base_url = 'https://app.box.com/files/0/f/';
  public Integer record_count = 0; 
  public Integer record_count_stop = 0;
  public string  foldername ='';
  public Set<String>IdSet;
  public BoxRemainingInitialCollaborationBatch(String folderName,Integer record_count_stop,Set<String>IdSet){
    this.record_count_stop = record_count_stop;
    this.foldername =foldername; 
    this.IdSet= IdSet;
  } 
  Map<Id,string> Usermap;
  Map<string,List<string>> Contactmap;
  public Database.QueryLocator start(Database.BatchableContext BC){
        Usermap = new Map<Id,string>();
        
         for(User u:[Select id ,email from user where Isactive=true]){
              Usermap.put(u.id,u.email);
          } 
      
     Contactmap = new Map<string,List<string>>(); 
   
    for(Account acc:[Select id, (Select email from contacts where email!=null) from Account where id!=null]){
       if(acc.contacts!=null){   
        for(Contact con :acc.contacts){
            
            if(!Contactmap.containsKey(acc.id)){
                Contactmap.put(acc.id, new List<string>());
            }
            Contactmap.get(acc.id).add(con.email);
          }
         } 
      
      } 
      
     return Database.getQueryLocator('Select id,cf_opportunity__c,CF_Box_Folder_Id__c,cf_opportunity__r.Pipeline_Stage__c from Sub_Folder__c where name=:folderName and CF_Box_Folder_Id__c in:IdSet');
  }
  
  public void execute(Database.BatchableContext BC, List<Sub_Folder__c> fldList){
     system.debug('======'+fldList);
    List<Collaboration__c> lstcollab = new List<Collaboration__c>();
    List<Box_Error__c> bxErrList = new List<Box_Error__c>();     
    Set<String> stagesSet= new Set<String>();
    Set<String> NewstagesSet= new Set<String>();
    Set<String> profileSet= new Set<String>();
    
    Map<String,String> folderIdMap= new Map<String,String>();
    Map<String,String> profileGroupMap = new Map<String,String>();
    List<String> foldIdlst = new List<String>(); 
    Set<String> BoxfoldIdlst = new Set<String>();
    List<Box_Log__c> boxLogsLst = new List<Box_Log__c>();     
   
    for(Sub_Folder__c sb: fldList){
        NewstagesSet.add(sb.cf_opportunity__r.Pipeline_Stage__c);
        foldIdlst.add(sb.CF_Box_Folder_Id__c);
        BoxfoldIdlst.add(sb.cf_opportunity__c);
        folderIdMap.put(sb.cf_opportunity__c,sb.CF_Box_Folder_Id__c); 
    }
    
    Map<String,String> profilePermissionMap = new Map<String,String>();
    Map<String,String> profileLookupMap = new Map<String,String>();
    Map<String,String> profileNameMap = new Map<String,String>();
    Map<String,List<String>> profileUserMap = new Map<String,List<String>>();
    
   
     
    for(BoxAccessMatrix_Stage__c bxStg:[select Box_Permission__c,BoxAccessMatrix_Profile__r.Lookup_field_Name__c,
    BoxAccessMatrix_Profile__r.Profile_Name__c, BoxAccessMatrix_Profile__r.Profile_Id__c, Stage__c 
    from BoxAccessMatrix_Stage__c 
    where BoxAccessMatrix_Profile__r.BoxAccessMatrix_SubFolder__r.SubFolder_Name__c =: folderName 
    and check__c =true and Stage__c in:NewstagesSet]){       
        stagesSet.add(bxStg.Stage__c);
        
        profileSet.add(bxStg.BoxAccessMatrix_Profile__r.Profile_Id__c);
        profilePermissionMap.put(bxStg.BoxAccessMatrix_Profile__r.Profile_Id__c,bxStg.Box_Permission__c);
        profileLookupMap.put(bxStg.BoxAccessMatrix_Profile__r.Profile_Id__c,bxStg.BoxAccessMatrix_Profile__r.Lookup_field_Name__c);
        profileNameMap.put(bxStg.BoxAccessMatrix_Profile__r.Profile_Id__c,bxStg.BoxAccessMatrix_Profile__r.Profile_Name__c);
        profileUserMap.put(bxStg.BoxAccessMatrix_Profile__r.Profile_Id__c,new List<String>());
       
    }
    
    for(Profile prf:[Select id,(Select id,email,Isactive  from users where isActive = true) from profile where id in:profileUserMap.keyset()]){
         
         for(User us: prf.Users){
             if(us.Isactive == true)
                 profileUserMap.get(prf.id).add(us.email);
             }
       }

     
    
     system.debug('foldIdlst size='+foldIdlst.size());
     if(foldIdlst.size() > 0){
     
         for(Box_Group__c  bg : [Select SF_Profile_Id__c, BoxGroup_Id__c,BoxGroup_Name__c from Box_Group__c]){
             profileGroupMap.put(bg.SF_Profile_Id__c, bg.BoxGroup_Id__c);
         }
     
         for(String prf: profileSet){
            system.debug('========='+profileNameMap.get(prf));
             if(profileLookupMap.get(prf) != null){
                 String query;
                 String sObjName;
                 String FolderIDstring; 
                 
               integer i = 1;  
               FolderIDstring = '(';
               for(String str:BoxfoldIdlst){
               
                   if(BoxfoldIdlst.size() == i){
                       FolderIDstring += '\''+str+'\'';
                   }
                   else{
                       FolderIDstring += '\''+str+'\',';
                   }
                   i++;
                }
               FolderIDstring += ')';
             
             system.debug('********'+FolderIDstring);  
                   
                if(profileLookupMap.get(prf)=='Subcontractor__c' || profileLookupMap.get(prf)=='EE_Assessor__c')
                    query = 'Select id,ownerId from opportunity where id in'+FolderIDstring;
                else{
                   query = 'Select id, O_Box_Folder_Id__c,'+ profileLookupMap.get(prf)+' from opportunity where  id in '+FolderIDstring;
                    }
                 system.debug('****'+query);
              
             
                for(Opportunity opp : Database.query(query)){ 
                     if(profileLookupMap.get(prf)=='Subcontractor__c'){
                     
                            String prjquery = 'Select '+ profileLookupMap.get(prf)+', RecordType.Name from project__c where opportunity__c=\''+opp.id+'\'';
                            system.debug('----'+prjquery);
                           for(Project__c prj:Database.query(prjquery)){
                                   Id LookupPrjId = String.valueOf(prj.get(profileLookupMap.get(prf)));
                                  if(LookupPrjId!=null){ 
                                   string LookUpAccId = String.valueof(LookupPrjId);
                                   sObjName = LookupPrjId.getSObjectType().getDescribe().getName();   
                                if(sObjName=='Account' && LookUpAccId!=null){
                              
                                   if((prj.RecordType.Name == 'EE Assessment'|| prj.RecordType.Name =='EE Upgrade') && folderName == 'EE'){
                                       
                                           for(String acSt:Contactmap.get(LookUpAccId)){
                                             system.debug(foldIdlst+'======'+acSt);
                                            if(acSt!=null) //change
                                                BoxInitialCollaborationBatch.CreatePrfLookupUserCollaboration(opp.id,LookUpAccId,folderIdMap.get(opp.id),acSt,profilePermissionMap.get(prf),prf,lstcollab,boxLogsLst );
                                            }
                                            
                                     }
                                  if((prj.RecordType.Name != 'EE Assessment'||prj.RecordType.Name !='EE Upgrade') && folderName != 'EE'){  
                                 
                                        for(String acSt:Contactmap.get(LookUpAccId)){
                                         system.debug(foldIdlst+'======'+acSt);
                                        if(acSt!=null) 
                                            BoxInitialCollaborationBatch.CreatePrfLookupUserCollaboration(opp.id,LookUpAccId,folderIdMap.get(opp.id),acSt,profilePermissionMap.get(prf),prf,lstcollab,boxLogsLst );
                                        }
                                      }
                                }
                               }   
                              }
                         }
                     else if(profileLookupMap.get(prf)=='EE_Assessor__c'){
                        String prjquery = 'Select '+ profileLookupMap.get(prf)+' from project__c where opportunity__c=\''+opp.id+'\'';
                        system.debug('hiiiiiii'+prjquery);
                         for(Project__c prj:Database.query(prjquery)){
                               Id LookupPrjId = String.valueOf(prj.get(profileLookupMap.get(prf))); 
                              
                                if(LookupPrjId!=null) 
                                     BoxInitialCollaborationBatch.CreatePrfLookupUserCollaboration(opp.id,LookupPrjId ,folderIdMap.get(opp.id),LookupPrjId ,profilePermissionMap.get(prf),prf,lstcollab,boxLogsLst );
                                 
                             }
                       
                        }   
                    else{
                         if(opp.get(profileLookupMap.get(prf))!=null){
                            Id LookupId = String.valueOf(opp.get(profileLookupMap.get(prf)));
                            system.debug('====&&&&'+sObjName);  
                            BoxInitialCollaborationBatch.CreatePrfLookupUserCollaboration(opp.id,LookupId,folderIdMap.get(opp.id),LookupId ,profilePermissionMap.get(prf),prf,lstcollab,boxLogsLst );
                          }
                       else{
                          if(profileNameMap.get(prf)=='Concierge')
                               BoxInitialCollaborationBatch.CreatePrfLookupUserCollaboration(opp.id,opp.id,folderIdMap.get(opp.id),opp.id,profilePermissionMap.get(prf),prf,lstcollab,boxLogsLst );
                          } 
                         }
                       }  
                    }     
             else{
              system.debug('======'+profileNameMap.get(prf));
               if(profileNameMap.get(prf)=='Concierge'||profileNameMap.get(prf)=='Document Controller'||profileNameMap.get(prf)=='System Administrator'){
                 //BoxInitialCollaborationBatch.CreatePrfLookupUserCollaboration(opp.id,LookupPrjId ,folderIdMap.get(opp.id),LookupPrjId ,profilePermissionMap.get(prf),prf,lstcollab,boxLogsLst );
                 }
             else {
               system.debug('======'+profileNameMap.get(prf));      
                     for(String stEmail:profileUserMap.get(prf)){
                           system.debug(foldIdlst+'======'+stEmail); 
                          if(stEmail!=null){
                             //BoxInitialCollaborationBatch.CreateLookupUserCollaboration(foldIdlst,stEmail,profilePermissionMap.get(prf),prf,lstcollab,bxErrList);   
                        }
                        } 
                   
               
                 }                 
             }
             
         }
         insert lstcollab;
         insert bxErrList; 
        
        }
       record_count += fldList.size();
      if(record_count == record_count_stop){
       system.debug('######################################## job aborted record_count is'+ record_count);
       System.abortJob(BC.getJobId());
       }     
    
          
  } 
  
  public void finish(Database.BatchableContext BC){}
  
  
  public static void CreateUserGroupCollaboration(List<String>fIdlst,String groupId, String role,String ProfId,List<Collaboration__c> lstcollab,List<Box_Error__c> bxErrList){
           
        try{
        
        boolean isCallSuccess = true;
        Integer lastIndex = -1;
        String collfld;
        for(integer i=0; i<fIdlst.size(); i++){
            if(!isCallSuccess)
                i = lastIndex; 
            lastIndex = i;
            collfld = fIdlst[i];
            if(collfld != null && groupId!= null && role != null){
                Box__c box = Box__c.getInstance();
                HttpRequest req = new HttpRequest();
                req.setEndpoint('https://api.box.com/2.0/collaborations');
                req.setMethod('POST');
                req.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
                req.setBody('{"item": { "id": "'+collfld+'", "type": "folder"}, "accessible_by": { "id": "'+groupId+'", "type": "group" }, "role": "'+role+'"}');
                HTTPResponse res = new Http().send(req);
                // Collaboration__c clb; 
                Collaborationwrapper cw = new Collaborationwrapper();
                system.debug(res.getStatusCode()+'hiiiii'+res.getbody());
                if(res.getStatusCode() == 201){
                    cw = (Collaborationwrapper)JSON.deserialize(res.getBody(),Collaborationwrapper.class);
                    Collaboration__c clb = new Collaboration__c();
                    clb.BoxCollaboration_Id__c = cw.Id;
                    clb.Role__c= cw.role;
                    clb.BoxFolder_Id__c= collfld;
                    clb.BoxGroup_Id__c=groupId;
                    clb.SFUser_Email__c = 'group@test.com';
                    clb.SFProfile_Id__c = ProfId;
                    lstcollab.add(clb);
                    isCallSuccess = true;
                }
                else if(res.getStatusCode() == 401){
                    BoxREFRESHAccessTokenScheduler.getToken();
                    isCallSuccess = false;
                }
                else{
                     Box_Error__c bxerr = new Box_Error__c();
                     bxerr.name = String.valueOf(res.getStatusCode()); 
                     bxerr.Message__c = collfld; 
                     bxerr.Body__c = res.getBody();
                     bxerr.Type__c = 'Collaboration';
                     bxerr.Status__c = 'Error';
                     bxErrList.add(bxerr); 
                }
            }
          }  
        }
        catch(Exception e){
            Box_Error__c bxerr = new Box_Error__c();
             bxerr.name = 'Col Exception';
             bxerr.Message__c ='' ; 
             bxerr.Body__c = '';
             bxerr.Type__c = 'Collaboration';
             bxerr.Status__c = 'Error';
             bxErrList.add(bxerr); 
        }
        finally{
         
         
         }
   } 
   
   public static void CreateLookupUserCollaboration(List<String>fIdlst,String userEmail, String role,String ProfId,List<Collaboration__c> lstcollab,List<Box_Error__c> bxErrList){
           
        try{
        
        boolean isCallSuccess = true;
        Integer lastIndex = -1;
        String  collfld;
        for(integer i=0; i<fIdlst.size(); i++){
            
            if(!isCallSuccess)
                i = lastIndex; 
            lastIndex = i;
            collfld = fIdlst[i];
         
            if(collfld!= null && userEmail!= null && role != null){
                Box__c box = Box__c.getInstance();
                HttpRequest req = new HttpRequest();
                req.setEndpoint('https://api.box.com/2.0/collaborations');
                req.setMethod('POST');
                req.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
                req.setBody('{"item": { "id": "'+collfld+'", "type": "folder"}, "accessible_by": { "login": "'+userEmail+'", "type": "user" }, "role": "'+role+'"}');
                HTTPResponse res = new Http().send(req);
                CollaborationUserWrapper cuw = new CollaborationUserWrapper ();
                system.debug(res.getStatusCode()+'hiiiii'+res.getbody());
                if(res.getStatusCode() == 201){
                    cuw = (CollaborationUserWrapper)JSON.deserialize(res.getBody(),CollaborationUserWrapper.class);
                    Collaboration__c clb = new Collaboration__c();
                    if(cuw.accessibleby!=null){
                        clb.BoxCollaboration_Id__c = cuw.Id;
                        clb.Role__c= cuw.role;
                        clb.BoxFolder_Id__c= collfld;
                        clb.BoxUser_Id__c=cuw.accessibleby.id;
                       }
                    else{
                        clb.BoxCollaboration_Id__c = cuw.id;
                        clb.Role__c= cuw.role;
                        clb.BoxFolder_Id__c= collfld;
                        clb.BoxUser_Id__c='';
                       } 
                    clb.SFUser_Email__c = userEmail;
                    clb.SFProfile_Id__c = ProfId;     
                    lstcollab.add(clb);
                }
               else if(res.getStatusCode() == 401){
                    BoxREFRESHAccessTokenScheduler.getToken();
                    isCallSuccess = false;
                }
                else{
                     Box_Error__c bxerr = new Box_Error__c();
                     bxerr.name = String.valueOf(res.getStatusCode()); 
                     bxerr.Message__c = collfld; 
                     bxerr.Body__c = res.getBody();
                     bxerr.Type__c = 'Collaboration';
                     bxerr.Status__c = 'Error';
                     bxErrList.add(bxerr); 
                    
                }
            }
          }  
        }
        catch(Exception e){
            Box_Error__c bxerr = new Box_Error__c();
             bxerr.name = 'Col Exception';
             bxerr.Message__c ='' ; 
             bxerr.Body__c = '';
             bxerr.Type__c = 'Collaboration';
             bxerr.Status__c = 'Error';
             bxErrList.add(bxerr); 
        }
        finally{
         
         
         }
   } 
  
   public static void CreatePrfLookupUserCollaboration(string fId,String userEmail, String role,String ProfId,List<Collaboration__c> lstcollab,List<Box_Error__c> bxErrList){
           
        try{
           //boolean isCallSuccess = true;
          system.debug(fId+'-------'+userEmail+'%%%%%%%'+role);
            if(fId!= null && userEmail!= null && role != null){
                Box__c box = Box__c.getInstance();
                HttpRequest req = new HttpRequest();
                req.setEndpoint('https://api.box.com/2.0/collaborations');
                req.setMethod('POST');
                req.setHeader('Authorization','Bearer '+box.BoxAccess_Token__c);
                req.setBody('{"item": { "id": "'+fId+'", "type": "folder"}, "accessible_by": { "login": "'+userEmail+'", "type": "user" }, "role": "'+role+'"}');
                HTTPResponse res = new Http().send(req);
                // Collaboration__c clb; 
                CollaborationUserWrapper cuw = new CollaborationUserWrapper ();
                system.debug(res.getStatusCode()+'hiiiii'+res.getbody());
                if(res.getStatusCode() == 201){
                    cuw = (CollaborationUserWrapper)JSON.deserialize(res.getBody(),CollaborationUserWrapper.class);
                    Collaboration__c clb = new Collaboration__c();
                    if(cuw.accessibleby!=null){
                        clb.BoxCollaboration_Id__c = cuw.Id;
                        clb.Role__c= cuw.role;
                        clb.BoxFolder_Id__c= fId;
                        clb.BoxUser_Id__c=cuw.accessibleby.id;
                       }
                    else{
                        clb.BoxCollaboration_Id__c = cuw.id;
                        clb.Role__c= cuw.role;
                        clb.BoxFolder_Id__c= fId;
                        clb.BoxUser_Id__c='';
                       }
                    clb.SFUser_Email__c = userEmail;
                    clb.SFProfile_Id__c = ProfId;
                    lstcollab.add(clb);
                }
              else if(res.getStatusCode() == 401){
                 BoxREFRESHAccessTokenScheduler.getToken();
                 //BoxInitialCollaborationBatch.CreatePrfLookupUserCollaboration(fId,userEmail, role,ProfId,lstcollab,bxErrList);
               }  
                else{
                     Box_Error__c bxerr = new Box_Error__c();
                     bxerr.name = String.valueOf(res.getStatusCode()); 
                     bxerr.Message__c = fId; 
                     bxerr.Body__c = res.getBody();
                     bxerr.Type__c = 'Collaboration';
                     bxerr.Status__c = 'Error';
                     bxErrList.add(bxerr); 
                    
                }
            }
            
        }
        catch(Exception e){
             Box_Error__c bxerr = new Box_Error__c();
             bxerr.name = 'Col Exception';
             bxerr.Message__c ='' ; 
             bxerr.Body__c = '';
             bxerr.Type__c = 'Collaboration';
             bxerr.Status__c = 'Error';
             bxErrList.add(bxerr); 
        }
        finally{
         
         
         }
   }  
  
    public class CollaborationWrapper {

        public String type;
        public String id;
        public Created_by created_by;
        public String created_at;
        public String modified_at;
        public Object expires_at;
        public String status;
        public Created_by accessible_by;
        public String role;
        public String acknowledged_at;
        public Item item;
    
    }
    
    public class Created_by {
        public String type;
        public String id;
        public String name;
        public String login;
    }

    public class Item {
        public String type;
        public String id;
        public String sequence_id;
        public String etag;
        public String name;
    }
    
    public class CollaborationItemsWrapper {

        public Integer total_count;
        public List<Item> entries;
        public Integer offset;
    }

    public class CollaborationInfoWrapper {

        public Integer total_count;
        public List<Entries> entries;
    }
    
    public class Entries {
        public String type;
        public String id;
        public Object created_by;
        public String created_at;
        public String modified_at;
        public Object expires_at;
        public String status;
        public Accessible_by accessible_by;
        public String role;
        public String acknowledged_at;
        public Item item;
    }
    
    public class Accessible_by {
        public String type;
        public String id;
        public String name;
    }
 public class CollaborationUserWrapper {
    public String id;
    public cls_accessible_by accessibleby;
    public String role; 
   } 
 public class cls_accessible_by {
    public String type; 
    public String id;   
    public String name; 
    public String login;   
    }
 
      
   
 }