posiGen_FullsendBox/src/objects/BoxAccessMatrix_SubFolder__c.object
<CustomObject>
    <fields>
        <fullName>SubFolder_Name__c</fullName>
        <label>SubFolder Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BoxAccessMatrix SubFolder</label>
    <nameField>
        <label>BoxAccessMatrix SubFolder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BoxAccessMatrix SubFolders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/UserCollaboratiionController.cls
public with sharing class UserCollaboratiionController{

   public UserCollaboratiionController(){}
   
 
  
 public void createUserCollaboratoion(User userId){
       
    for(BoxAccessMatrix_subfolder__c Bas:[Select Subfolder_Name__c from BoxAccessMatrix_subfolder__c]){
    
         Database.executeBatch(new Batch_CreateUserCollaboration(userId,Bas.Subfolder_Name__c),1);     
      
     }
  
   } 
   
 public void DeleteUserCollaboratoion(User userId){
       
          Database.executeBatch(new  Batch_DeleteUserCollaboration(userId),1);
  
   }     
 
}