posiGen_FullsendBox/src/objects/Business_Stage__c.object
<CustomObject>
    <label>Business Stage</label>
    <nameField>
        <label>Business Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Status__c.object
<CustomObject>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Business Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Business_Installation_Stage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Installation Stage</label>
        <referenceTo>Business_Stage__c</referenceTo>
        <relationshipLabel>PM Stages</relationshipLabel>
        <relationshipName>PM_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Status</label>
        <referenceTo>Business_Status__c</referenceTo>
        <relationshipLabel>PM Stages</relationshipLabel>
        <relationshipName>PM_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PM_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PM Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Tool_V2__c</fullName>
        <label>PM Tool V2</label>
        <referenceTo>PM_Tool_V2__c</referenceTo>
        <relationshipLabel>PM Stages</relationshipLabel>
        <relationshipName>PM_Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PM Stage</label>
    <nameField>
        <displayFormat>Stage-{000000}</displayFormat>
        <label>PM Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Tool_V2__c.object
<CustomObject>
    <label>PM Tool V2</label>
    <nameField>
        <label>PM Tool V2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Tools V2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/PM_Review.cls
public class PM_Review{

    public String pmToolId;
    public static Boolean pmReviewed = false;
    public List<PM_Stage__c> pmStageList{get;set;}

    public PM_Review(ApexPages.StandardController controller) {
        
        pmStageList = new List<PM_Stage__c>();
    }

    
    public void loadPmReview(){
        
        try{
        
            pmToolId = ApexPages.currentPage().getParameters().get('id');
            if(pmToolId != null && pmToolId != ''){
                
                pmStageList = [select id, Business_Installation_Stage__r.Name, Business_Status__r.Name, Business_Status__r.Score__c, PM_Review__c, PM_Tool_V2__c from PM_Stage__c where PM_Tool_V2__c =: pmToolId and (Business_Status__r.Score__c = 3 or Business_Status__r.Score__c = 4)];
            }
            else{
            
               ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'PM Tool id is not provided');
               ApexPages.addMessage(errMsg);
            }
        }
        catch(Exception e){
           ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()+', '+e.getStackTraceString());
           ApexPages.addMessage(errMsg);
        }
        
    }
    
    public PageReference saveStages(){
        
        try{
            pmReviewed = true;
            update pmStageList;
            return new PageReference('/'+pmToolId);
        }
        catch(Exception e){
           ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()+', '+e.getStackTraceString());
           ApexPages.addMessage(errMsg);
           
           return null;
        }
    }
}