posiGen_FullsendBox/src/objects/Business_Market__c.object
<CustomObject>
    <label>Business Market</label>
    <nameField>
        <label>Business Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Business_Market__c</fullName>
        <label>Business Market</label>
        <referenceTo>Business_Market__c</referenceTo>
        <relationshipLabel>Business Stages</relationshipLabel>
        <relationshipName>Business_Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Business Stage</label>
    <nameField>
        <label>Business Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Business_Installation_Stage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Installation Stage</label>
        <referenceTo>Business_Stage__c</referenceTo>
        <relationshipLabel>PM Stages</relationshipLabel>
        <relationshipName>PM_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PM_Review__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PM Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Tool_V2__c</fullName>
        <label>PM Tool V2</label>
        <referenceTo>PM_Tool_V2__c</referenceTo>
        <relationshipLabel>PM Stages</relationshipLabel>
        <relationshipName>PM_Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PM Stage</label>
    <nameField>
        <displayFormat>Stage-{000000}</displayFormat>
        <label>PM Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Tool_V2__c.object
<CustomObject>
    <fields>
        <fullName>Completion_Average__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Completion Average</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <label>Lease Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PM Tools V2</relationshipLabel>
        <relationshipName>PM_Tools_V2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PM Tool V2</label>
    <nameField>
        <label>PM Tool V2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Tools V2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestPMStageTrigger.cls
@isTest
public with sharing class TestPMStageTrigger {
    public static testMethod void unitTest1() {
        Opportunity opp = new Opportunity();
        opp.name = 'Test1';
        opp.StageName = 'Layout Approval';
        opp.CloseDate = system.today();
        insert opp;
        
        PM_Tool_V2__c pm = new PM_Tool_V2__c();
        pm.Opportunity__c = opp.id;
        pm.Project_Status__c = 'Active';
        pm.Completion_Average__c = 0.0;
        pm.Lease_Type__c = '';
        insert pm;   
    
        Business_Market__c bm = new Business_Market__c(name='CT');
        insert bm;
        
        Business_Stage__c bist = new Business_Stage__c(name='test123',Business_market__c = bm.id);
        insert bist;
        
        PM_Stage__c pmStage = new PM_Stage__c();
        pmStage.Business_Installation_Stage__c = bist.id;
        pmStage.PM_Tool_V2__c = pm.id;
        pmStage.PM_Review__c = true;
        insert pmStage;
        
        PM_Review.pmReviewed = true;
        update pmStage;
    }
}