posiGen_FullsendBox/src/objects/Business_Installation_Step__c.object
<CustomObject>
    <fields>
        <fullName>Business_Stage__c</fullName>
        <label>Business Stage</label>
        <referenceTo>Business_Stage__c</referenceTo>
        <relationshipLabel>Business Installation Steps</relationshipLabel>
        <relationshipName>Business_Installation_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Business Installation Step</label>
    <nameField>
        <label>Business Installation Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Installation Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Market__c.object
<CustomObject>
    <label>Business Market</label>
    <nameField>
        <label>Business Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Business_Market__c</fullName>
        <label>Business Market</label>
        <referenceTo>Business_Market__c</referenceTo>
        <relationshipLabel>Business Stages</relationshipLabel>
        <relationshipName>Business_Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Business Stage</label>
    <nameField>
        <label>Business Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Status__c.object
<CustomObject>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Business Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Steps__c.object
<CustomObject>
    <fields>
        <fullName>Aging__c</fullName>
        <label>Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Installation_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Installation Step</label>
        <referenceTo>Business_Installation_Step__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Status</label>
        <referenceTo>Business_Status__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Process_Aging_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Process Aging Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>In_Process_Aging__c</fullName>
        <label>In Process Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_Process_End_Date__c</fullName>
        <label>In Process End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Process_Start_Date__c</fullName>
        <label>In Process Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NA_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Review_Aging_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PM Review Aging Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Review_Aging__c</fullName>
        <label>PM Review Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PM_Review_End_Date__c</fullName>
        <label>PM Review End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PM_Review_Start_Date__c</fullName>
        <label>PM Review Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PM_Tool_V2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PM Tool V2</label>
        <referenceTo>PM_Tool_V2__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>PM Step</label>
    <nameField>
        <displayFormat>Step-{000000}</displayFormat>
        <label>PM Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Tool__c.object
<CustomObject>
    <fields>
        <fullName>Completion_Average__c</fullName>
        <label>Completion %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <formula>Deal__r.RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lease Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PM Tools</relationshipLabel>
        <relationshipName>PM_Tools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Removal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PM Tool</label>
    <nameField>
        <label>PM Tool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Tool_V2__c.object
<CustomObject>
    <fields>
        <fullName>Completion_Average__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Completion Average</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <label>Lease Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PM Tools V2</relationshipLabel>
        <relationshipName>PM_Tools_V2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PM Tool V2</label>
    <nameField>
        <label>PM Tool V2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Tools V2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestPmToolDataMigration.cls
@isTest
public with sharing class TestPmToolDataMigration {
  public static testMethod void myUnitTest1() {     
      Integer record_limit = 0;
      String oppId = '';
      Database.BatchableContext BC;
      List<PM_Steps__c> pmStepsList = new List<PM_Steps__c>();
      List<Business_Installation_Step__c> bisList = new List<Business_Installation_Step__c>();
      List<String> allSteps = new List<String>();
      List<PM_Tool_v2__c> pmToolList = new List<PM_Tool_V2__c>();
      String allString = 'Activation,Closing Call,Determination,EE Audit,EA State Application Approval,Electrical Install,Electrical Install,R&P Install,Quality Control,Permitting,Inspection,EE Upgrade,EA State Application Approval,Work Scope Approval,State Initial Approval,Site Verification,Engineering,Intro Call,Assessment,Sales Order Creation,Layout Approval';
      allSteps = allString.split(',');
      
      Business_Market__c bm = new Business_Market__c(name='CT');
      insert bm;
      
      Business_Status__c bs = new Business_Status__c(name='Complete',score__c=3);
      insert bs;
      
      Business_Stage__c bist = new Business_Stage__c(name='test123',Business_market__c = bm.id);
      insert bist;
      
      Opportunity opp = new Opportunity();
      opp.name = 'Test1';
      opp.StageName = 'Layout Approval';
      opp.CloseDate = system.today();
      insert opp;
      
      oppId = String.valueOf(opp.id);
        
      PM_Tool__c pm = new PM_Tool__c();
      pm.Opportunity__c = opp.id;
      pm.Project_Status__c = 'Active';
      pm.Completion_Average__c = 0.0;
      //pm.Lease_Type__c = '';
      insert pm;
        
      PM_Tool_V2__c pmNew = new PM_Tool_V2__c();
      pmNew.Opportunity__c = opp.id;
      pmNew.Project_Status__c = 'Active';
      pmNew.Completion_Average__c = 0.0;
      pmNew.Lease_Type__c = '';
      insert pmNew;
      
      pmToolList.add(pmNew);
      
      //system.assert(false, allSteps);
      
      for(String Name: allSteps) {       
        Business_Installation_Step__c bistep1 = new Business_Installation_Step__c(name=name,Business_Stage__c=bist.id);
        bisList.add(bistep1);
      }  
      
      insert bisList;
      
      //system.assert(false, bisList);
          
      for(Business_Installation_Step__c bistp: bisList) {
            PM_Steps__c pms = new PM_Steps__c();
            pms.Aging__c = 1;
            pms.Business_Installation_Step__c = bistp.id;
            pms.End_Date__c = null; 
            pms.In_Process_Aging__c = 2; 
            pms.In_Process_Aging_Exception__c = false; 
            pms.In_Process_End_Date__c = null; 
            pms.In_Process_Start_Date__c = null; 
            pms.NA_Override__c = false; 
            pms.PM_Review_Aging__c = 3; 
            pms.PM_Review_Aging_Exception__c = true; 
            pms.PM_Review_End_Date__c = null; 
            pms.PM_Review_Start_Date__c = null;
            pms.PM_Tool_V2__c = pmNew.id; 
            pms.Start_Date__c = null;
            pmStepsList.add(pms);
      }
      
      //system.assert(false, pmStepsList);
      insert pmStepsList;
      
      PmToolDataMigration dataMig = new PmToolDataMigration(record_limit, oppId);
      
      datamig.start(BC);
      
      Integer size = pmStepsList.size();
      datamig.execute(BC, pmToolList); 
   }
}