posiGen_FullsendBox/src/objects/Business_Installation_Step__c.object
<CustomObject>
    <fields>
        <fullName>Business_Stage__c</fullName>
        <label>Business Stage</label>
        <referenceTo>Business_Stage__c</referenceTo>
        <relationshipLabel>Business Installation Steps</relationshipLabel>
        <relationshipName>Business_Installation_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Display_In_Tracker__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Display In Tracker</label>
        <type>Checkbox</type>
    </fields>
    <label>Business Installation Step</label>
    <nameField>
        <label>Business Installation Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Installation Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Market__c.object
<CustomObject>
    <label>Business Market</label>
    <nameField>
        <label>Business Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Business_Market__c</fullName>
        <label>Business Market</label>
        <referenceTo>Business_Market__c</referenceTo>
        <relationshipLabel>Business Stages</relationshipLabel>
        <relationshipName>Business_Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Display_In_Tracker__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Display In Tracker</label>
        <type>Checkbox</type>
    </fields>
    <label>Business Stage</label>
    <nameField>
        <label>Business Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Status__c.object
<CustomObject>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Business Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Exception_Threshold__c.object
<CustomObject>
    <fields>
        <fullName>Business_Installation_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Installation Step</label>
        <referenceTo>Business_Installation_Step__c</referenceTo>
        <relationshipLabel>Exception Thresholds</relationshipLabel>
        <relationshipName>Exception_Thresholds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>In_Process_Threshold__c</fullName>
        <label>In Process Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PM_Review_Threshold__c</fullName>
        <label>PM Review Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Exception Threshold</label>
    <nameField>
        <label>Exception Threshold Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Thresholds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Steps__c.object
<CustomObject>
    <fields>
        <fullName>Aging__c</fullName>
        <label>Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Installation_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Installation Step</label>
        <referenceTo>Business_Installation_Step__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Status</label>
        <referenceTo>Business_Status__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Process_Aging_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Process Aging Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>In_Process_Aging__c</fullName>
        <label>In Process Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_Process_End_Date__c</fullName>
        <label>In Process End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Process_Start_Date__c</fullName>
        <label>In Process Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NA_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Review_Aging_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PM Review Aging Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Review_Aging__c</fullName>
        <label>PM Review Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PM_Review_End_Date__c</fullName>
        <label>PM Review End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PM_Review_Start_Date__c</fullName>
        <label>PM Review Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>PM Step</label>
    <nameField>
        <displayFormat>Step-{000000}</displayFormat>
        <label>PM Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestAgingUpdate.cls
@isTest
public class TestAgingUpdate{
     public Static testmethod void unitTest1() {
        Database.BatchableContext BC;
     
        Business_Market__c bm = new Business_Market__c(name='CT');
        insert bm;
        
        Business_Status__c busStatus = new Business_Status__c(name='Complete',score__c=3);
        insert busStatus;
        
        PMToolV2.runStepTrigger = true;
        
        Business_Stage__c bs = new Business_Stage__c(Name='Feasibility', Business_Market__c = bm.id, Display_In_Tracker__c=true);
        insert bs;
        
        Business_Installation_Step__c bis = new Business_Installation_Step__c();
        bis.name = 'Assessment';
        bis.Business_Stage__c = bs.id;
        insert bis;
        
        Exception_Threshold__c ex = new Exception_Threshold__c();
        ex.In_Process_Threshold__c = 2; 
        ex.PM_Review_Threshold__c = 3;
        ex.Business_Installation_Step__c = bis.id;
        insert ex;
        
        PM_Steps__c pms = new PM_Steps__c();
        List<PM_Steps__c> pmList = new List<PM_Steps__c>();
        pms.Aging__c = 1;
        pms.Business_Installation_Step__c = bis.id;
        pms.End_Date__c = null; 
        pms.In_Process_Aging__c = 2; 
        pms.In_Process_Aging_Exception__c = false; 
        pms.In_Process_End_Date__c = null; 
        pms.In_Process_Start_Date__c = null; 
        pms.NA_Override__c = false; 
        pms.PM_Review_Aging__c = 3; 
        pms.PM_Review_Aging_Exception__c = true; 
        pms.PM_Review_End_Date__c = null; 
        pms.PM_Review_Start_Date__c = null;
        pms.Start_Date__c = null;
        insert pms;
        
        pmList.add(pms);
        
        AgingUpdate agingUpt = new AgingUpdate();
        
        agingUpt.start(BC);
        agingUpt.execute(BC, pmList);
        agingUpt.finish(BC);
     }
}