posiGen_FullsendBox/src/objects/Business_Installation_Step__c.object
<CustomObject>
    <label>Business Installation Step</label>
    <nameField>
        <label>Business Installation Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Installation Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Business_Status__c.object
<CustomObject>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Business Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Exception_Threshold__c.object
<CustomObject>
    <fields>
        <fullName>Business_Installation_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Installation Step</label>
        <referenceTo>Business_Installation_Step__c</referenceTo>
        <relationshipLabel>Exception Thresholds</relationshipLabel>
        <relationshipName>Exception_Thresholds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>In_Process_Threshold__c</fullName>
        <label>In Process Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PM_Review_Threshold__c</fullName>
        <label>PM Review Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Exception Threshold</label>
    <nameField>
        <label>Exception Threshold Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Thresholds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Stage__c.object
<CustomObject>
    <fields>
        <fullName>Business_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Status</label>
        <referenceTo>Business_Status__c</referenceTo>
        <relationshipLabel>PM Stages</relationshipLabel>
        <relationshipName>PM_Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NA_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Tool_V2__c</fullName>
        <label>PM Tool V2</label>
        <referenceTo>PM_Tool_V2__c</referenceTo>
        <relationshipLabel>PM Stages</relationshipLabel>
        <relationshipName>PM_Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PM Stage</label>
    <nameField>
        <displayFormat>Stage-{000000}</displayFormat>
        <label>PM Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Steps__c.object
<CustomObject>
    <fields>
        <fullName>Aging__c</fullName>
        <label>Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Installation_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Installation Step</label>
        <referenceTo>Business_Installation_Step__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Status</label>
        <referenceTo>Business_Status__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Process_Aging_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>In Process Aging Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>In_Process_Aging__c</fullName>
        <label>In Process Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_Process_End_Date__c</fullName>
        <label>In Process End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Process_Start_Date__c</fullName>
        <label>In Process Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NA_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Review_Aging_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PM Review Aging Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Review_Aging__c</fullName>
        <label>PM Review Aging</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PM_Review_End_Date__c</fullName>
        <label>PM Review End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PM_Review_Start_Date__c</fullName>
        <label>PM Review Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PM_Stage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PM Stage</label>
        <referenceTo>PM_Stage__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PM_Tool_V2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PM Tool V2</label>
        <referenceTo>PM_Tool_V2__c</referenceTo>
        <relationshipName>PM_Stepses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>PM Step</label>
    <nameField>
        <displayFormat>Step-{000000}</displayFormat>
        <label>PM Steps Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/PM_Tool_V2__c.object
<CustomObject>
    <label>PM Tool V2</label>
    <nameField>
        <label>PM Tool V2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Tools V2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/AgingUpdate.cls
public class AgingUpdate implements Database.Batchable<Sobject>, Database.Stateful{
     
    Map<id, Exception_Threshold__c> exceptionMap;
    
    public AgingUpdate(){
          
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
    
        exceptionMap = new Map<id, Exception_Threshold__c>();
        for(Exception_Threshold__c et: [select id, Business_Installation_Step__c, In_Process_Threshold__c, PM_Review_Threshold__c from Exception_Threshold__c]){
              exceptionMap.put(et.Business_Installation_Step__c, et);              
        }
        
        String query='SELECT Id,Aging__c,Business_Installation_Step__c,Business_Status__c,End_Date__c,In_Process_Aging__c,In_Process_Aging_Exception__c,In_Process_End_Date__c,In_Process_Start_Date__c,NA_Override__c,PM_Review_Aging__c,PM_Review_Aging_Exception__c,PM_Review_End_Date__c,PM_Review_Start_Date__c,PM_Stage__c,PM_Tool_V2__c,Start_Date__c from PM_Steps__c where End_Date__c = null and Business_status__r.Score__c != 0 and Business_status__r.Score__c != -1';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC,List<PM_Steps__c> scope) {
        
        List<PM_Steps__c> pmAgingList = new List<PM_Steps__c>();

        for(PM_Steps__c pm : scope){
        
           try{
            
               // Calculation for aging
               Integer aging = 0;
               
               if(pm.Start_Date__c != null) {
                  aging = Integer.valueOf(pm.Start_Date__c.daysBetween(System.today()));
               }
               pm.Aging__c = aging;
            
               // Calculation for pm review aging
               Integer pm_review_aging = 0;
               
               if(pm.PM_Review_Start_Date__c != null && pm.PM_Review_End_Date__c == null) {
                  pm_review_aging = Integer.valueOf(pm.PM_Review_Start_Date__c.daysBetween(System.today()));
               }
               pm.PM_Review_Aging__c = pm_review_aging;
               
               // Calculation for in process aging
               Integer in_process_aging = 0;
               
               if(pm.In_Process_Start_Date__c != null && pm.In_Process_End_Date__c == null) {
                  in_process_aging = Integer.valueOf(pm.In_Process_Start_Date__c.daysBetween(System.today()));
               }
               pm.In_Process_Aging__c = in_process_aging;
               
               // Calculation for pm review exception
               if(exceptionMap.containsKey(pm.Business_Installation_Step__c)){
                    if(exceptionMap.get(pm.Business_Installation_Step__c).PM_Review_Threshold__c < pm.PM_Review_Aging__c){
                        pm.PM_Review_Aging_Exception__c = true;
                    }
                   
                    if(exceptionMap.get(pm.Business_Installation_Step__c).In_Process_Threshold__c < pm.In_Process_Aging__c){
                        pm.In_Process_Aging_Exception__c = true;
                    }
                    
                }
                      
                pmAgingList.add(pm);
            }
            catch(Exception e){
                system.debug('Following Error has Occured'+ e.getMessage());
            } 
        }
        
        try{
            update pmAgingList;
        }
        catch(Exception e){
            system.debug('Following Error has Occured'+ e.getMessage());
        }
        
    }

    public void finish(Database.BatchableContext BC){
    }
}