posiGen_FullsendBox/src/objects/Census_Tract__c.object
<CustomObject>
    <fields>
        <fullName>Census_Tract__c</fullName>
        <externalId>true</externalId>
        <label>Census Tract</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>Census Tract</label>
    <nameField>
        <displayFormat>CT{000000}</displayFormat>
        <label>Census Tract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Census Tracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Census_Tract__c</fullName>
        <description>2013 Shape Files</description>
        <inlineHelpText>2013 Shape Files</inlineHelpText>
        <label>Census Tract</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Property__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities At This Property</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_City__c</fullName>
        <description>City from Assessor Record</description>
        <inlineHelpText>City from Assessor Record</inlineHelpText>
        <label>Assessor City</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_House__c</fullName>
        <description>House Number from Assessor Record</description>
        <inlineHelpText>House Number from Assessor Record</inlineHelpText>
        <label>Assessor House #</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_State__c</fullName>
        <description>State from Assessor Record</description>
        <inlineHelpText>State from Assessor Record</inlineHelpText>
        <label>Assessor State</label>
        <picklist>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assessor_Street_Direction__c</fullName>
        <description>Street Direction from Assessor Record</description>
        <inlineHelpText>Street Direction from Assessor Record</inlineHelpText>
        <label>Assessor Street Direction</label>
        <picklist>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assessor_Street_Name__c</fullName>
        <description>Street Name from Assessor Record</description>
        <inlineHelpText>Street Name Only, without type or direction</inlineHelpText>
        <label>Assessor Street Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_Street_Type__c</fullName>
        <label>Assessor Street Type</label>
        <picklist>
            <picklistValues>
                <fullName>Street</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boulevard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lane</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Place</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Road</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Court</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Highway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arcade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayou</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluffs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bottom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burgs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bypass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canyon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cape</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Causeway</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Trigger_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Attachment_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Attachment Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BoxAccessMatrixStage_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BoxAccessMatrixStage Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FeedItem_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FeedItem Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LD_Lease_trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>LD Lease trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opportunity Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>PM Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Task_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>for TaskTriggerNew</description>
        <label>Task Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>User Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Setting</label>
</CustomObject>

posiGen_FullsendBox/src/classes/TestCensusTract.cls
@isTest
public class TestCensusTract{ 
    @testSetup static void myUnitTest() {
    
    
        Account acc= new Account(
          FirstName='Test FName',
          LastName='Test LName',
          PersonMailingStreet='test@yahoo.com',
          PersonMailingPostalCode='12345',
          PersonMailingCity='SFO',
          PersonEmail='test@yahoo.com',
          PersonHomePhone='1234567',
          PersonMobilePhone='12345678' 
        );
 
        insert acc;
        
        Property__c property = new Property__c();
        property.Assessor_City__c = 'LA';
        property.Assessor_House__c = '311';
        property.Assessor_Street_Direction__c = 'ssa';
        property.Assessor_Street_Name__c = 'asasa';
        property.Assessor_Street_Type__c = 'hhh';
        property.Assessor_State__c = 'LA';
        property.name= 'Property test';
        property.Address_Line_1__c = 'asadsjds';
        property.Account__c = acc.id;
        insert property;
        
        
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Closed Won';
        opp.Census_Tract__c = null;
        opp.Property__c = property.id;
        insert opp;
        
        
        
    }
    
    static testMethod void myUnitTest2(){
        
        Opportunity opp = [select id,stageName,Census_Tract__c from opportunity][0];
        Map<Id,String> oldOppStageMap = new Map<Id,String>();
        oldOppStageMap.put(opp.id,opp.stageName);
        
        Map<Id,String> oldCensusTractMap = new Map<Id,String>();
        oldCensusTractMap.put(opp.id,opp.Census_Tract__c);
        
        Trigger_Setting__c ts = new Trigger_Setting__c(Attachment_Trigger__c=true, BoxAccessMatrixStage_Trigger__c=true, FeedItem_Trigger__c=true, LD_Lease_trigger__c=true, Opportunity_Trigger__c=true, PM_Trigger__c=true, Project_Trigger__c=true, Task_Trigger__c=true, User_Trigger__c=true );
        insert ts;
        
        //opp.stageName = 'Contracts Approved';
        //update opp;
        //System.assert(false,opp.stageName);
        
        Set<Id> oppSet = new Set<Id>();  
        oppSet.add(opp.id);
        
        Test.startTest();
        CensusTract.updateCensusTract(oppSet, oldOppStageMap, oldCensusTractMap);
        Test.stopTest();
        
    }
}