posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <externalId>true</externalId>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxUser_Id__c</fullName>
        <label>BoxUser Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFProfile_Id__c</fullName>
        <label>SFProfile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFUser_Email__c</fullName>
        <label>SFUser Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity_Collaboration_Recovery__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Opportunity Collaboration Recovery</relationshipLabel>
        <relationshipName>Opportunity_Collaboration_Recovery</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserEmail__c</fullName>
        <label>UserEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Collaboration Recovery</label>
    <nameField>
        <label>Opportunity Collaboration Recovery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Collaboration Recovery</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/InsertCollaboration.cls
public with sharing class InsertCollaboration implements Database.Batchable<Sobject>, Database.Stateful{
    
    public String folderName;
    public InsertCollaboration(String folderName){
      this.folderName = folderName; 
    } 
    
    public Database.QueryLocator start(Database.BatchableContext BC){
    
            return Database.getQueryLocator('select Sub_Folder__c, BoxCollaboration_Id__c, Profile_Id__c, UserEmail__c  from Opportunity_Collaboration_Recovery__c where Sub_Folder__r.Name =:folderName');
    }
    
    public void execute(Database.BatchableContext BC, List<Opportunity_Collaboration_Recovery__c> ocrList){
        List<Collaboration__c> NewclbList = new List<Collaboration__c>();
        Set<String> subFolderSet = new Set<String>();
        Set<String> collaborationSet = new Set<String>();
        for(Opportunity_Collaboration_Recovery__c clb:ocrList){
            subFolderSet.add(clb.Sub_folder__c);
          }
          
      for(Collaboration__c col : [select BoxCollaboration_Id__c from Collaboration__c where sub_folder__c in:subFolderSet]){
            collaborationSet.add(col.BoxCollaboration_Id__c);
        }
      for(Opportunity_Collaboration_Recovery__c ocr:ocrList) {     
           
            if(!collaborationSet.contains(ocr.BoxCollaboration_Id__c)){
                
                  Collaboration__c clb = new Collaboration__c();
                  clb.BoxUser_Id__c='';
                  clb.BoxCollaboration_Id__c = ocr.BoxCollaboration_Id__c;
                  clb.sub_folder__c= ocr.Sub_Folder__c;
                  clb.SFProfile_Id__c =ocr.Profile_Id__c;
                  clb.SFUser_Email__c =ocr.UserEmail__c;
                  NewclbList.add(clb);
                
              } 
              
            
          }
        insert  NewclbList; 
       
    }
    
    public void finish(Database.BatchableContext BC){}
}