posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <externalId>true</externalId>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxFolder_Id__c</fullName>
        <label>BoxFolder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxUser_Id__c</fullName>
        <label>BoxUser Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFProfile_Id__c</fullName>
        <label>SFProfile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFUser_Email__c</fullName>
        <label>SFUser Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Deals</relationshipLabel>
        <relationshipName>Deals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CloseDate__c</fullName>
        <label>CloseDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StageName__c</fullName>
        <label>StageName</label>
        <picklist>
            <picklistValues>
                <fullName>Schedule Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reschedule Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Input Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docusign Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docusign Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduct Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Submitted to DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Rejected by DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Contract Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Feasibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Redeploy Layout and Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Rejected by DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Rejected by UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Submitted to DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Submitted to UW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracts Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Sunrun</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feasibility Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Layout Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release to Installer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Not Feasible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Layout Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost - Cancelled After Install Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed/Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Deal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal</label>
        <referenceTo>Deal__c</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Sub_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestCollaborationSubFolderLookup.cls
@isTest
public class TestCollaborationSubFolderLookup{ 
    static testMethod void myTest1() {
    
        Account acc =new Account();
        acc.name = 'irfan khan';
        insert acc;
        
        Contact con = new Contact(FirstName='Test1',LastName='State1',email='test2@test.com',AccountId=acc.id);
        insert con;
        
        Deal__c opp = new Deal__c();       
        //opp.name = 'Test opp';
        opp.Account__c = acc.id;
        opp.CloseDate__c = date.today();
        opp.stageName__c = 'Closed Won';
        insert opp;   								
        
        List<Sub_Folder__c> lstclb = new List<Sub_Folder__c>();
        Sub_Folder__c sf = new Sub_Folder__c();
        sf.CF_Box_Folder_Id__c = '654321';
        sf.CF_Deal__c = opp.id;
        insert sf;
        lstclb.add(sf); 
        
        
        Collaboration__c collaboration = new Collaboration__c();
        collaboration.BoxCollaboration_Id__c = '123456';
        collaboration.BoxFolder_Id__c= '654321';
        collaboration.BoxGroup_Id__c = '11111';
        collaboration.BoxUser_Id__c= '22222';
        collaboration.Role__c= 'Uploader';
        collaboration.SFProfile_Id__c = '33333';
        collaboration.SFUser_Email__c = 'test2@test.com';
        collaboration.Sub_Folder__c = null;
        insert collaboration;
       
        
        CollaborationSubFolderLookup bcb = new CollaborationSubFolderLookup();
        Database.BatchableContext BC;
        
        bcb.start(BC);
        Test.startTest();
        bcb.start(BC);
        bcb.execute(BC,lstclb);
        bcb.finish(BC);
        
        
    }
}