posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxFolder_Id__c</fullName>
        <label>BoxFolder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/CollaborationSubFolderLookup.cls
public with sharing class CollaborationSubFolderLookup implements Database.Batchable<Sobject>, Database.Stateful{

    public CollaborationSubFolderLookup(){
        
    } 
    
    public Database.QueryLocator start(Database.BatchableContext BC){
    
        return Database.getQueryLocator('select id, CF_Box_Folder_Id__c from Sub_Folder__c');
    }
    
    public void execute(Database.BatchableContext BC, List<Sub_Folder__c> subFolderList){
    
        Map<String, Id> subFolderMap = new Map<String, Id>();
        for(Sub_Folder__c folder : subFolderList){
            subFolderMap.put(folder.CF_Box_Folder_Id__c, folder.id);
        }
        
        List<Collaboration__c> listToUpdate = new List<Collaboration__c>();    
        for(Collaboration__c collaboration : [select id, BoxFolder_Id__c from Collaboration__c where BoxFolder_Id__c in : subFolderMap.keyset()]){
        
            collaboration.Sub_Folder__c = subFolderMap.get(collaboration.BoxFolder_Id__c);
            listToUpdate.add(collaboration);
        }
        
        update listToUpdate;
    
    }
    
    public void finish(Database.BatchableContext BC){}
}