posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <externalId>true</externalId>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxFolder_Id__c</fullName>
        <label>BoxFolder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Collaborations</relationshipLabel>
        <relationshipName>Collaborations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity_Collaboration_Recovery__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Folder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Folder</label>
        <referenceTo>Sub_Folder__c</referenceTo>
        <relationshipLabel>Opportunity Collaboration Recovery</relationshipLabel>
        <relationshipName>Opportunity_Collaboration_Recovery</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserEmail__c</fullName>
        <label>UserEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Collaboration Recovery</label>
    <nameField>
        <label>Opportunity Collaboration Recovery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Collaboration Recovery</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Sub_Folder__c.object
<CustomObject>
    <fields>
        <fullName>CF_Box_Folder_Id__c</fullName>
        <externalId>true</externalId>
        <label>Box Folder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CF_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sub Folders</relationshipLabel>
        <relationshipName>Child_Folders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sub Folder</label>
    <nameField>
        <label>Child Folder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Folders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestInsertCollaboration.cls
@isTest
private class TestInsertCollaboration {

    static testMethod void executeTest1() {
    
        Account acc =new Account();
        acc.name = 'irfan khan';
        upsert acc;
    
        Opportunity opp = new Opportunity();
        opp.name = 'Test opp';
        opp.accountId = acc.id;
        opp.CloseDate = date.today();
        opp.stageName = 'Closed Won';
        insert opp;
    
        Sub_folder__c sf = new Sub_folder__c();
        sf.name = 'EE';
        sf.cf_opportunity__c = opp.id;
        sf.cf_box_folder_id__c = '11446498';
        insert sf;
        
        
        Opportunity_Collaboration_Recovery__c ocr = new Opportunity_Collaboration_Recovery__c();
        ocr.Sub_Folder__c = sf.id;
        ocr.BoxCollaboration_Id__c = '4545454';
        ocr.Profile_Id__c = 'feukfyskufhds';
        ocr.UserEmail__c = 'test@abc.com';
        insert ocr;
        
        List<Opportunity_Collaboration_Recovery__c> ocrList = new List<Opportunity_Collaboration_Recovery__c>();
        ocrList.add(ocr);
        
        Collaboration__c clb = new Collaboration__c();
        clb.BoxCollaboration_Id__c = '4523256';
        clb.BoxFolder_Id__c = sf.cf_box_folder_id__c;
        clb.BoxFolder_Id__c = sf.cf_box_folder_id__c;
        clb.Sub_Folder__c = sf.id;
        insert clb;
        
        Database.BatchableContext BC;
        InsertCollaboration icb = new InsertCollaboration('EE');
        
        Test.startTest();
        icb.start(bc);
        icb.execute(bc,ocrList);
        icb.finish(bc);
        Test.stopTest();
        

    }
}