posiGen_FullsendBox/src/objects/Collaboration__c.object
<CustomObject>
    <fields>
        <fullName>BoxCollaboration_Id__c</fullName>
        <externalId>true</externalId>
        <label>BoxCollaboration Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxFolder_Id__c</fullName>
        <label>BoxFolder Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BoxGroup_Id__c</fullName>
        <label>BoxGroup Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Collaboration</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Collaboration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaborations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestBatchDeleteLogRecords.cls
@isTest
public class TestBatchDeleteLogRecords{ 
    static testMethod void myUnitTest() { 
       
       List<Collaboration__c> lstclb = new List<Collaboration__c>();
       Collaboration__c clb = new Collaboration__c(BoxCollaboration_Id__c='123456',BoxFolder_Id__c='11446498',BoxGroup_Id__c=null,Role__c='Viewer');
       insert clb;
       lstclb.add(clb);
       
       BatchDeleteLogRecords bcb = new BatchDeleteLogRecords('select id, createddate from Collaboration__c','Log');
       Database.BatchableContext BC;
       
       System.test.startTest();
       bcb.start(BC);
       bcb.execute(BC,lstclb); 
       bcb.finish(BC);
       System.test.stopTest();
       
    }
}