posiGen_FullsendBox/src/objects/Customer_Portal_Global_Setting__c.object
<CustomObject>
    <fields>
        <fullName>How_To_Save_More__c</fullName>
        <description>WYSIWYG Editor to manage &quot;How do I save more money&quot; content</description>
        <label>How To Save More</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Customer Portal Global Setting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Portal Global Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/CustomerCommunity_SettingController.cls
public class CustomerCommunity_SettingController {

    public Customer_Portal_Global_Setting__c globalSetting { get; set; }
    public String howToSaveMore { get; set; }
    public Boolean standardUser { get; set; }

    public pageReference redirectToMySavings() {
        return new PageReference((standardUser?'/apex':'') + '/CustomerCommunity_MySavings');
    }
    
    public CustomerCommunity_SettingController() {
        standardUser = (UserInfo.getUserType() == 'Standard');
        globalSetting = [SELECT How_To_Save_More__c FROM Customer_Portal_Global_Setting__c LIMIT 1];
        howToSaveMore = globalSetting.How_To_Save_More__c;
    }
    
}