posiGen_FullsendBox/src/objects/Deal__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Household_Income__c</fullName>
        <inlineHelpText>Whoever fills out this field, please let your friendly neighborhood salesforce admin know. - Thank you</inlineHelpText>
        <label>Annual Household Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LMI_Eligible__c</fullName>
        <label>LMI Eligible</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>People_In_Household__c</fullName>
        <label>People In Household</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Deals At This Property</relationshipLabel>
        <relationshipName>Opportunities9</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deal</label>
    <nameField>
        <displayFormat>Deal-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Municipality__c.object
<CustomObject>
    <fields>
        <fullName>Household_Size_01__c</fullName>
        <label>Household Size 01</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Household_Size_02__c</fullName>
        <label>Household Size 02</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Household_Size_03__c</fullName>
        <label>Household Size 03</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Household_Size_04__c</fullName>
        <label>Household Size 04</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Household_Size_05__c</fullName>
        <label>Household Size 05</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Household_Size_06__c</fullName>
        <label>Household Size 06</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Household_Size_07__c</fullName>
        <label>Household Size 07</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Household_Size_08__c</fullName>
        <label>Household Size 08</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Municipality</label>
    <nameField>
        <label>Municipality Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipalities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_Household_Income__c</fullName>
        <inlineHelpText>Whoever fills out this field, please let your friendly neighborhood salesforce admin know. - Thank you</inlineHelpText>
        <label>Annual Household Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LMI_Eligible__c</fullName>
        <label>LMI Eligible</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>People_In_Household__c</fullName>
        <label>People In Household</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Property__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities At This Property</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>AHJ__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LMI AHJ</label>
        <referenceTo>Municipality__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>AHJ</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/LMITriggerHandler.cls
public with sharing class LMITriggerHandler implements ITrigger{
    
    public static boolean firstRun = true;
    // Constructor
    public LMITriggerHandler(){
          
    }
    

    /**
     * bulkBefore
     *
     * This method is called prior to execution of a BEFORE trigger. Use this to cache
     * any data required into maps prior execution of the trigger.
     */
    public void bulkBefore()
    {
       
    }
    
    public void bulkAfter()
    {
    }
    
    
    public void beforeInsert()
    {

       
    }
    
    public void beforeUpdate()
    {
        // before update will only execute for Opportunity 
        Deal__c oppError;
        try{       

            Map<integer, decimal> muncipalityValues = new Map<integer, decimal>();
            
            for(Deal__c opp : [select id, Property__r.AHJ__r.Household_Size_01__c, Property__r.AHJ__r.Household_Size_02__c, 
                                    Property__c, Property__r.AHJ__r.Household_Size_03__c, Property__r.AHJ__r.Household_Size_04__c, 
                                    Property__r.AHJ__c, Property__r.AHJ__r.Household_Size_05__c, Property__r.AHJ__r.Household_Size_06__c, 
                                    Property__r.AHJ__r.Household_Size_07__c, Property__r.AHJ__r.Household_Size_08__c, People_In_Household__c,
                                    Annual_Household_Income__c from Deal__c where id in : Trigger.New]){
                                    
                oppError = (Deal__c)Trigger.NewMap.get(opp.id);
                 if(opp.Property__c != Null && opp.Property__r.AHJ__c != Null){
                     
                         muncipalityValues.put(1, opp.Property__r.AHJ__r.Household_Size_01__c);
                         muncipalityValues.put(2, opp.Property__r.AHJ__r.Household_Size_02__c);
                         muncipalityValues.put(3, opp.Property__r.AHJ__r.Household_Size_03__c);
                         muncipalityValues.put(4, opp.Property__r.AHJ__r.Household_Size_04__c);
                         muncipalityValues.put(5, opp.Property__r.AHJ__r.Household_Size_05__c);
                         muncipalityValues.put(6, opp.Property__r.AHJ__r.Household_Size_06__c);
                         muncipalityValues.put(7, opp.Property__r.AHJ__r.Household_Size_07__c);
                         muncipalityValues.put(8, opp.Property__r.AHJ__r.Household_Size_08__c);
                     
                 }            
            }
               
            
            for(Deal__c opp: (List<Deal__c>)Trigger.New){
                oppError = opp;
                
                if(opp.Annual_Household_Income__c != Null && opp.People_in_Household__c != Null){
                
                    if(muncipalityValues.containsKey(Integer.valueOf(opp.People_in_Household__c)) &&  muncipalityValues.get(Integer.valueOf(opp.People_in_Household__c)) != Null){
                        if(opp.Annual_Household_Income__c <= muncipalityValues.get(Integer.valueOf(opp.People_in_Household__c))){
                            opp.LMI_Eligible__c= 'Yes';
                        }
                        else if(opp.Annual_Household_Income__c > muncipalityValues.get(Integer.valueOf(opp.People_in_Household__c))){
                            opp.LMI_Eligible__c = 'No';
                        } 
                    }
                    else{
                        opp.LMI_Eligible__c = Null;
                    }
                }
                else{
                    opp.LMI_Eligible__c = Null;
                } 
                
            }
        }
        catch(Exception e){
           oppError.addError(e.getMessage()+': in class LMITriggerHandler at line number - '+e.getLineNumber());
        }
    }
    
    /**
     * beforeDelete
     *
     * This method is called for records to be deleted during a BEFORE
     * trigger.
     */
    public void beforeDelete()
    {   
        
    }
    
    public void afterInsert()
    {   
        // after insert will only execute for Opportunity 
        Deal__c oppError;
        try{
        
            Map<integer, decimal> muncipalityValues = new Map<integer, decimal>();
            
            for(Deal__c opp : [select id, Property__r.AHJ__r.Household_Size_01__c, Property__r.AHJ__r.Household_Size_02__c, 
                                    Property__c, Property__r.AHJ__r.Household_Size_03__c, Property__r.AHJ__r.Household_Size_04__c, 
                                    Property__r.AHJ__c, Property__r.AHJ__r.Household_Size_05__c, Property__r.AHJ__r.Household_Size_06__c, 
                                    Property__r.AHJ__r.Household_Size_07__c, Property__r.AHJ__r.Household_Size_08__c, People_In_Household__c,
                                    Annual_Household_Income__c from Deal__c where id in : Trigger.New]){
                 
                 oppError = (Deal__c)Trigger.NewMap.get(opp.id);
                
                     if(opp.Property__c != Null && opp.Property__r.AHJ__c != Null){
                         
                             muncipalityValues.put(1, opp.Property__r.AHJ__r.Household_Size_01__c);
                             muncipalityValues.put(2, opp.Property__r.AHJ__r.Household_Size_02__c);
                             muncipalityValues.put(3, opp.Property__r.AHJ__r.Household_Size_03__c);
                             muncipalityValues.put(4, opp.Property__r.AHJ__r.Household_Size_04__c);
                             muncipalityValues.put(5, opp.Property__r.AHJ__r.Household_Size_05__c);
                             muncipalityValues.put(6, opp.Property__r.AHJ__r.Household_Size_06__c);
                             muncipalityValues.put(7, opp.Property__r.AHJ__r.Household_Size_07__c);
                             muncipalityValues.put(8, opp.Property__r.AHJ__r.Household_Size_08__c);
                         
                    }
                
                                  
            }     
            
            List<Deal__c> oppList = new List<Deal__c>();
            for(Deal__c opp: [select id, Property__r.AHJ__r.Household_Size_01__c, Property__r.AHJ__r.Household_Size_02__c, 
                                    Property__c, Property__r.AHJ__r.Household_Size_03__c, Property__r.AHJ__r.Household_Size_04__c, 
                                    Property__r.AHJ__c, Property__r.AHJ__r.Household_Size_05__c, Property__r.AHJ__r.Household_Size_06__c, 
                                    Property__r.AHJ__r.Household_Size_07__c, Property__r.AHJ__r.Household_Size_08__c, People_In_Household__c,
                                    Annual_Household_Income__c from Deal__c where id in : Trigger.New]){
                                    
                oppError = (Deal__c)Trigger.NewMap.get(opp.id);
                
                if(opp.Annual_Household_Income__c != Null && opp.People_in_Household__c != Null){
                
                    if(muncipalityValues.containsKey(Integer.valueOf(opp.People_in_Household__c)) &&  muncipalityValues.get(Integer.valueOf(opp.People_in_Household__c)) != Null){
                        if(opp.Annual_Household_Income__c <= muncipalityValues.get(Integer.valueOf(opp.People_in_Household__c))){
                            opp.LMI_Eligible__c= 'Yes';
                        }
                        else if(opp.Annual_Household_Income__c > muncipalityValues.get(Integer.valueOf(opp.People_in_Household__c))){
                            opp.LMI_Eligible__c = 'No';
                        } 
                    }
                    else{
                        opp.LMI_Eligible__c = Null;
                    }
                }
                else{
                    opp.LMI_Eligible__c = Null;
                }
                
                oppList.add(opp); 
                
            }
            
            update oppList;   
        
        }
        catch(Exception e){
            
            oppError.addError(e.getMessage()+': in class LMITriggerHandler at line number - '+e.getLineNumber());
        }
        
        
    }
    
    public void afterUpdate()
    {
    
        // after update will only execute for property 
        
        Deal__c oppError;
        try{
        
            Set<id> oppIds = new Set<id>();
            for(Deal__c opp: [select id from Deal__c where property__c in : Trigger.New]){
                 oppIds.add(opp.id);
            }
        
            Map<integer, decimal> muncipalityValues = new Map<integer, decimal>();
            for(Deal__c opp : [select id, Property__r.AHJ__r.Household_Size_01__c, Property__r.AHJ__r.Household_Size_02__c, 
                                    Property__c, Property__r.AHJ__r.Household_Size_03__c, Property__r.AHJ__r.Household_Size_04__c, 
                                    Property__r.AHJ__c, Property__r.AHJ__r.Household_Size_05__c, Property__r.AHJ__r.Household_Size_06__c, 
                                    Property__r.AHJ__r.Household_Size_07__c, Property__r.AHJ__r.Household_Size_08__c, People_In_Household__c,
                                    Annual_Household_Income__c from Deal__c where id in : oppIds]){
                 
                 oppError = (Deal__c)Trigger.NewMap.get(opp.id);
                
                     if(opp.Property__c != Null && opp.Property__r.AHJ__c != Null){
                         
                             muncipalityValues.put(1, opp.Property__r.AHJ__r.Household_Size_01__c);
                             muncipalityValues.put(2, opp.Property__r.AHJ__r.Household_Size_02__c);
                             muncipalityValues.put(3, opp.Property__r.AHJ__r.Household_Size_03__c);
                             muncipalityValues.put(4, opp.Property__r.AHJ__r.Household_Size_04__c);
                             muncipalityValues.put(5, opp.Property__r.AHJ__r.Household_Size_05__c);
                             muncipalityValues.put(6, opp.Property__r.AHJ__r.Household_Size_06__c);
                             muncipalityValues.put(7, opp.Property__r.AHJ__r.Household_Size_07__c);
                             muncipalityValues.put(8, opp.Property__r.AHJ__r.Household_Size_08__c);
                         
                    }
                
                                  
            }     
            
            List<Deal__c> oppList = new List<Deal__c>();
            for(Deal__c opp: [select id, Property__r.AHJ__r.Household_Size_01__c, Property__r.AHJ__r.Household_Size_02__c, 
                                    Property__c, Property__r.AHJ__r.Household_Size_03__c, Property__r.AHJ__r.Household_Size_04__c, 
                                    Property__r.AHJ__c, Property__r.AHJ__r.Household_Size_05__c, Property__r.AHJ__r.Household_Size_06__c, 
                                    Property__r.AHJ__r.Household_Size_07__c, Property__r.AHJ__r.Household_Size_08__c, People_In_Household__c,
                                    Annual_Household_Income__c from Deal__c where id in : oppIds]){
                                    
                oppError = (Deal__c)Trigger.NewMap.get(opp.id);
                
                if(opp.Annual_Household_Income__c != Null && opp.People_in_Household__c != Null){
                
                    if(muncipalityValues.containsKey(Integer.valueOf(opp.People_in_Household__c)) &&  muncipalityValues.get(Integer.valueOf(opp.People_in_Household__c)) != Null){
                        if(opp.Annual_Household_Income__c <= muncipalityValues.get(Integer.valueOf(opp.People_in_Household__c))){
                            opp.LMI_Eligible__c= 'Yes';
                        }
                        else if(opp.Annual_Household_Income__c > muncipalityValues.get(Integer.valueOf(opp.People_in_Household__c))){
                            opp.LMI_Eligible__c = 'No';
                        } 
                    }
                    else{
                        opp.LMI_Eligible__c = Null;
                    }
                }
                else{
                    opp.LMI_Eligible__c = Null;
                }
                
                oppList.add(opp); 
                
            }
            
            update oppList;   
        
        }
        catch(Exception e){
            
            oppError.addError(e.getMessage()+': in class LMITriggerHandler at line number - '+e.getLineNumber());
        }
    }
    
    public void afterDelete()
    {
    }
    
    public void afterUnDelete()
    {
    }
    
    /**
     * andFinally
     *
     * This method is called once all records have been processed by the trigger. Use this 
     * method to accomplish any final operations such as creation or updates of other records.
     */
    public void andFinally()
    {
        
    }
}