posiGen_FullsendBox/src/objects/EE_Upgrade__c.object
<CustomObject>
    <fields>
        <fullName>Energy_Audit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Energy Audit</label>
        <referenceTo>Energy_Audit__c</referenceTo>
        <relationshipLabel>EE Upgrade Performed</relationshipLabel>
        <relationshipName>EE_Upgrade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Api_Name__c</fullName>
        <label>Field Api Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EE Upgrade</label>
    <nameField>
        <displayFormat>EE-{00000000}</displayFormat>
        <label>EE Upgrade Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EE Upgrade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Energy_Audit__c.object
<CustomObject>
    <fields>
        <fullName>AirFilters_QTY__c</fullName>
        <label>Air Filters(QTY)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Air_Attic_Scuttle_Hole_Insulation_EA_QTY__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Attic Scuttle Hole Insulation EA(QTY)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Energy Audit</label>
    <nameField>
        <label>Energy Audit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Energy Audit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/EnergyAuditTriggerTest.cls
@isTest
private class EnergyAuditTriggerTest {
    static testMethod void unitTest(){
        Energy_Audit__c energyAudit = new Energy_Audit__c();
        energyAudit.Air_Attic_Scuttle_Hole_Insulation_EA_QTY__c = 2;
        energyAudit.AirFilters_QTY__c = 3;
        insert energyAudit;
        system.assert(energyAudit.id != null);
        
        EE_Upgrade__c eeUpgrade = new EE_Upgrade__c();
        eeUpgrade.Energy_Audit__c =  energyAudit.id;
        eeUpgrade.Field_Api_Name__c = 'AirFilters_QTY__c';
        insert eeUpgrade;
        system.assert(eeUpgrade.id != null);
        
        energyAudit.AirFilters_QTY__c = 2;
        energyAudit.Air_Attic_Scuttle_Hole_Insulation_EA_QTY__c = 3;
        update energyAudit;
        
    }
}