posiGen_FullsendBox/src/objects/Issue__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Issues (Case)</relationshipLabel>
        <relationshipName>Issues1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Issue</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Issue_Comment__c.object
<CustomObject>
    <fields>
        <fullName>Case_Comment_Id__c</fullName>
        <label>Case Comment Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Created_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Created By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Issue_Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_Date_Time__c</fullName>
        <label>Created Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Issue__c</fullName>
        <label>Issue</label>
        <referenceTo>Issue__c</referenceTo>
        <relationshipLabel>Issue Comments</relationshipLabel>
        <relationshipName>Issue_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Issue Comment</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>Issue Comment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/Batch_SyncCaseCommentToIssueComment.cls
global without sharing class Batch_SyncCaseCommentToIssueComment implements Database.Batchable<sObject>{
    
    /*
    	Goal of this batch is to generate the Issue Comment records from the Case Comments.
    	Do not run this batch consecutively. Doing so will create duplicate Issue Comment records. Issue Comments are not linked to Case Comments.
    
    */
    
    global Database.QueryLocator start(Database.BatchableContext BC){
		return Database.getQueryLocator('SELECT Id, CommentBody, CreatedById, CreatedDate, ParentId FROM CaseComment');
	}
	
	global void execute(Database.BatchableContext BC, List<CaseComment> scope){
		Set<Id> caseIds = new Set<Id>();
		Set<Id> caseCommentIds = new Set<Id>();
		Issue__c[] queriedIssues = new Issue__c[]{};
		Map<Id, Id> caseIdToIssueId = new Map<Id, Id>();
		Map<Id, Id> caseCommentIdToExistingIssueCommentIdMap = new Map<Id, Id>();
		Issue_Comment__c[] issueCommentToInsert = new Issue_Comment__c[]{};
		
		if(scope.size() > 0){
			
			//create set of case ids and set of case comment ids
			for(CaseComment l : scope){
				caseIds.add(l.ParentId);
				caseCommentIds.add(l.Id);
			}
			
			//query issue records
			queriedIssues = [SELECT Id, Case__c FROM Issue__c WHERE Case__c IN: caseIds];
			
			//create set of issue ids
			for(Issue__c i : queriedIssues){
				caseIdToIssueId.put(i.Case__c, i.Id);
			}
			
			//query existing issue comment records and add to map to be used for preventing creation of dupes
			for(Issue_Comment__c ic : [SELECT Id, Case_Comment_Id__c FROM Issue_Comment__c WHERE Case_Comment_Id__c IN: caseCommentIds]){
				caseCommentIdToExistingIssueCommentIdMap.put(ic.Case_Comment_Id__c, ic.Id);
			}
			
			//loop over case comments
			for(CaseComment cc : scope){
				if(!caseCommentIdToExistingIssueCommentIdMap.containsKey(cc.Id)){ //skip if issue comment already exists
					Issue_Comment__c ic = new Issue_Comment__c();
					
					ic.Comment__c = cc.CommentBody;
					ic.Created_By__c = cc.CreatedById;
					ic.Created_Date_Time__c = cc.CreatedDate;
					ic.Issue__c = caseIdToIssueId.get(cc.ParentId);
					ic.Case_Comment_Id__c = cc.Id;
					
					issueCommentToInsert.add(ic);
				}
			}
			
			insert issueCommentToInsert;
			
			
			
		/*Old bad code here.
			//create set of case ids
			for(CaseComment l : scope){
				caseIds.add(l.ParentId);
			}
			
			//query issue records
			queriedIssues = [SELECT Id, Case__c FROM Issue__c WHERE Case__c IN: caseIds];
			
			//create set of issue ids
			for(Issue__c i : queriedIssues){
				caseIdToIssueId.put(i.Case__c, i.Id);
			}
			
			//query existing issue comments
			existingIssueComments = [SELECT Id, Issue__r.Case__c FROM Issue_Comment__c WHERE Issue__c IN: caseIdToIssueId.values()];
			
			//create map of case id to issue comment
			for(Issue_Comment__c c : existingIssueComments){
				caseIdToExistingIssueComment.put(c.Issue__r.Case__c, c);
			}
			
			//loop over case comments
			for(CaseComment cc : scope){
				Issue_Comment__c ic = new Issue_Comment__c();
				
				//if issue comment already exists, then sync it
				if(caseIdToExistingIssueComment.containsKey(cc.ParentId)){ //verifies if the case related to the case comment matches with an existing issue comments related issue record that relates to the same case
					ic = caseIdToExistingIssueComment.get(cc.ParentId);
					
					ic.Comment__c = cc.CommentBody;
					ic.Created_By__c = cc.CreatedById;
					ic.Created_Date_Time__c = cc.CreatedDate;
					
					issueCommentsToUpsert.add(ic);
				}
				//otherwise create a new one
				else{
					ic.Comment__c = cc.CommentBody;
					ic.Created_By__c = cc.CreatedById;
					ic.Created_Date_Time__c = cc.CreatedDate;
					ic.Issue__c = caseIdToIssueId.get(cc.ParentId);
					
					issueCommentsToUpsert.add(ic);
				}
			}
			
			//upsert issue comments
			upsert issueCommentsToUpsert;
			*/
		}
	}
	
	global void finish(Database.BatchableContext BC){
		//nothing to do here!
	}
	
	global static void byPassTest(){
		integer i = 0;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
		i++;
	}
}