posiGen_FullsendBox/src/objects/LD_Lease__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>Account the record is related to.</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>LD Leases</relationshipLabel>
        <relationshipName>LD_Leases</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>The Opportunity this LD Lease is related to.</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>LD Leases</relationshipLabel>
        <relationshipName>LD_Leases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>LD Lease</label>
    <nameField>
        <label>LD Lease Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LD Leases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$UserRole.Name</field>
                <operation>equals</operation>
                <value>Project Manager</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_User_Project_Manager_For</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/AccountDetailsControllerTest.cls
@isTest
class AccountDetailsControllerTest{

    @testSetup
    static void dataSetup() {
    
     Account acc= new Account(name='test1');
     insert acc;
     
     Opportunity opp = new Opportunity(name='test1', accountId=acc.Id, StageName='Schedule Appointment', Project_Manager__c=UserInfo.getUserId(), CloseDate=system.today());
     insert opp;
     
     Contact conTest= new Contact (
        FirstName = 'xyzFirst',
        LastName = 'XyZLast',
        //line changed - waveoc
        AccountId = acc.Id,
        Email = 'xyzmail@mail.com'
     );
     insert conTest;
     
     Case caseObj = new Case(
        ContactId = conTest.Id,
        AccountId = acc.Id,
        Status = 'Working',
        Origin = 'Phone'
     );
     insert caseObj; 
     
     //LD_Lease__c leaseTest= new LD_Lease__c(opportunity__c=opp.Id, Account__c= acc.Id);
     //insert leaseTest;
            
    }

    static testMethod void method1(){ 

        String accId= [Select id From Account].Id;
        AccountDetailsController adc= new AccountDetailsController();  
        adc.loadAccounts();
        adc.accountId= accId;  
        adc.getAccountDetails();
        
        adc.selAcc = '11-30';
        adc.loadAccounts();
        adc.selAcc = '31-60';
        adc.loadAccounts();
        adc.selAcc = '61-90';
        adc.loadAccounts(); 
        adc.selAcc = '91-180';
        adc.loadAccounts();
        adc.selAcc = '181-200';
        adc.loadAccounts();   
        
        adc.selMan ='I am Account Manager';
        adc.selAcc = '11-30';
        adc.loadAccounts();
        adc.selAcc = '31-60';
        adc.loadAccounts();
        adc.selAcc = '61-90';
        adc.loadAccounts(); 
        adc.selAcc = '91-180';
        adc.loadAccounts();  
        adc.selAcc = '181-200';
        adc.loadAccounts(); 
         
        adc.resetAccs();
    }
}