posiGen_FullsendBox/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Application_MTD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Application this month</description>
        <label>Application MTD</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_MTD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Approved this month</description>
        <label>Approved MTD</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assess_Req_MTD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Assess Requested this month</description>
        <label>Assess Req MTD</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Assessed_Feas_MTD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Assessed Feasible this month</description>
        <label>Assessed Feas MTD</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Closed_MTD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Closed this month</description>
        <label>Closed MTD</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_MTD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Opened this month</description>
        <label>Open MTD</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Signed_MTD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Signed this month</description>
        <label>Signed MTD</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submitted_MTD__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Submitted this month</description>
        <label>Submitted MTD</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/EPClearLeadStageMTD.cls
global class EPClearLeadStageMTD implements Database.Batchable<sObject>, Schedulable {
	String query;
	
	/** Database Batchable Methods that need to be implemented **/
	//START METHOD
	global Database.queryLocator start(Database.BatchableContext bc){
		return Database.getQueryLocator(query);
	}
	
	//EXECUTE METHOD
	global void execute(Database.BatchableContext bc, List<Lead> scope) {
         for(Lead l : scope){ 
           l.OPEN_MTD__C = 0; 
           l.APPLICATION_MTD__C = 0; 
           l.SIGNED_MTD__C = 0; 
           l.SUBMITTED_MTD__C = 0; 
           l.APPROVED_MTD__C = 0; 
           l.Assess_Req_MTD__c = 0;
           l.Assessed_Feas_MTD__c = 0;
           l.Closed_MTD__c = 0; 
       } 
        update scope;
	}

	//FINISH METHOD
	global void finish(Database.BatchableContext bc){
		System.debug(LoggingLevel.INFO,'\n\n***** The EPClearLeadStageMTD Batchable class is completed. *****\n\n');
	}
	
	global void execute(SchedulableContext sc){
		String soql = 'SELECT ID, OPEN_MTD__C, APPLICATION_MTD__C, SIGNED_MTD__C, SUBMITTED_MTD__C, APPROVED_MTD__C, Assess_Req_MTD__c, Assessed_Feas_MTD__c, Closed_MTD__c FROM LEAD WHERE (OPEN_MTD__C = 1 OR APPLICATION_MTD__C = 1 OR SIGNED_MTD__C = 1 OR SUBMITTED_MTD__C = 1  OR APPROVED_MTD__C = 1 OR Assess_Req_MTD__c = 1 OR Assessed_Feas_MTD__c = 1 OR Closed_MTD__c = 1) and isConverted=false';
		EPClearLeadStageMTD epClearLS_MTD = new EPClearLeadStageMTD();
		epClearLS_MTD.query = soql;
		Id batchId = Database.executeBatch(epClearLS_MTD);
	}
    
        @isTest(SeeAllData=true)
	static public void testCodeCoverage() {
		Test.startTest();
		//generate leads
		CreateTestUser();
        
		String soql = 'SELECT ID, OPEN_MTD__C, APPLICATION_MTD__C, SIGNED_MTD__C, SUBMITTED_MTD__C, APPROVED_MTD__C, Assess_Req_MTD__c, Assessed_Feas_MTD__c, Closed_MTD__c FROM LEAD WHERE (OPEN_MTD__C = 1 OR APPLICATION_MTD__C = 1 OR SIGNED_MTD__C = 1 OR SUBMITTED_MTD__C = 1  OR APPROVED_MTD__C = 1 OR Assess_Req_MTD__c = 1 OR Assessed_Feas_MTD__c = 1 OR Closed_MTD__c = 1) and isConverted=false LIMIT 200';
		EPClearLeadStageMTD epClearLS_MTD = new EPClearLeadStageMTD();
		epClearLS_MTD.query = soql;
		Id batchId = Database.executeBatch(epClearLS_MTD);
		
		Test.stopTest();
	}
	
	static private void CreateTestUser(){
		List<Lead> testLeads = new List<Lead>();
		for(Integer i = 0; i<200; i++){
			Lead a = new Lead(FirstName='Test',LastName='Test',Street='Mystreet',City='myCity',State='North Carolina',Country='United States',PostalCode='28202',IsConverted=FALSE,Company='Test'+i,Status = 'Open',OPEN_MTD__C = 1,Email='test'+Datetime.now().format('MM-dd-yyyy-hhmmss')+'@test.com');
			testLeads.add(a);
		}
		insert testLeads;
	}
}