posiGen_FullsendBox/src/objects/Login_access__c.object
<CustomObject>
    <fields>
        <fullName>EndPointUrl__c</fullName>
        <label>EndPointUrl</label>
        <length>175</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>175</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>175</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>security_token__c</fullName>
        <label>security token</label>
        <length>175</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>Login access</label>
    <nameField>
        <label>Login access Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logins access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestExplicitLogin.cls
@isTest
public class TestExplicitLogin { 
    static testMethod void myUnitTest1() { 
        Login_access__c mts = new Login_access__c();
        mts.EndPointUrl__c = 'test';
        mts.Password__c = 'test';
        mts.security_token__c = 'test';
        mts.Username__c = 'test';
        insert mts;
        
        ExplicitLogin fe = new ExplicitLogin();
        ExplicitLoginMock exMock = new ExplicitLoginMock();
        Test.StartTest(); 
        Test.setMock(HttpCalloutMock.class, exMock);
        ExplicitLogin.login();
        Test.stopTest();
    }
}