posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact_Reference_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Reference 1</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Contact Reference 1)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Reference_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Reference 2</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Contact Reference 2)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Secondary Applicant)</relationshipLabel>
        <relationshipName>Opportunities0</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/TestCustomerApplicationFormController.cls
@isTest
public class TestCustomerApplicationFormController{
  
  public static testmethod void Test1(){
     
        Account acc =new Account();
        acc.name = 'irfan khan';
        insert acc;
    
        List<String> opplst = new List<String>{'AccountId',
        'Secondary_Applicant__c',
        'Contact_Reference_1__c',
        'Contact_Reference_2__c'};
        
        
        Contact con = new Contact(LastName='Ly', FirstName='Tung',Email='tly@abc.com');
        insert con;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test OPP';
        opp.StageName ='Closed Won';
        opp.CloseDate= date.Today();
        opp.AccountId = acc.id;
        opp.Secondary_Applicant__c=con.id;
        opp.Contact_Reference_1__c=con.id;
        insert opp;
       
       
        
        
        
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        CustomerApplicationFormController  caf= new CustomerApplicationFormController(sc);
        caf.save();
        caf.cancel();
     
  
  }
 public static testmethod void Test2(){
     
        Account acc =new Account();
        acc.name = 'irfan khan';
        insert acc; 
    
        List<String> opplst = new List<String>{'AccountId',
        'Secondary_Applicant__c',
        'Contact_Reference_1__c',
        'Contact_Reference_2__c'};
        
        Opportunity opp = new Opportunity();
       
        
        Contact con = new Contact(LastName='Ly', FirstName='Tung',Email='tly@abc.com');
        insert con;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        CustomerApplicationFormController  caf= new CustomerApplicationFormController(sc);
        caf.save();
       // caf.cancel(); 
  }
 
  public static testmethod void Test3(){
     
        Account acc =new Account();
        acc.name = 'irfan khan';
        
    
        List<String> opplst = new List<String>{'AccountId',
        'Secondary_Applicant__c',
        'Contact_Reference_1__c',
        'Contact_Reference_2__c'};
        
        Contact con = new Contact(LastName='Ly', FirstName='Tung',Email='tly@abc.com');
        
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test OPP';
        opp.StageName ='Closed Won';
        opp.CloseDate= date.Today();
        opp.AccountId = acc.id;
        opp.Secondary_Applicant__c=con.id;
        opp.Contact_Reference_1__c=con.id;
        insert opp;
        
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        CustomerApplicationFormController  caf= new CustomerApplicationFormController(sc);
        caf.save();
       // caf.cancel(); 
  } 


}