posiGen_FullsendBox/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>R_P_Removal_Date__c</fullName>
        <label>R &amp; P Removal Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>R_P_Removal_Date__c</fullName>
        <label>R&amp;P Removal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>System_Removed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System To Remove</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Systems__c.Name</field>
                <operation>startsWith</operation>
                <value>S</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Systems__c</referenceTo>
        <relationshipLabel>Removal Project</relationshipLabel>
        <relationshipName>Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System</label>
        <referenceTo>Systems__c</referenceTo>
        <relationshipLabel>Service Call Projects</relationshipLabel>
        <relationshipName>Service_Call_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/System_Channel__c.object
<CustomObject>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <referenceTo>Systems__c</referenceTo>
        <relationshipLabel>System Channels</relationshipLabel>
        <relationshipName>System_Channels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>System Channel</label>
    <nameField>
        <label>System Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Channels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/System_PV_Production__c.object
<CustomObject>
    <fields>
        <fullName>Production_W__c</fullName>
        <label>Daily Rollup (W)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_Channel__c</fullName>
        <label>System Channel</label>
        <referenceTo>System_Channel__c</referenceTo>
        <relationshipName>System_PV_Monthly_Production_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <referenceTo>Systems__c</referenceTo>
        <relationshipName>System_PV_Monthly_Production_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>System PV Production</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Production ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System PV Production Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Systems__c.object
<CustomObject>
    <fields>
        <fullName>Install_Project_Created_On__c</fullName>
        <inlineHelpText>This is the install project the system was initially created on.</inlineHelpText>
        <label>Install Project Created On</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>PV Install</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Systems Created For This Install</relationshipLabel>
        <relationshipName>Systems_Created_For_This_Install</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>System_Removal_Date__c</fullName>
        <label>System Removal Date</label>
        <type>Date</type>
    </fields>
    <label>System</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Systems Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <description>Main Record Type</description>
        <label>System</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/ZD_Tests.cls
@isTest
private class ZD_Tests {

    static testMethod void projectTriggerTest() {
        test.startTest();

        // create a new account
        Account oAccount = new Account(Name = 'ZD Test');
        insert oAccount;
        
        // create an opportunity
        
        // get any opportunity stage
        List<OpportunityStage> lStage = [SELECT Id FROM OpportunityStage WHERE Id != NULL LIMIT 1]; 
        if(lStage.size() < 1) {
            throw new ZD_Exception('Error stage');
        }
        Id nStageId = lStage[0].Id;
        
        Opportunity oOpportunity = new Opportunity(
            Name = 'ZD Test',
            Account = oAccount,
            StageName = nStageId,
            CloseDate = date.today()
        );
        insert oOpportunity;
        
        // get Project record types
        Map<ID,RecordType> mRecordTypes = new Map<ID,RecordType>([Select ID, Name From RecordType Where sObjectType = 'Project__c']);
        
        // create an install project
        Project__c oInstallProject = null;
        for(String sId : mRecordTypes.keySet())
        {
            if(mRecordTypes.get(sId).name.containsIgnoreCase('PV Install'))
            {
                oInstallProject = new Project__c(RecordTypeId = sId, Opportunity__c = oOpportunity.Id);
                break;
            }
        }
        insert oInstallProject;
        
        // create a system        
        Systems__c oSystem = new Systems__c(Install_Project_Created_On__c = oInstallProject.Id);
        insert oSystem;
        
        // create a removal project that is linked to system        
        Project__c oRemovalProject = null;
        for(String sId : mRecordTypes.keySet())
        {
            if(mRecordTypes.get(sId).name.containsIgnoreCase('PV Removal'))
            {
         		oRemovalProject = new Project__c(RecordTypeId = sId, Opportunity__c = oOpportunity.Id, System_Removed__c = oSystem.Id, R_P_Removal_Date__c = date.today());
                break;
            }
        }
        insert oRemovalProject;
        
        // assert that project removal date is stored on system object
        Systems__c oUpdatedSystem = [SELECT Id, System_Removal_Date__c FROM Systems__c WHERE Id = :oSystem.Id];
                
        System.assert(oUpdatedSystem.System_Removal_Date__c == date.today());
                
        test.stopTest();
    }
    
    static testMethod void systemEfficiencyTest() {
        test.startTest();
        
        // create a new account
        Account oAccount = new Account(Name = 'ZD Test');
        insert oAccount;
        
        // create an opportunity
        
        // get any opportunity stage
        List<OpportunityStage> lStage = [SELECT Id FROM OpportunityStage WHERE Id != NULL LIMIT 1]; 
        if(lStage.size() < 1) {
            throw new ZD_Exception('Error stage');
        }
        Id nStageId = lStage[0].Id;
        
        Opportunity oOpportunity = new Opportunity(
            Name = 'ZD Test',
            Account = oAccount,
            StageName = nStageId,
            CloseDate = date.today()
        );
        insert oOpportunity;
        
        // get Project record types
        Map<ID,RecordType> mRecordTypes = new Map<ID,RecordType>([Select ID, Name From RecordType Where sObjectType = 'Project__c']);
        
        // create an install project
        Project__c oInstallProject = null;
        for(String sId : mRecordTypes.keySet())
        {
            if(mRecordTypes.get(sId).name.containsIgnoreCase('PV Install'))
            {
                oInstallProject = new Project__c(RecordTypeId = sId, Opportunity__c = oOpportunity.Id);
                break;
            }
        }
        insert oInstallProject;
        
        // create a system        
        Systems__c oSystem = new Systems__c(Install_Project_Created_On__c = oInstallProject.Id);
        insert oSystem;
        
        // create a system channel
        System_Channel__c oSystemChannel = new System_Channel__c(System__c = oSystem.Id);
        insert oSystemChannel;
        
        // create sysem PV Production
        System_PV_Production__c oSystemProduction = new System_PV_Production__c(System__c = oSystem.Id, Production_W__c = 25, System_Channel__c = oSystemChannel.Id);
        insert oSystemProduction;
        
        // set system id GET parameter
        ApexPages.currentPage().getParameters().put('id', oSystem.Id);
             
        // as long as we throw no exceptions there are no errors
        ZD_System_Detail_Controller controller = new ZD_System_Detail_Controller();
        
        test.stopTest();
    }
    
    /*
    static testMethod void projectExtensionTest() {
        test.startTest();
        
        // create a new account
        Account oAccount = new Account(Name = 'ZD Test');
        insert oAccount;
        
        // create an opportunity
        
        // get any opportunity stage
        List<OpportunityStage> lStage = [SELECT Id FROM OpportunityStage WHERE Id != NULL LIMIT 1]; 
        if(lStage.size() < 1) {
            throw new ZD_Exception('Error stage');
        }
        Id nStageId = lStage[0].Id;
        
        Opportunity oOpportunity = new Opportunity(
            Name = 'ZD Test',
            Account = oAccount,
            StageName = nStageId,
            CloseDate = date.today()
        );
        insert oOpportunity;
        
        // get Project record types
        Map<ID,RecordType> mRecordTypes = new Map<ID,RecordType>([Select ID, Name From RecordType Where sObjectType = 'Project__c']);
        
        // create an install project
        Project__c oInstallProject = null;
        for(String sId : mRecordTypes.keySet())
        {
            if(mRecordTypes.get(sId).name.containsIgnoreCase('PV Install'))
            {
                oInstallProject = new Project__c(RecordTypeId = sId, Opportunity__c = oOpportunity.Id);
                break;
            }
        }
        insert oInstallProject;
        
        // create a system        
        Systems__c oSystem = new Systems__c(Install_Project_Created_On__c = oInstallProject.Id);
        insert oSystem;
        
        // create a system channel
        System_Channel__c oSystemChannel = new System_Channel__c(System__c = oSystem.Id);
        insert oSystemChannel;
        
        // create sysem PV Production
        System_PV_Production__c oSystemProduction = new System_PV_Production__c(System__c = oSystem.Id, Production_W__c = 25, System_Channel__c = oSystemChannel.Id);
        insert oSystemProduction;
        
        // create an ee assessment project
        Project__c oAssessmentProject = null;
        for(String sId : mRecordTypes.keySet())
        {
            if(mRecordTypes.get(sId).name.containsIgnoreCase('EE Assessment'))
            {
                oAssessmentProject = new Project__c(RecordTypeId = sId, Opportunity__c = oOpportunity.Id);
                break;
            }
        }
        insert oAssessmentProject;
        
        // create standard controller
        ApexPages.StandardController oStandardController = new ApexPages.StandardController(oAssessmentProject);
        
        // create controller extension
        ZD_EEProject_System_Controller oController = new ZD_EEProject_System_Controller(oStandardController);
        
        oController.getSystemId();
        
        test.stopTest();
    }
	*/
}