posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Building_Permit_Received_Date__c</fullName>
        <label>Building Permit Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Electrical_Permit_Received_Date__c</fullName>
        <label>Electrical Permit Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Informed_Net_Meter_Installed_Date__c</fullName>
        <inlineHelpText>This is the date that PG was informed the Net Meter has been installed.</inlineHelpText>
        <label>Informed Net Meter Installed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Net_Meter_Install_Scheduled_Date__c</fullName>
        <inlineHelpText>This is the date the Utility Company tell us the Net Meter will be installed.</inlineHelpText>
        <label>Net Meter Install Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Net_Meter_Status__c</fullName>
        <label>Net Meter Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Set</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Net Meter Install Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Requesting Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Address Discrepancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid NMIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid Electricity Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foreclosure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House Fire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Informed Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verified Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Final Inspection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Production Analyses.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Install Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Utility Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Unable To Access Meter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Net Meter</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PVI_Electrical_Installed_Date__c</fullName>
        <label>PVI Electrical Installed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PVI_Placed_In_Service_Date__c</fullName>
        <description>This is the date that the subcontractor installs the electrical (which is the final portion) of the PV system.</description>
        <inlineHelpText>This is the date that the subcontractor installs the electrical (which is the final portion) of the PV system and declares it &quot;Placed in Service&quot;.</inlineHelpText>
        <label>PVI Placed In Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PVI_Rails_Installed_Date__c</fullName>
        <label>PVI Rails Installed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QC_Date__c</fullName>
        <inlineHelpText>Date the QC was completed</inlineHelpText>
        <label>QC Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QC_Passed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check box if install has passed acceptance test</inlineHelpText>
        <label>QC Passed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>R_P_Reinstall_Date__c</fullName>
        <description>Rip and Repair Reinstall Date</description>
        <label>R&amp;P Reinstall Date:</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System</label>
        <referenceTo>Systems__c</referenceTo>
        <relationshipLabel>Service Call Projects</relationshipLabel>
        <relationshipName>Service_Call_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/System_Channel__c.object
<CustomObject>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <referenceTo>Systems__c</referenceTo>
        <relationshipLabel>System Channels</relationshipLabel>
        <relationshipName>System_Channels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>System Channel</label>
    <nameField>
        <label>System Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Channels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/System_PV_Production__c.object
<CustomObject>
    <fields>
        <fullName>DateTime__c</fullName>
        <label>DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Energy_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Energy Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model_W__c</fullName>
        <description>The modeled amount of production, currently calculated by PowerDash.</description>
        <label>Model (W)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Production_W__c</fullName>
        <label>Daily Rollup (W)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_Channel__c</fullName>
        <label>System Channel</label>
        <referenceTo>System_Channel__c</referenceTo>
        <relationshipName>System_PV_Monthly_Production_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <referenceTo>Systems__c</referenceTo>
        <relationshipName>System_PV_Monthly_Production_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>System PV Production</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Production ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System PV Production Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Systems__c.object
<CustomObject>
    <fields>
        <fullName>Install_Project_Created_On__c</fullName>
        <inlineHelpText>This is the install project the system was initially created on.</inlineHelpText>
        <label>Install Project Created On</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>PV Install</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Systems Created For This Install</relationshipLabel>
        <relationshipName>Systems_Created_For_This_Install</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>System</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Systems Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <description>Main Record Type</description>
        <label>System</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/ZD_System_Detail_Controller.cls
public class ZD_System_Detail_Controller {
        
    // *** Variables
   
    public Systems__c m_oSystem {
    	get { return m_oSystem; }
      	set { m_oSystem = value; }
    }    
    
    // Energy Production
    
    public List<Double> m_lACEnergyKwh {
    	get { return m_lACEnergyKwh; }
      	set { m_lACEnergyKwh = value; }
    }
    public Double m_dACEnergyTotalKwh {
    	get { return m_dACEnergyTotalKwh; }
      	set { m_dACEnergyTotalKwh = value; }
    }
    public List<Double> m_lEnergyValueDollar {
    	get { return m_lEnergyValueDollar; }
      	set { m_lEnergyValueDollar = value; }
   	}
    public Double m_dEnergyValueTotalDollar {
    	get { return m_dEnergyValueTotalDollar; }
      	set { m_dEnergyValueTotalDollar = value; }
    }
    
    // PV Install
    
    public Project__c m_oInstallProject {
    	get { return m_oInstallProject; }
      	set { m_oInstallProject = value; }        
    }
    
    // *** Methods
    
	public ZD_System_Detail_Controller() {
           
        m_dACEnergyTotalKwh = 0;
        m_dEnergyValueTotalDollar = 0;
        
        try {
        	// get values for energy production     
        
            String sId = ApexPages.currentPage().getParameters().get('id');
            if(sId == null)
                throw new ZD_Exception('No System ID Parameter');
            
            Integer nYear = System.Today().year();
            if(ApexPages.currentPage().getParameters().get('year') != null)
                nYear = Integer.valueOf(ApexPages.currentPage().getParameters().get('year'));
            
            // get the System object
            m_oSystem = [SELECT Id, Name, Install_Project_Created_On__c FROM Systems__c 
                        WHERE Id = :sId];
                        
            
            // get values for PV Install             
            String sProjectId = m_oSystem.Install_Project_Created_On__c;
            if(sProjectId == null)
                throw new ZD_Exception('No Install Project associated with System');
            
            List<Project__c> lProjects = [
                SELECT 
                	Id,
                	Building_Permit_Received_Date__c,
                	Electrical_Permit_Received_Date__c,
                	R_P_Reinstall_Date__c,
                	PVI_Rails_Installed_Date__c,
                	PVI_Electrical_Installed_Date__c,
                	PVI_Placed_In_Service_Date__c,
                	Net_Meter_Status__c,
                	Net_Meter_Install_Scheduled_Date__c,
                	Informed_Net_Meter_Installed_Date__c,
                	QC_Date__c,
                	QC_Passed__c
                FROM 
                	Project__c 
                WHERE Id = :sProjectId
            ];
            if(lProjects.isEmpty())
                throw new ZD_Exception('No Projects associated with Install Project ID');
            
            m_oInstallProject = lProjects[0];
                        
            // get the System Channel(s)
            List<System_Channel__c> lSystemChannels = [SELECT Id, Name FROM System_Channel__c
                                                      WHERE System__c = :sId];            
            if(lSystemChannels.isEmpty())
                throw new ZD_Exception('No System Channels associated with System ID Parameter');
            
            // get the System PV Production 
            
            // if we don't find any production table entries through an error
            Boolean bPVProductionFound = false;
            
            // store 
            List<Double> lACEnergyKwh = new Double[12];
            List<Double> lEnergyValueDollar = new Double[12];            
            for(Integer ix = 0; ix < 12; ix++)
            {
                lACEnergyKwh[ix] = 0;
                lEnergyValueDollar[ix] = 0;
            }
            
            for(Integer ix = 0; ix < lSystemChannels.size(); ix++)
            {
                Id oSystemChannelId = lSystemChannels[ix].Id;
                List<System_PV_Production__c> lSystemPVProduction = [
                    SELECT 
                    	Id, 
                    	Name, 
                    	DateTime__c, 
                    	Model_W__c,
                    	Production_W__c, 
                    	Energy_Value__c
                    FROM 
                    	System_PV_Production__c
                    WHERE 
                    	System_Channel__c = :oSystemChannelId
                    	AND CALENDAR_YEAR(DateTime__c) = :nYear
                ];
                if(lSystemPVProduction.isEmpty())
                    continue;
                
                bPVProductionFound = true;     
                
                // loop through all production and add 
                for(Integer jx = 0; jx < lSystemPVProduction.size(); jx++)
                {
                	DateTime oMonth = lSystemPVProduction[jx].DateTime__c;              
                    Integer nMonth = oMonth.month() - 1;
                    
                    Double dACEnergy = (lSystemPVProduction[jx].Model_W__c == null) ? 0 : lSystemPVProduction[jx].Model_W__c;
                    Double dEnergyValue = (lSystemPVProduction[jx].Energy_Value__c == null) ? 0 : lSystemPVProduction[jx].Energy_Value__c;
                                        
                    dACEnergy = dACEnergy + lACEnergyKwh[nMonth];
                    dEnergyValue = dEnergyValue + lEnergyValueDollar[nMonth];         
                    
                    lACEnergyKwh.set(nMonth, dACEnergy);
                    lEnergyValueDollar.set(nMonth, dEnergyValue);
                }
            }
            
            // error check
            if(bPVProductionFound)
            {
                m_lACEnergyKwh = lACEnergyKwh;
                m_lEnergyValueDollar = lEnergyValueDollar;
                
                // totals for energy production
                for(Integer ix = 0; ix < 12; ix++)
                {
                    m_dACEnergyTotalKwh = m_dACEnergyTotalKwh + lACEnergyKwh[ix];
                    m_dEnergyValueTotalDollar = m_dEnergyValueTotalDollar + lEnergyValueDollar[ix];
                }
            }
            else
            {
                String sTemp = 'No estimated production data available for this system';
                ApexPages.Message sError = new ApexPages.Message(ApexPages.Severity.FATAL, sTemp);
                ApexPages.addMessage(sError);                
            }
        }
        catch(Exception ex) {
            String sTemp = '';       
            sTemp = sTemp + ex.getMessage();            
            sTemp = sTemp + ' ' + ex.getStackTraceString();
            ApexPages.Message sError = new ApexPages.Message(ApexPages.Severity.FATAL, sTemp);
            ApexPages.addMessage(sError);
        }
    }
}