posiGen_FullsendBox/src/objects/Projected_Savings__c.object
<CustomObject>
    <fields>
        <fullName>Count_Of_Projected_Months__c</fullName>
        <label>Count Of Projected Months</label>
        <summaryForeignKey>Projected_Savings_Line_Item__c.Projected_Savings__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Projected Savings</label>
    <nameField>
        <label>Projected Savings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projected_Savings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Projected_Savings_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Month_Bill_Dollars__c</fullName>
        <label>Month Bill Dollars</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Month_Bill_Usage_kWh__c</fullName>
        <label>Month Bill Usage kWh</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_Projected__c</fullName>
        <label>Month Projected</label>
        <length>9</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numeric_Month_Projected__c</fullName>
        <formula>CASE( Month_Projected__c , 
  &quot;January&quot;, 1, 
  &quot;February&quot;, 2, 
  &quot;March&quot;, 3, 
  &quot;April&quot;, 4, 
  &quot;May&quot;, 5, 
  &quot;June&quot;, 6, 
  &quot;July&quot;, 7, 
  &quot;August&quot;, 8, 
  &quot;September&quot;, 9, 
  &quot;October&quot;, 10, 
  &quot;November&quot;, 11, 
  12)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Numeric Month Projected</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projected_Savings__c</fullName>
        <label>Projected Savings</label>
        <referenceTo>Projected_Savings__c</referenceTo>
        <relationshipLabel>Projected Savings Line Items</relationshipLabel>
        <relationshipName>Projected_Savings_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Projected Savings Line Item</label>
    <nameField>
        <label>Projected Savings Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projected Savings Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/AddProjectedSavingsLIsController.cls
public class AddProjectedSavingsLIsController {

    public String newPSLIs { get; set; }

    public PageReference createmonths()
    {
       Id psId = ApexPages.currentPage().getParameters().get('id');
       //Id psId = 'a4S7A0000000ElH';
       Decimal myCount = [SELECT Count_Of_Projected_Months__c FROM Projected_Savings__c WHERE Id = :psId].Count_Of_Projected_Months__c;
       Integer psliCount = myCount.intValue();
       added = false;
       if (psliCount < 12)
       {
           List<Projected_Savings_Line_Item__c> newPSLIs = new List<Projected_Savings_Line_Item__c>(); 
           String[] months = new String[]{'January','February','March','April','May','June','July','August','September','October','November','December'};
           for (String month : months)
           {
              Projected_Savings_Line_Item__c psli = new Projected_Savings_Line_Item__c(Name=month+' Projected Savings', 
                 Month_Projected__c=month, Projected_Savings__c=psId);
              newPSLIs.add(psli);
           }
           insert newPSLIs;
           added = true;
       }
       return null;
    }
    
    public Boolean added { get; set; }
    
    Id psId;
    public List<Projected_Savings_Line_Item__c> psliList {get;set;}
    
    public AddProjectedSavingsLIsController(){
        psId = ApexPages.currentPage().getParameters().get('id');
        //psId = 'a4S7A0000000ElH';
        psliList = [SELECT Projected_Savings__c, Name, Month_Projected__c, Month_Bill_Dollars__c, Month_Bill_Usage_kWh__c
                    FROM Projected_Savings_Line_Item__c WHERE Projected_Savings__c = :psId
                    ORDER BY Numeric_Month_Projected__c]; 
    }
    
    public void save(){
        update psliList;
    }
    
    public PageReference saveAndReturn() {
        update psliList;
        PageReference parentPage = new PageReference('/' + ApexPages.currentPage().getParameters().get('id'));
        //parentPage.setRedirect(true);
        return parentPage;
    }
    
    public void insertPSLIs(){
        insert psliList;
    }

}