posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Systems__c.object
<CustomObject>
    <fields>
        <fullName>Install_Project_Created_On__c</fullName>
        <inlineHelpText>This is the install project the system was initially created on.</inlineHelpText>
        <label>Install Project Created On</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>PV Install</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Systems Created For This Install</relationshipLabel>
        <relationshipName>Systems_Created_For_This_Install</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>System</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Systems Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <description>Main Record Type</description>
        <label>System</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/ZD_EEProject_System_Controller.cls
public class ZD_EEProject_System_Controller {
/*
    private final Project__c m_oProject;
    
    public ZD_EEProject_System_Controller(ApexPages.StandardController stdController) {
        Id oId = stdController.getId();
        this.m_oProject = [
            SELECT
                Id,
                Name,
                Opportunity__c
            FROM
                Project__c
            WHERE
                Id = :oId
        ];
    }
    
    public String getSystemId() {
        String sResult = '';
                
        // get the opportunity
        Id oOpportunityId = m_oProject.Opportunity__c;
        
        // get the PV Install project type
        RecordType oProjectInstallRecordType = [
            SELECT
                Id, 
                Name 
            FROM 
                RecordType 
            WHERE 
                sObjectType = 'Project__c'
                AND Name = 'PV Install'
        ];
        
        // project has a lookup relationship to opportunity
        List<Project__c> lProjects = [
            SELECT
                Id,
                Name,
                Opportunity__c,
                RecordTypeId
            FROM
                Project__c
            WHERE
                Opportunity__c = :oOpportunityId
                AND RecordTypeId = :oProjectInstallRecordType.Id
        ];
                
        if(lProjects.size() == 0)
            return sResult;

        Id oProjectId = lProjects[0].Id;
        
        // system has a master-detail relationship to project
        List<Systems__c> lSystems = [
            SELECT
                Id,
                Name
            FROM
                Systems__c
            WHERE
                Install_Project_Created_On__c = :oProjectId
        ];
            
        if(lSystems.size() == 0)
            return sResult;

        Id oSystemId = lSystems[0].Id;
        
        sResult = '' + oSystemId;
        
        return sResult;
    }*/
}