posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <formula>CASESAFEID(Milestone__r.Project__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProjectId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Milestone__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK( Milestone__r.Project__c , Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Number_within_Milestone__c</fullName>
        <label>Task Number (within Milestone)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Task - MPM</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Time__c.object
<CustomObject>
    <fields>
        <fullName>Date_Incurred__c</fullName>
        <label>Date Incurred</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <label>Hours Worked</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incurred_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incurred By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Time</relationshipLabel>
        <relationshipName>Time</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Timecards Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/ProjectTimeTableController.cls
public class ProjectTimeTableController
{
    private List<Task__c> projectTasks;
    private List<Time__c> taskTimes;
    private Project__c project;
    
    public ProjectTimeTableController()
    {
        project =	[SELECT Id,Name FROM Project__c WHERE Id = :(IdConversionHelper.ID15to18(ApexPages.currentPage().getParameters().get('id'))) LIMIT 1];
        
        projectTasks = [SELECT 
                        Id, 
                        ProjectID__c,
                        (SELECT Id FROM Time__r) 
                        FROM
                       	Task__c
                       	WHERE
                        ProjectID__c = :project.id
                       ];
        
    
    	taskTimes = [SELECT
                     Id, 
                     Name, 
                     Task__r.ID, 
                     Task__r.Name,
                     Task__r.Project_Name__c,
                     Task__r.ProjectID__c,
                     Date_Incurred__c,
                     Incurred_By__r.Id,
                     Incurred_By__r.Name,
                     Description__c,
                     Hours_Worked__c
                     FROM
                     Time__c
                     WHERE Task__r.ProjectID__c = :project.id
                     ORDER BY Task__r.Project__c, Task__r.Task_Number_Within_Milestone__c
                    ];
    }
    
    public List<Time__c> getTaskTimes()
    {
        return this.taskTimes;
    }
}