posiGen_FullsendBox/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>System_Removed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System To Remove</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Systems__c.Name</field>
                <operation>startsWith</operation>
                <value>S</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Systems__c</referenceTo>
        <relationshipLabel>Removal Project</relationshipLabel>
        <relationshipName>Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/objects/Systems__c.object
<CustomObject>
    <label>System</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Systems Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <recordTypes>
        <fullName>System</fullName>
        <active>true</active>
        <description>Main Record Type</description>
        <label>System</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

posiGen_FullsendBox/src/classes/ZD_Project_Utility.cls
public class ZD_Project_Utility {

    public static void copyFieldRemovalProjectToSystem(Project__c oProject, String sSourceField, String sDestinationField)
    {
        // check if this project is a PV Removal record type
        Map<ID,RecordType> mRecordTypes = new Map<ID,RecordType>([Select ID, Name From RecordType Where sObjectType = 'Project__c']);
		if(!mRecordTypes.get(oProject.recordTypeID).name.containsIgnoreCase('PV Removal'))
            return;
        
        // get the system removed project
    	List<Systems__c> lSystem = [SELECT Id FROM Systems__c WHERE Id = :oProject.System_Removed__c]; 
        if(lSystem.isEmpty())
            return;
        
        // copy the source project field to the destination system field
        lSystem[0].put(sDestinationField, oProject.get(sSourceField));        
        update lSystem[0];
    }
}